### ISSUE TITLE
Questions with regards to lifetimes

### ISSUE THREAD

**Issue by CumpsD** [influxdata/influxdb-client-csharp#105]
A few questions with regards to best practices for object lifetimes.

Is the client created by `InfluxDBClientFactory` safe to be registered as a Singleton for the lifetime of the application?

```csharp
InfluxDBClientFactory.Create(influxEndpoint.ToString(), token.ToCharArray());
```

Is the WriteApi created by `GetWriteApi` intended to be created and disposed on every write?
```csharp
influxDbClient.GetWriteApi(writeOptions);
```

What I'm playing with now:

```csharp
            // TODO: What is the usage pattern for influxdbclient?
            containerBuilder
                .Register(context =>
                {
                    return InfluxDBClientFactory.Create(
                        influxEndpoint.ToString(),
                        token.ToCharArray());
                })
                .SingleInstance()
                .As<InfluxDBClient>();

            containerBuilder
                .Register<Func<WriteApi>>(context =>
                {
                    var influxDbClient = context.Resolve<InfluxDBClient>();

                    var writeOptions = WriteOptions
                        .CreateNew()
                        .BatchSize(5000)
                        .FlushInterval(1000)
                        .JitterInterval(1000)
                        .RetryInterval(5000)
                        .Build();

                    return () => influxDbClient.GetWriteApi(writeOptions);
                })
                .As<Func<WriteApi>>();
```

```csharp
        private static void WriteTemperature(
            Func<WriteApi> writeApi,
            string location,
            double value)
        {
            var temperature = new Temperature
            {
                Location = location,
                Value = value,
                Time = DateTime.UtcNow
            };

            using (var writeClient = writeApi())
            {
                // TODO: Get bucket and org from config
                writeClient.WriteMeasurement(
                    "functional-living",
                    "cumps",
                    WritePrecision.Ns,
                    temperature);

                writeClient.Flush();
            }
        }
```

**Comment by bednar** [comment]
Hi @CumpsD,

> Is the client created by InfluxDBClientFactory safe to be registered as a Singleton for the lifetime of the application?

Yes

> Is the WriteApi created by GetWriteApi intended to be created and disposed on every write?

It depends on your use-case. The `WriteApi` uses batching with auto-flush strategy. If you will write a lot of data then keep alive `WriteApi` for the lifetime of the application.

Otherwise you could dispose a client on every write.

Currently we have in review a new `WriteApiAsync` (https://github.com/influxdata/influxdb-client-csharp/pull/102) without batching that could be a useful for second strategy.

Regards

**Comment by CumpsD** [comment]
Thanks!

What happens to `WriteApi` on exception?

I found https://github.com/influxdata/influxdb-client-csharp/blob/b6b8e973b053d69d01ae5d5ed7accba96a6ed1b2/Client/WriteApi.cs#L194-L198

Does it rebuilt itself and retry on exception? Or is there a way to?

That seems to be the only concern I have with keeping `WriteApi` around for the lifetime of the application.

**Comment by bednar** [comment]
It depends on type of error:

- retryable error from InfluxDB server (HTTP 429 or 503):  publish `WriteRetriableErrorEvent` event and retry the write after specified delay: https://github.com/influxdata/influxdb-client-csharp/blob/b6b8e973b053d69d01ae5d5ed7accba96a6ed1b2/Client/WriteApi.cs#L139
- not retryable error  from InfluxDB server (e.a. incorrect LineProtocol): publish `WriteErrorEvent` and continue with next batch: https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#handle-the-error-write

**Comment by CumpsD** [comment]
Thanks @bednar! I see now, the exception bit I linked is really for unhandled exceptions in the WriteApi, not for the stuff you deal with like the non retryable errors.
