### ISSUE TITLE
Bulk Writes in Write API 

### ISSUE THREAD

**Issue by SGStino** [influxdata/influxdb-client-csharp#112]
I've just migrated from InfluxDB.LineProtocol to this library using the WritePointsAsync method.

Code-wise, everything looks to work correctly. But first attempt at uploading something to InfluxCloud had me ..

WritePointsAsync "never" seemd to return. At least, never before i grew inpatient and killed the client.

After investigating the source code of the API, things became clear:
`WritePointsAsync` just is implemented as:
```
            foreach (var point in points) await WritePointAsync(bucket, org, point);
```

I'm not familiar yet with the 2.0 Protocols, howerver, i'd asume that there would be some kind of bulk upload option?
Because setting up an HTTP connection to the cloud for every single point sounds like it's going to be exactly as slow as i've experienced :) 

As reference, my debug output:
```Upload of 1000 points took 00:10:16.8700501```

That's a little insane compared to the < 100ms against the InfluxDB.LineProtocol version I had before.

**Comment by bednar** [comment]
Hi @SGStino,

thanks for the issue, We will take a look. 

Meanwhile you could use this workaround:

```csharp
List<PointData> points = ...;

await _writeApi.WriteRecordsAsync(WritePrecision.Ns, points.Select(point => point.ToLineProtocol()).ToList());
```

Regards

**Comment by bednar** [comment]
Hi @SGStino,

The issue is fixed in [1.11.0 milestone](https://github.com/influxdata/influxdb-client-csharp/milestone/14). 

If you would like to use a preview version use our nightly build:

```
dotnet add package InfluxDB.Client --version 1.11.0-dev.1166
```

Regards

**Comment by SGStino** [comment]
Ok, i'll give it a spin tomorrow. 
The workaround works fine, and from reviewing the commit,
So I believe the result should be the same.

**Comment by SGStino** [comment]
Spins like a kitten...
500ms for 500 points, 400ms for 1 point. + 200ms jitter.
The transatlantic connection does really amplify the problem.

Thanks for the quick fix!

**Comment by bednar** [comment]
You are welcome
