### ISSUE TITLE
Suggestion: Known Exceptions

### ISSUE THREAD

**Issue by SGStino** [influxdata/influxdb-client-csharp#114]
__Proposal:__
Add custom known-exceptions to the API.

__Current behavior:__
Currently it throws a `HttpException` with an `ErrorBody` that needs to be parsed to know what went wrong.

__Desired behavior:__
I'd suggest adding and `Influx...Exception` familiy with the ErrorBody as properties on the `Exception`:
For example `InfluxRateLimitException` for `org {org} has exceeded limited_write plan limit`

__Use case:__
This helps people writing clean error handling code, for example with Polly's Policies.

Currently I'm writing them as I encounter the exceptions, but I can't really find a concise list of the possible error responses. 
Of course, all this is only possible if the errors are consistent and well defined on the influx server side.

**Comment by bednar** [comment]
Hi @SGStino,

Thanks for suggestion. I think that a correct solution will be prepare a family of HTTP exception: `RequestTimeoutException`, `InternalServerErrorException`, `TooManyRequestsException`, ...

You will be able to hook to the `TooManyRequestsException` and correctly handle exceeded limit exception.

Regards
