### ISSUE TITLE
Why does InfluxDBClientOptions.Builder.AuthenticateToken not accept string parameter?

### ISSUE THREAD

**Issue by GF-Huang** [influxdata/influxdb-client-csharp#117]
Why does `InfluxDBClientOptions.Builder.AuthenticateToken` not accept `string` parameter?

`"token".ToCharArray()` is meaningless do by API user.

![image](https://user-images.githubusercontent.com/4510984/90439961-0c90e880-e109-11ea-8185-84aa20cda590.png)

**Comment by bednar** [comment]
Hi @GF-Huang,

thanks for your suggestion. Yes, you are right.

The accepting only `char[]` is meaningless. It originally comes from our Java client API and in a C# world it is meaningless.

We will add a variant of `AuthenticateToken` method that will accept a `string`.

Regards
