### ISSUE TITLE
No timestamp returned via POCO based QueryAsync<T>

### ISSUE THREAD

**Issue by ritchiecarroll** [influxdata/influxdb-client-csharp#119]
With a simple class like the following:
```C#
    [Measurement("point")]
    public class Point
    {
        [Column("tag", IsTag = true)] public string Tag { get; set; }
        [Column("min")] public double Minimum { get; set; }
        [Column("max")] public double Maximum { get; set; }
        [Column("avg")] public double Average { get; set; }
        [Column("flags")] public uint QualityFlags { get; set; }
        [Column(IsTimestamp = true)] public DateTime Timestamp { get; set; }
    }
```

Data writes fine and I can verify through a CLI query that timestamps are accurately stored, but when retriving data, the timestamp is always zero, i.e., `DateTime.MinValue`.

Here's the query code:

```C#
        public static async IAsyncEnumerable<Point> ReadPoints(string influxDBHost, string fluxQuery)
        {
            using InfluxDBClient influxDBClient = InfluxDBClientFactory.Create(influxDBHost, Token);
            QueryApi queryAPI = influxDBClient.GetQueryApi();

            List<Point> points = await queryAPI.QueryAsync<Point>($"from(bucket:\"{PointBucket}\"){fluxQuery}", OrganizationID);

            foreach (Point point in points)
                yield return point;
        }
```

Seems like the marked `IsTimestamp` column is being missed during deserialization.

Also, tried several variations on POCO timestamp column:

```C#
[Column("Timestamp", IsTimestamp = true)] public DateTime Timestamp;
[Column("time", IsTimestamp = true)] public DateTime Timestamp;
[Column("_time", IsTimestamp = true)] public DateTime Timestamp;
[Column(IsTimestamp = true)] public DateTime Time;
```

**Comment by ritchiecarroll** [comment]
As a side note, have you considered creating an overload that will directly return an `IAsyncEnumerable<T>` from a `QueryAsync` method as an optimization?

Could even provide a new method like `QueryAsyncEnumerable<T>`

**Comment by ritchiecarroll** [comment]
> As a side note, have you considered creating an overload that will directly return an `IAsyncEnumerable<T>` from a `QueryAsync` method as an optimization?
> 
> Could even provide a new method like `QueryAsyncEnumerable<T>`

I added a pull request for this feature #121

FYI, this PR includes both the timestamp fix plus the enhancement - let me know if I should separate these.

**Comment by rhajek** [comment]
Hi @ritchiecarroll, thanks for using our client library and creating PRs. We will include them in the next release.  I tried couple of tests and deserialisation of timestamp works only with Column.Name annotation set on "time". 

```[Column("time", IsTimestamp = true)] public DateTime Timestamp { get; set; }``` 

I found also problem with DateTime.Now, Poco with such timestamp is not written to InfluxDB, `System.ArgumentException : Timestamps must be specified as UTC` is not propagated or shown.

We definitely need  to add more unit tests related to Poco and timestamps.

**Comment by shialex** [comment]
I am experiencing a similar issue where querying DateTime via a POCO always returns `DateTime.MinValue` using InfluxDB.Client 1.15.0. I'm using logic similar to the one found here [https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#queries](url). 

```
var cycles = await queryApi.QueryAsync<Cycle>(flux, "org_id");
```

Our object looks like the following:

```
[Measurement("cycle")]
public class Cycle
{
    [Column(IsTimestamp = true)] public DateTime Time;
    [Column("cycle_start")] public DateTime CycleStart { get; set; }
    [Column("cycle_end")] public DateTime CycleEnd { get; set; }
    ...
}
```

Looking through the queried `cycles` list, all `CycleStart` and `CycleEnd` will have `DateTime.MinValue` as their value even though I can verify that the values being published correctly.

**Comment by bednar** [comment]
Hi @shialex,

Could you share how you Flux query looks like? The query should use [pivot() function](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/built-in/transformations/pivot/), something like:

```c#
var query = $"from(bucket:\"{bucket}\") " +
                        "|> range(start: 0) " +
                        "|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")";
``` 

Check out this example: [PocoQueryWriteExample.cs](https://github.com/influxdata/influxdb-client-csharp/blob/master/Examples/PocoQueryWriteExample.cs).

Regards

**Comment by shialex** [comment]
Hello @bednar,

You are completely correct, I forgot about the pivot() function in the Flux query.

Thanks so much for your help!

**Comment by teddybee** [comment]
@bednar I have the same issue as @shialex , the timestamp in the POCO is 0001. 01. 01. 0:00:00. I used the pivot in flux.
The root cause probably in the fluxRecord.GetTimeInDateTime() method, as it is also has this fault.
fluxRecord.GetTime() is working well.

**Comment by wen2204** [comment]
Hi ,I encounter the same error with the lateast version InfluxDB.Client 2.1.0.
this is the class.
[Measurement("temperature")]
        private class Temperature
        {
            [Column("location", IsTag = true)] 
            public string Location { get; set; }

            [Column("value")] 
            public double Value { get; set; }

            [Column("time", IsTimestamp = true)] 
            public DateTime Time;
        }

      this is query code:
        var flux2 = $"from(bucket:\"{bucket}\") |> range(start: 0) " +
                        "|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")";
            var temperatures = await influxDBClient.GetQueryApi().QueryAsync<Temperature>(flux2, org);
            temperatures.ForEach(temperature =>
            {
                _logger.LogInformation($"{temperature.Location}: {temperature.Value} at {temperature.Time}");
            });

the temperature.Time is still the wrong time:0001/1/1 0:00:00

**Comment by bednar** [comment]
Hi @wen2204,

Can you share debug output from client? You can enable debug mode by: 

```csharp
var client = InfluxDBClientFactory.Create("http://localhost:9999",
    "my-token".ToCharArray());
client.SetLogLevel(LogLevel.Body);
```

Regards
