### ISSUE TITLE
Writing out null values

### ISSUE THREAD

**Issue by grantbridges** [influxdata/influxdb-client-csharp#125]
Is there any way to write out a null value in a PointData object?  I only see overloads for non-nullable types.  My use case is I'm trying to write out 12 series with identical timestamps (under 1 tag) so when I query for them, I get back the same number of records back for all series with identical timestamps on every record.

**Comment by bednar** [comment]
Hi @grantbridges,

Could you share little bit more how your data looks like? Is your tag same for every series?

The time series is defined as a combination of tags and timestamp so following example produce only one record in InfluxDB:

```
data,tag=a field_value1=10 1
data,tag=a field_value2=10 1
```

Regards

**Comment by grantbridges** [comment]
Hi @bednar ,

Sure, here's a simple representation of what I'm trying to do in translating my own C# data model to the Influx PointData model:

```
List<PointData> points = new List<PointData>();

foreach (var row in dataRows)
{
	var point = PointData.Measurement("Log")
		.Tag("DataAcqConfigId", "(some id for this series)")
		.Timestamp(row.Timestamp, WritePrecision.S);

	foreach (var field in row.Data)
	{
		if (field.Value.HasValue)
		{
			point = point.Field(field.Key, field.Value.Value);
		}
	}

	points.Add(point);
}
```
where my "dataRow" type is simply set up like:

```
public class InfluxUploadDataRow
{
	public DateTimeOffset Timestamp { get; set; }
	public Dictionary<string, double?> Data { get; set; }
}
```

So in the case where I have null for a value in my row's "Data" dictionary, I'd like to be able to write out a null in my Influx database. Right now I'm just having to exclude it altogether from the PointData fields for that timestamp, but that leads me to having uneven numbers of records for each of my fields in a given series.

Hope that makes sense.

**Comment by bednar** [comment]
Thanks for explanations, but unfortunately `null` is not a valid field value and is unsupported by InfluxDB. 

If your `InfluxUploadDataRow` doesn't have data then nothing will be written into database.

Check LineProtocol date types:

- https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/#data-types-and-format

**Comment by grantbridges** [comment]
Thanks for the help
