### ISSUE TITLE
unable to parse authentication credentials - SIGNIN Resource throws 404

### ISSUE THREAD

**Issue by DMDTT** [influxdata/influxdb-client-csharp#130]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Use 1.12.0 influxdb.client nuget package
2. _InfluxDBClient = InfluxDBClientFactory.Create("http://localhost:8086", "user", "password".ToCharArray());
3. on writing measurements I'm getting the error "{"error":"unable to parse authentication credentials"}"
3.1 in fiddler I see a 404 HttpError on POST /api/v2/signin HTTP/1.1
3.2 the user "user" with its password "password" exists (no admin)
3.3 the sign in request has a Authorization Header: Basic.... it contains the correct username:password content

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Specifications:__
 - Client Version: 1.12.0 C#
 - InfluxDB Version: 1.8
 - Platform: Windows

**Comment by sranka** [comment]
Usage against InfluxDB 1.x is a bit different comparing to InfluxDB v2 that is primarily targeted by this library, as mentioned in bold at the top of the main [readme](https://github.com/influxdata/influxdb-client-csharp#influxdb-client-csharp)  and explained in https://github.com/influxdata/influxdb-client-csharp#influxdb-18-api-compatibility. https://github.com/influxdata/influxdb-client-csharp/blob/master/Examples/InfluxDB18Example.cs shows that `InfluxDBClientFactory.CreateV1` shall be used is your step (2) when you run the client against InfluxDB 1.8.

**Comment by DMDTT** [comment]
@sranka in fact, right before your comment I discovered exactly this method --> InfluxDBClientFactory.CreateV1

thanks a lot
