### ISSUE TITLE
Error handling?

### ISSUE THREAD

**Issue by dracan** [influxdata/influxdb-client-csharp#135]
In the examples, it shows the happy path - eg...

```
var point = PointData.Measurement("MyMeasurement")
	.Tag("sometag", "mytag")
	.Field("amount", amount)
	.Timestamp(timestamp, WritePrecision.Ns);

using var client = InfluxDBClientFactory.Create(_serverUri, _influxDbAuthToken);
using var writeApi = client.GetWriteApi();
writeApi.WritePoint("MyBucket", _organisation, point);
```

But there's no mention of how to handle unhappy paths.

`WritePoint` returns void. If I change for example the token to something invalid, no exceptions are thrown either. Running the above sample with a setting on the command line shows stdout information about what's wrong - but I'm assuming it's not expected that we have to capture and parse stdout to detect errors.

I'm sure I must be missing something - but how should errors be handled?

**Comment by bednar** [comment]
Hi @dracan,

the `client.GetWriteApi();` uses batching strategy for writes. The writes are dispatched at background thread. You could hook to errors via:

```csharp
//
// Register event handler
//
writeApi.EventHandler += (sender, eventArgs) =>
{
    if (eventArgs is WriteErrorEvent @event)
    {
        var exception = @event.Exception;
        
        //
        // handle error
        //
    }
};
```

or you could you `WriteApiAsync` which is simplified version of `WriteApi` without batching support and directly propagates errors.

- https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#writes
- https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#using-writeapiasync

Regards

**Comment by dracan** [comment]
Thanks @bednar - that's useful to know. The `WriteApiAsync` version sounds like what I'm after. Closing ticket.
