### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by MihaMarkic** [influxdata/influxdb-client-csharp#139]
I'm just wondering whether this client is thread safe or not. Technically it could be but it probably isn't. Asking this because I'd like to use it efficiently within REST API.
Perhaps readme could be update with this info.

**Comment by bednar** [comment]
Hi @MihaMarkic,

thanks for the question.

The client is ThreadSafe.

Regards

**Comment by MihaMarkic** [comment]
Thanks

**Comment by ravindra-gaikawad** [comment]
If client is thread safe, then can I use single instance of ApiClient (e.g. WriteApi, QueryApi or DeleteApi) throughout my application?

**Comment by MihaMarkic** [comment]
@ravindra-gaikawad If it is thread safe then yes, you can use a singleton. That's how I understand it.

**Comment by bednar** [comment]
> If client is thread safe, then can I use single instance of ApiClient (e.g. WriteApi, QueryApi or DeleteApi) throughout my application?

Yes, APIs are thread safe.
