### ISSUE TITLE
Public methods but can not be used

### ISSUE THREAD

**Issue by tire0011** [influxdata/influxdb-client-csharp#142]
There is on the clientFactory a Create method with empty parameters. But when it is used a exception is comming up:
System.ArgumentException: 'Expecting a non-empty string for url'
but then should be the method not public if no one can use it.
using var influxDbClient = InfluxDBClientFactory.Create();

![influexDbIssue](https://user-images.githubusercontent.com/228717/102340071-5cd46600-3f96-11eb-82bb-41591b3a8025.jpg)

**Comment by bednar** [comment]
Hi @tire0011,

thanks for using our client. 

The method with empty parameters loads configuration from a `App.config` file. For more details see: https://github.com/influxdata/influxdb-client-csharp/blob/master/Client/README.md#client-configuration-file

We should check that the configuration exists and if isn't then should be used correct exception.

Regards

**Comment by tire0011** [comment]
okay but why is the factory method then public? why you not make it not private and call it from the public factory methods?

**Comment by bednar** [comment]
The `InfluxDBClientFactory.Create();` is way how to tell to the client that should be configured from config file.
