### ISSUE TITLE
Client::WriteApi::WritePoints() fails without any exceptions

### ISSUE THREAD

**Issue by LeoCMade** [influxdata/influxdb-client-csharp#144]
__Steps to reproduce:__
Call Client::WriteApi::WritePoints() with some data (also 1 point is enough to reproduce the bug) from a for cycle without any other operations. The problem seems to happen if not enough time pass between each WritePoints() call.

__Expected behavior:__
Data is written to influxdb

__Actual behavior:__
Data insert is randomly skipped after the first write operation without any exceptions. This library is unusable because data is randomly skipped without any way to detect skipped data.

__Specifications:__
 - Client Version: 1.13.0
 - InfluxDB Version: 1.8.0
 - Platform: Windows 2019 Server

**Comment by bednar** [comment]
Hi @LeoCMade,

thanks for using our client.

The `WriteApi` uses batching mode to aggregate data and writes in batches. The batches could be configured via `WriteOptions`. The default configuration is: 
![image](https://user-images.githubusercontent.com/455137/104157973-a32db100-53ec-11eb-8dff-70ce4a99e5b0.png)

See: https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#writes

If you want write data without batching, then please use `WriteApiAsync`. See: 
https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#using-writeapiasync

Could you share little bit of your code?

Regards

**Comment by bednar** [comment]
Missing info...
