### ISSUE TITLE
WritePoint(pointData) silently fail with approx 30 sec delay when trying to write field value with different data type which was previously wrote.

### ISSUE THREAD

**Issue by digital-spinner** [influxdata/influxdb-client-csharp#147]
__Steps to reproduce:__

1. Follow the C# tutorial and populate basket with some float values.
2. Try to populate the same basked and measurement with different value type, eg. int.

__Expected behavior:__
Exception thrown on wrong data type is being tried to be pushed to InfluxDB on WritePoint(pointData) method.

__Actual behavior:__
Nothing happens except printing debug output messages shown below and hanging the app flow wor approx 30 seconds.
No exception - no information about issue. No data is being saved to DB I assume (nothin new is shown on data explorer UI).
Output debug messages:
```Flushing batches before shutdown.
The thread 0x1dd0 has exited with code 0 (0x0).
The InfluxDB does not specify "Retry-After". Use the default retryInterval: 5000
testhost Warning: 0 : The retriable error occurred during writing of data. Reason: 'unexpected error writing points to database: partial write: field type conflict: input field "used_percent" on measurement "mem" is type integer, already exists as type float dropped=1'. Retry in: 5s.
The thread 0x36e0 has exited with code 0 (0x0).
The InfluxDB does not specify "Retry-After". Use the default retryInterval: 25000
testhost Warning: 0 : The retriable error occurred during writing of data. Reason: 'unexpected error writing points to database: partial write: field type conflict: input field "used_percent" on measurement "mem" is type integer, already exists as type float dropped=1'. Retry in: 25s.
The thread 0x12b0 has exited with code 0 (0x0).
testhost Error: 0 : The WriteApi can't be gracefully dispose! - 30000ms elapsed.
```

__Specifications:__
 - Client Version: InfluxDB.Client 1.14.0
 - InfluxDB Version: 2.0.3
 - Platform: Linux Ubuntu 20.04

**Comment by bednar** [comment]
Hi @digital-spinner,

thanks for using our client.

The `WriteApi` uses batching mode to aggregate data and writes in batches. The batches could be configured via `WriteOptions`. The default configuration is: 
![image](https://user-images.githubusercontent.com/455137/104157973-a32db100-53ec-11eb-8dff-70ce4a99e5b0.png)

See: https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#writes

If you want to catch an exception then you should handle `WriteErrorHandle`. See: https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#handle-the-error-write

If you want to directly catch exception then use `WriteApiAsync`. See:
https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#using-writeapiasync

Regards

**Comment by digital-spinner** [comment]
OK, thanks.
