### ISSUE TITLE
Queryable Linq query hangs indefinitely when trying to execute it via a WebApi application

### ISSUE THREAD

**Issue by mariana-gendler** [influxdata/influxdb-client-csharp#151]
I am trying to execute the following query using the Influx.Client.Linq "Queryable" API:

```
var converter = new NumericSeriesEntryConverter(seriesId, tenant, storage);
var memberResolver = new NumericSeriesEntryMemberResolver();
var queryAPI = influxClient.GetQueryApi(converter);

 var query = from s in InfluxDBQueryable<NumericSeriesEntry>.Queryable(bucket, org, queryAPI, memberResolver)
                where s.SeriesId == seriesId
                select s;
```

The following  line hangs indefinitely without any errors:
` List<NumericSeriesEntry> results = query.ToList();`
 
 Executing the same logic via a .NET application works as expected, meaning that I am able to retrieve the results successfully

According the call stack, the logic hangs in the following method:

InfluxDB.Client.Linq.dll!InfluxDB.Client.Linq.Internal.InfluxDBQueryExecutor.ExecuteCollection<InfluxDBPOCWebApi.Entities.NumericSeriesEntry>
 	 	 	 	 	 	[External Code]
 	 	 	 	 	 	InfluxDBPOCWebApi.dll!InfluxDBPOCWebApi.Controllers.NumericSeriesEntryController.Get() Line 38
 	 	 	 	 	 	[External Code]

**Comment by bednar** [comment]
Hi @mariana-gendler,

thanks for feedback. 

I am not able to simulate the hangs 😞. I've try it with this testing app: https://github.com/influxdata/influxdb-client-csharp/tree/feat/linq-prototype/Examples.WebApi and everything works correctly.

But I also improved a `InfluxDBQueryExecutor.ExecuteCollection` to bring better solution for transform `Async` response from `QueryApi` to a synchronous LINQ results.

Could you please test your code with new version?

```bash
dotnet add package InfluxDB.Client.Linq --version 1.15.0-dev.linq.7
```

Could you also share a little bit more how your WebApi stack looks like?

Regards

**Comment by mtstowe81** [comment]
Hi @bednar,

@mariana-gendler provided a sample application that reproduces the issue for us.  please reference attached file.  I will ask her to re-test with your fix as well.

Thanks
[InfluxDBPOCWebApi.zip](https://github.com/influxdata/influxdb-client-csharp/files/5880467/InfluxDBPOCWebApi.zip)

**Comment by mariana-gendler** [comment]
Hi @bednar ,
Unfortunately, the issue still reproduces with the latest version of the code.
Please refer to the attached sample application that reproduces the issue and let me know if you have any questions

**Comment by mariana-gendler** [comment]
@bednar ,
Also wanted to mention that your samples contain a .NET core WebAPI application where as our existing legacy service is built on top of .NET standard WebAPI application so there might be some difference in that perspective

**Comment by bednar** [comment]
@mtstowe81, @mariana-gendler 

thanks for detail information. I just tried your `InfluxDBPOCWebApi` with Visual Studio for Mac and everything works:

![image](https://user-images.githubusercontent.com/455137/106007977-2884b700-60b7-11eb-95da-6982df22484e.png)

Which platform do you use? How do you start your WebApp?

**Comment by mariana-gendler** [comment]
@bednar ,
We run it directly from Visual studio in debug mode. The operation system is Windows 10. We have tried so far on two different developer machines and both have the same issue. 
I will try to reproduce it on a Virtual machine in Microsoft Azure to try to confirm that it's not related to any corporate machine issues.
In the meantime, if you could try to execute this application on a Windows machine and see if the issue reproduces it would be very helpful.

**Comment by bednar** [comment]
@mariana-gendler how much data do you have in InfluxDB? Maybe there is too much data…

Could you try limit the amount of data by something like: `Take(10)` or `where s.Timestamp > new DateTime(2021, 01, 20, 8, 20, 15, DateTimeKind.Utc)`?

**Comment by mariana-gendler** [comment]
@bednar ,
I have only one record for the seriesId that I'm using and I can successfully retrieve it while executing this code from a .NET application but not the WebAPI application.
In addition to this being reproducible on two developer machines, I managed to reproduce it on a Virtual Machine I just deployed on the Azure cloud.
This virtual machine is running Windows 10 and only has Visual Studio 2017 installed.

Please see the attached screenshot with the line of code and the call stack

![InfluxQueryHangsOnAzureVM](https://user-images.githubusercontent.com/67005232/106031571-6e348600-609d-11eb-91ab-3bd79c6468e3.PNG)

**Comment by bednar** [comment]
I am able to reproduce it too - Win 10 + Latest Visual Studio. I will try to figure out where is problem and fix it as soon as possible.

**Comment by bednar** [comment]
@mariana-gendler the issue is fixed in a latest preview version of library:

```
dotnet add package InfluxDB.Client.Linq --version 1.15.0-dev.linq.8
```

The problem was in transforming asynchronous response from InfluxDB into synchronous result in LINQ provider. I had to add a synchronous version of query into our `QueryApi` and use it in LINQ provider:

- https://github.com/influxdata/influxdb-client-csharp/blob/22f6f2bac55931c9de92da688f8df628b6b17cd4/Client/QueryApi.cs#L290
- https://github.com/influxdata/influxdb-client-csharp/blob/5a199bd0ec8896a065592d8cf1d9d04f6ab271c5/Client.Linq/Internal/QueryExecutor.cs#L65

**Comment by mariana-gendler** [comment]
@bednar ,
I can confirm that the issue is resolved in the latest version you provided.
Thanks a lot for the quick response!

**Comment by deanasheehan** [comment]
Thanks @bednar
