### ISSUE TITLE
async/await patterns and ConfigureAwait(false)

### ISSUE THREAD

**Issue by mtstowe81** [influxdata/influxdb-client-csharp#152]
Hello,

I have been reviewing your code base and found that there are some async/await and ConfigureAwait patterns that do not align with MSFT guidelines, especially if you wish to support both .NET Framework and Core.

1. ConfigureAwait(false)

Reference: [ConfigureAwait](https://devblogs.microsoft.com/dotnet/configureawait-faq/)

It is typically considered best practice for a driver/library to apply ConfigureAwait(false) internally so as to not perform any unnecessary context switching and avoid potential dead-locks.  Awaits without this are typically left in the application layer.

For example, [this](https://github.com/influxdata/influxdb-client-csharp/blob/master/Client/InfluxDBClient.cs) should have a ConfigureAwait(false) applied to it.
```
public async Task<Ready> ReadyAsync()
{
	try
	{
		return await _readyService.GetReadyAsync();
	}
	catch (Exception e)
	{
		Trace.TraceError($"The exception: '{e.Message}' occurs during check instance readiness.");

		return null;
	}
}
```

Should be written as:
```
public async Task<Ready> ReadyAsync()
{
	try
	{
		return await _readyService.GetReadyAsync().ConfigureAwait(false);
	}
	catch (Exception e)
	{
		Trace.TraceError($"The exception: '{e.Message}' occurs during check instance readiness.");

		return null;
	}
}
```

2. Unneeded awaits

I have observed that in cases there are awaits being performed when a task could have been simply returned and the overhead of the await avoided.

For example, [this](https://github.com/influxdata/influxdb-client-csharp/blob/master/Client/InfluxDBClient.cs) is an unneeded await as there is no processing on the result of the task within the method:
```
public async Task<HealthCheck> HealthAsync()
{
	return await GetHealthAsync(_healthService.GetHealthAsync());
}
```
and may be written as:
```
public Task<HealthCheck> HealthAsync()
{
	return GetHealthAsync(_healthService.GetHealthAsync());
}
```

The following await is appropriate as you require processing on the result of the asynchronous task.
```
public async Task<Ready> ReadyAsync()
{
	try
	{
		return await _readyService.GetReadyAsync();
	}
	catch (Exception e)
	{
		Trace.TraceError($"The exception: '{e.Message}' occurs during check instance readiness.");

		return null;
	}
}
```

Hope this helps.

**Comment by bednar** [comment]
Hi @mtstowe81,

thanks for your suggestion. It is very helpful 👍... every suggestion is welcome and appreciated. Thanks again.

I will improve our codebase ASAP.

Regards

**Comment by bednar** [comment]
@mtstowe81, I just started working on this. You could track progress here: https://github.com/influxdata/influxdb-client-csharp/compare/fix/async-await-configure

**Comment by bednar** [comment]
Hello @mtstowe81, I've prepare PR with fixed version of client - #154. Do you have time to quick review?

**Comment by mtstowe81** [comment]
Hi @bednar, I did a quick scan over your PR and I think it's safe to say you understand the concepts I presented in this enhancement request 👍 Thanks for your efforts!

**Comment by bednar** [comment]
Hi @mtstowe81, thanks for your quick review 👍
