### ISSUE TITLE
Documentation - How to select database, bucket, and retention policy when writing data?

### ISSUE THREAD

**Issue by kyledevans** [influxdata/influxdb-client-csharp#153]
I am trying to get started with InfluxDB by creating a small C# application, but I'm running into some pretty fundamental roadblocks.

First I was unable to write to a specific database using the POCO WriteMeasurement() method.  Eventually I managed to write simple data to my database using the WritePoint() method.  However with this method I can't see a way to select an existing retention policy.  So everything goes into "autogen".

Additionally, I ran into issues selecting my "org".  Some methods require an orgId, and others are fine with an org name.  I couldn't find documentation in the library that said to just use "default" for the org.  I saw that mentioned in the InfluxDB docs and simply guessed if it worked in the library.

I apologize if this comes across as a a bit of a brain dump or a rant, I just wanted to provide some feedback about some of the early hurdles I've encountered.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Connect to database
2. Try to figure out what org to use, what bucket to use, and what retention policy to use.
3. Try to find out how to specify in the C# library what org, bucket, and RP to use.

__Expected behavior:__
Documentation that explains things for people that are new to both InfluxDB and the C# library.  Or maybe there's some functionality in the library that is still work in progress?  I don't know.

__Actual behavior:__
I fumbled around trying various methods and various combinations of orgs, buckets, and RPs in the parameters.

__Specifications:__
 - Client Version: 1.15.0
 - InfluxDB Version: 2.0
 - Platform: Linux (Container)

**Comment by bednar** [comment]
Hi @kyledevans,

thanks for using our client and your issue

>  First I was unable to write to a specific database using the POCO WriteMeasurement() method. Eventually I managed to write simple data to my database using the WritePoint() method. However with this method I can't see a way to select an existing retention policy. So everything goes into "autogen".

The InfluxDB 2.0 has a retention policy specified for whole bucket. You could use something like that to specify which bucket is your destination:

```c#
[Measurement("h2o")]
private class H20Measurement
{
    [Column("location", IsTag = true)] public string Location { get; set; }

    [Column("water_level")] public double? Level { get; set; }

    [Column(IsTimestamp = true)] public DateTime Time { get; set; }
}


public async Task WriteData()
{
    var writeApi = _influxDbClient.GetWriteApiAsync();
    var measurement = new H20Measurement
    {
        Location = "coyote_creek", Level = 15.0D, Time = DateTime.UtcNow
    };

    await writeApi.WriteMeasurementAsync("my-bucket", "my-org", WritePrecision.S, measurement);
}
```

> Additionally, I ran into issues selecting my "org". Some methods require an orgId, and others are fine with an org name. I couldn't find documentation in the library that said to just use "default" for the org. I saw that mentioned in the InfluxDB docs and simply guessed if it worked in the library.

The `WriteApiAsync`, `WriteApi` and `QueryApi` is fine with the `name` or the `id`. So you could define defaults with something like this:

```csharp
const string bucket = "my-bucket-id";
const string org = "my-org-id";

var options = new InfluxDBClientOptions.Builder()
    .Url("http://localhost:8086")
    .AuthenticateToken("my-token".ToCharArray())
    .Bucket(bucket)
    .Org(org)
    .Build();

var client = InfluxDBClientFactory.Create(options);
```

For the managements API you should explicitly specify `name` or `id`, because the [InfluxDB API](https://docs.influxdata.com/influxdb/cloud/api/) is not consistent and depends on concrete use case.

Regards

**Comment by kyledevans** [comment]
Thanks for the clarification, but now I'm little more confused.  Because I seem to be able to write data to a bucket that has multiple retention policies ('autogen' and 'testrp' in my case).

I think I found a pretty major source of the confusion I was having.  In Chronograf, it labels "buckets" as "database".  Under the InfluxDB Admin page where you add/remove databases and retention policies.  So in the library I was looking all over for where to specify a database, and then in chronograf I've been looking for any mention of "bucket" within the admin screens.  I presume that the terminology changed with the 2.0 release.

I randomly decided to try specifying a bucket like this:
`Writer.WritePoint("mybucket/testrp", "default", data);`
Which let me successfully write data to the correct bucket and retention policy.  I believe it would be helpful to have examples or documentation for this, because I only figured it out by random guesswork.

Thanks again for the help!

**Comment by bednar** [comment]
The note about `InfluxDB 1.8 API compatibility` is here: 
https://github.com/influxdata/influxdb-client-csharp#influxdb-18-api-compatibility
and following example shows how to use the client with InfluxDB v1.8:
https://github.com/influxdata/influxdb-client-csharp/blob/master/Examples/InfluxDB18Example.cs

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
