### ISSUE TITLE
Query Relations between buckets in a timeframe for a tenant

### ISSUE THREAD

**Issue by weedkiller** [influxdata/influxdb-client-csharp#155]
How can we query across buckets, for a tenant.

**Use Case:** for e.g. people may rent out drones (`Drone-Sensors1`, Sensor`2`.. etc) for surveys etc. Each of those puts data in a different bucket, for each vendor/tenant.

Since this changes often, How can we model this in our C# Linq: or some way to use in our C# app.
 
 for e.g. we have 10 sensors1,2,3, etc. in different buckets. 

1. - [ ] We need to query that using a relationship (sensor & Zipcode)
2. - [ ] We need to query across the bucket  
3. - [ ] We need to query for time frames  (sensor, zip, bucket1, bucket3)
4. - [ ] We need to put security on top only for that client/vendor/tenant.

**Comment by bednar** [comment]
Hi @weedkiller,

thanks for using our client.

> How can we query across buckets, for a tenant.

You could join your queries by `join() function`:
https://docs.influxdata.com/influxdb/cloud/query-data/flux/join/

> Since this changes often, How can we model this in our C# Linq: or some way to use in our C# app.

You could use `QueryAsync` and map the results into your domain object:
- https://github.com/influxdata/influxdb-client-csharp/blob/be8f5ac4188d0b0186a4366a77f701f2908bb92e/Client/QueryApi.cs#L78.

```csharp
var query = "from(...";
var objects = (await _client.GetQueryApi().QueryAsync(query))
    .SelectMany(it => it.Records)
    .Select(record =>
    {
        // TODO map into DomainObject
        return "";
    });
```

Regards

**Comment by weedkiller** [comment]
Are buckets at a vendor/tenant level
