### ISSUE TITLE
System.Linq.Expressions.UnaryExpression.Convert function does not produce results as expected in the InfluxDB.Client.Linq package

### ISSUE THREAD

**Issue by mariana-gendler** [influxdata/influxdb-client-csharp#156]
Using the latest version of the "InfluxDB.Client.Linq" nuget package(1.16.0-dev.linq.10) and the "Queryable" API

I am executing the following query against our API:
https://localhost:44329/SOLAR/main/Series/NumericTimeSeries(21089c29-ac99-45c6-8c88-8907cdd5137e)/Entries?$filter=Timestamp+gt+2020-01-01T00:00:00.000Z+and+Timestamp+le+2020-12-31T23:59:59.999Z+and+Attributes/any(a:a/Name+eq+%27Quality%27+and+a/Value+eq+%27Good%27)

The query that I have defined using the Influx.Queryable API is as following:
```
var query = from s in InfluxDBQueryable<NumericSeriesEntry>.Queryable(this.Bucket, this.Org, this.QueryApi, this.memberNameResolver)
                            where s.SeriesId == this.SeriesId
                            select s;
```
The "query" is retuned to the contorller and the .NET Web API runtime applies that query against Influx which for some reason returns no results.
For testing purposes I added the following:

`results = query.ToList()`

returning results.AsQueryable() to the API instead of the "query"
This means that we have already executed the query against Influx and the "Convert" expression will be executed against the results that were already fetched and not the "lazy" query as in previous example.
In this case, I am able to get the results successfully as expected.
So I suspect that there might be some internal issue with the "Convert" implementation of the Influx.Queyrable that causes invalid filleting of the data.

**Comment by bednar** [comment]
Hi @mariana-gendler,

Could you please share a more info about your app?

- How do you transform `ODataQueryOptions` into `IQueryable`?
- Which version of OData library do you use?
- Do you have any special configuration for OData?

I am little bit straggeling to simulate your LINQ expresion:

```csharp
{value(SE.OIP.DFL.Services.OData.Controllers.MockQueryable`1[SE.OIP.Common.Entities.Series.NumericSeriesEntry]).Where($it => ((($it.Timestamp > value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.DateTimeOffset]).TypedProperty) AndAlso ($it.Timestamp <= value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.DateTimeOffset]).TypedProperty)) AndAlso $it.Attributes.Any(a => ((Convert(a.Name) == value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty) AndAlso (Convert(a.Value) == value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty))))).OrderBy($it => $it.Timestamp).Take(60001)}
```

My testing app: https://github.com/influxdata/influxdb-client-csharp/tree/feat/linq-prototype/Examples.WebApi produces following LINQ expression:

```csharp
 value(InfluxDB.Client.Linq.InfluxDBQueryable`1[Examples.WebApi.DomainEntity]).Where(s => (s.SeriesId == Parse("0f8fad5b-d9cb-469f-a165-70867728950e"))).Where($it => ((Convert((($it.Timestamp > value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.DateTimeOffset]).TypedProperty) AndAlso ($it.Timestamp <= value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.DateTimeOffset]).TypedProperty)), Nullable`1) AndAlso IIF(($it.Attributes == null), null, Convert($it.Attributes.Any(a => ((IIF((a == null), null, a.Name) == value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty) AndAlso (IIF((a == null), null, a.Value) == value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty))), Nullable`1))) == True))
```

- http://localhost:5000/domainEntity/odata?$filter=Timestamp+gt+2020-01-01T00:00:00.000Z+and+Timestamp+le+2020-12-31T23:59:59.999Z+and+Attributes/any(a:a/Name+eq+%27Quality%27+and+a/Value+eq+%27Good%27)

which is even more complicated 🤔.


Regards

**Comment by mariana-gendler** [comment]
Hi @bednar ,
To answer your questions above:
- Microsoft's .NET WebAPi runtime translates the OdataQueryOptions to IQueryable for us, so we do not do that manually.
- Our version is a bit outdated. Our service runs on top of .NET standard and not .NET core. We use "Microsoft.AspNet.WebApi" version 5.2.7
- I'm not aware of any special Odata configurations that we might have.
Let me do some further investigation on my end and see if I can provide any additional information that might be beneficial for reproducing the issue.

Thanks,
Mariana

**Comment by mariana-gendler** [comment]
Hi @bednar ,
I did some additional request pipeline debugging, below is the expression that is passed to Influx by the WebAPI .NET runtime:

{value(InfluxDB.Client.Linq.InfluxDBQueryable`1[SE.OIP.Common.Entities.Series.NumericSeriesEntry]).Where(s => (s.SeriesId == value(SE.OIP.Common.Repository.InfluxDB.Series.NumericSeriesEntryInfluxRepository).SeriesId)).Where($it => ((($it.Timestamp > value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.DateTimeOffset]).TypedProperty) AndAlso ($it.Timestamp <= value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.DateTimeOffset]).TypedProperty)) AndAlso $it.Attributes.Any(a => ((Convert(a.Name) == value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty) AndAlso (Convert(a.Value) == value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty))))).OrderBy($it => $it.Timestamp).Take(60001)}

This looks different from the one you have mentioned above.
Please let me know if that helps.

**Comment by bednar** [comment]
@mariana-gendler thanks for detail info. 

I guess that the problem comes with `Microsoft.AspNet.WebApi version 5.2.7`, let me test it deeply and we will see...

**Comment by mariana-gendler** [comment]
@bednar ,
As a reference.
When the expression is executed against a .NET list and not Influx the results are returned as expected.
I.e. The Influx query is as following:
```
 var query = from s in InfluxDBQueryable<T>.Queryable(this.Bucket, this.Org, this.QueryApi, this.memberNameResolver)
                            where s.SeriesId == this.SeriesId
                            select s;
                return await Task.FromResult(query.ToList().AsQueryable());
```
Not that query.ToList() was added to get the results before WebAPI applies the other query parameters.

And generated the Linq expression is as following:

`{System.Collections.Generic.List`1[SE.OIP.Common.Entities.Series.NumericSeriesEntry].Where($it => ((($it.Timestamp > value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.DateTimeOffset]).TypedProperty) AndAlso ($it.Timestamp <= value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.DateTimeOffset]).TypedProperty)) AndAlso $it.Attributes.Any(a => ((Convert(a.Name) == value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty) AndAlso (Convert(a.Value) == value(System.Web.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty))))).OrderBy($it => $it.Timestamp).Take(60001)}
`

**Comment by mariana-gendler** [comment]
@bednar,
I added the following line for debugging as suggested in your documentation:

var query = ((InfluxDBQueryable<NumericSeriesEntry>)this.queryable).ToDebugQuery()._Query;
Below is the value of the Influx query that is being sent to Influx as a result of the above Linq expression:

`from(bucket: p1) |> range(start: p4, stop: p5) |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") |> filter(fn: (r) => (r["series_id"] == p3) and (r["attribute_Quality"] == p7)) |> sort(columns: [p8], desc: p9) |> limit(n: p10)`

Does anything about this query look suspicious to you?

**Comment by mariana-gendler** [comment]
@bednar ,
I found that the issue is actually on our end. There was a mismatch in the way that we map our attributes vs the way that we try to query them. I fixed the issue and it now works as expected. 
Apologies for the inconvenience. Thank you so much for looking into it!
Also thanks for providing a way to debug the Influx query, that was very helpful in identifying the issue.

**Comment by bednar** [comment]
@mariana-gendler Awesome news 👍 

If you want also to debug values of parameter, than use following code:

```csharp
var influxQuery = ((InfluxDBQueryable<Sensor>) query).ToDebugQuery();
foreach (var statement in influxQuery.Extern.Body)
{
    var os = statement as OptionStatement;
    var va = os?.Assignment as VariableAssignment;
    var name = va?.Id.Name;
    var value = va?.Init.GetType().GetProperty("Value")?.GetValue(va.Init, null);

    Console.WriteLine($"{name}={value}");
}
Console.WriteLine(influxQuery._Query);
```
