### ISSUE TITLE
InfluxDB.Client.AspNetCore

### ISSUE THREAD

**Issue by deinok** [influxdata/influxdb-client-csharp#159]
Hi, we are using the InfluxDB.Client inside an AspNetCore Web application.

We have found that in order to integrate it more in AspNetCore we added some code that could be shared. Something like 'InfluxDb.Client.AspNetCore'.

Basicly, in our case we created the code to add an InfluxDB.Client in the ServiceCollection (DI), and also we added integration with AspNetCore Health Check system. So, I'm not sure if a PR adding what we have would be accepted.

**Comment by bednar** [comment]
Hi @deinok, thanks for using our client. Every PR is welcome! Let’s create it and we will take a look.

**Comment by bednar** [comment]
Project got stuck from my enterprise, for now you can close it. If they wake up again I will do it again.

_Originally posted by @deinok in https://github.com/influxdata/influxdb-client-csharp/issues/160#issuecomment-832539816_
