### ISSUE TITLE
"engine: cache-max-memory-size exceeded" when using WriteApiAsync

### ISSUE THREAD

**Issue by digital-spinner** [influxdata/influxdb-client-csharp#164]
__Steps to reproduce:__

1. Download and run provided example project on Windows 10 x64 1909 or newer (Visual Studio 2019 solution) in debug or release mode.
[InfluxSimpleLoadTest.zip](https://github.com/influxdata/influxdb-client-csharp/files/6002815/InfluxSimpleLoadTest.zip)
2. When running please observe Windows system RAM usage.

__Expected behavior:__
RAM should not be eaten indefinitely and after app shutdown it should be released.

__Actual behavior:__
Windows OS uses RAM indefinitely before app crashes.
When the writeApiAsync is got before each point write (see commented piece of code) than the RAM is eaten indefinitely but the app won't crash and everything runs until Windows OS hangs due to RAM usage issue.

```
Unhandled exception. InfluxDB.Client.Core.Exceptions.HttpException: unexpected error writing points to database: engine: cache-max-memory-size exceeded: (1075474000/1073741824)
   at InfluxDB.Client.Api.Service.WriteService.PostWriteAsyncWithIRestResponse(String org, String bucket, Byte[] body, String zapTraceSpan, String contentEncoding, String contentType, Nullable`1 contentLength, String accept, String orgID, Nullable`1 precision)
   at InfluxDB.Client.Api.Service.WriteService.PostWriteAsyncWithHttpInfo(String org, String bucket, Byte[] body, String zapTraceSpan, String contentEncoding, String contentType, Nullable`1 contentLength, String accept, String orgID, Nullable`1 precision)
   at InfluxDB.Client.Api.Service.WriteService.PostWriteAsync(String org, String bucket, Byte[] body, String zapTraceSpan, String contentEncoding, String contentType, Nullable`1 contentLength, String accept, String orgID, Nullable`1 precision)
   at InfluxDB.Client.WriteApiAsync.WriteData(String org, String bucket, WritePrecision precision, IEnumerable`1 data)
   at InfluxDB.Client.WriteApiAsync.WritePointsAsync(String bucket, String org, List`1 points)
   at Examples.Program.WriteBatchAsync(Int32 taskNo, Int32 pointsToWrite) in C:\Users\Test\Desktop\InfluxSimpleLoadTest\InfluxSimpleLoadTest\Program.cs:line 48
   at Examples.Program.Main(String[] args) in C:\Users\Test\Desktop\InfluxSimpleLoadTest\InfluxSimpleLoadTest\Program.cs:line 33
   at Examples.Program.<Main>(String[] args)
```

__Specifications:__
 - Client Version: 1.15.0
 - InfluxDB Version: 2.0.3
 - Platform: Windows 10 x64 for client, docker @ Ubuntu 20.04.2 - InfluxDB server

**Comment by bednar** [comment]
Hi @digital-spinner,

thanks for using our client. 

Did you try to reuse the `writeApiAsync` across `Tasks`? The better approach will be create one instance of `InfluxDB.Client` and `WriteApiAsync` for all `Tasks`.

Regards

**Comment by digital-spinner** [comment]
Thank you for your concern and answer!

I have tried to use one client and one writeApiAsync per task as in the example I have attached which results in the exception I have posted.

When I tried to get the new WriteApiAsync before each WritePointsAsync(...) method, then there is no exception but the RAM is eaten up to the point the Windows can't run anymore. The RAM usage of example console app stays at stable level the whole time it is running.

In my example you can set the parallelTask variable to only 1 and the result will be actually the same as when using multiple tasks.

**Comment by bednar** [comment]
The problem could caused by inefficient uses of `PointData` structure. The `PointData` is immutable => every new `field` or `tag` cause copying whole structure.

I've used a version with creating the LineProtocol:

```csharp
private static Task WriteSomethingRecord(WriteApiAsync writeApiAsync, Random randomGenerator)
{
    var lineProtocol = new StringBuilder();
    lineProtocol.Append("measurement,tagName=tagValue ");

    int i = 1;

    for (; i <= 100; i++)
    {
        lineProtocol.Append($"something_{i:D4}={randomGenerator.Next()}i,");
    }

    for (; i <= 200; i++)
    {
        lineProtocol.Append($"something_{i:D4}={randomGenerator.NextDouble()},");
    }

    for (; i <= 300; i++)
    {
        lineProtocol.Append($"something_{i:D4}=");
        lineProtocol.Append('"');
        foreach (var c in GenerateRandomString(randomGenerator, 64 * 1024))
        {
            switch (c)
            {
                case '\\':
                case '\"':
                    lineProtocol.Append("\\");
                    break;
            }

            lineProtocol.Append(c);
        }
        lineProtocol.Append('"');
        lineProtocol.Append(',');
    }
    
    // remove last ','
    lineProtocol.Remove(lineProtocol.Length - 1, 1);
    lineProtocol.Append(' ');
    
    var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
    lineProtocol.Append((BigInteger) (DateTime.UtcNow - epoch).TotalMilliseconds);
    
    return writeApiAsync.WriteRecordAsync(bucket, org, WritePrecision.Ms, lineProtocol.ToString());
}
```

and then the RAM usage is consistent. Today I don't have access to Win machine, so I did the test on MacOS. Could you test it with LineProtocol?

**Comment by digital-spinner** [comment]
Thank you. I have tested line protocol implementation as above. The issue persist. Please take a look onto attached screenshot.
I can't find what is actually eating up the RAM in the system even using Process Explorer - hmmm, maybe I don't know how to do it properly. The RAM usage of the app itself is kept at stable level.

![image](https://user-images.githubusercontent.com/19900487/108508547-48755800-72bc-11eb-8c61-226f4472526c.png)

**Comment by digital-spinner** [comment]
I have been testing the same examples also on Linux (Ubuntu 20.04) client OS inside vmware VM and found that the RAM usage there is not a problem, but the same exception occurs randomly. But I had to wait for it - it appeared after transferring about 30GB of data through the network interface.

**Comment by bednar** [comment]
The exception is thrown by InfluxDB. Does your hardware fit the sizing guideline? https://docs.influxdata.com/influxdb/v1.8/guides/hardware_sizing/

**Comment by digital-spinner** [comment]
Thank you for your answer. Now I understand that my bug report contains two issues actually.

About the exception - now I understand what is going on and maybe how to handle it properly - will need to do more tests and research though.

About the RAM usage / leak? on Windows - can you confirm the issue is real as I described?

**Comment by bednar** [comment]
Hi @digital-spinner,

Today, I had enough time investing your issue on Win platform and I got same results - too high RAM usage.

The RAM usage is in correlation with size of LineProtocol - If we reduce amount of **string** fields than the usage is lower.

#### Results
<img width="1280" alt="visualstudio2" src="https://user-images.githubusercontent.com/455137/109054890-bc5d9900-76de-11eb-8e97-0be2d1d26a8c.PNG">
<img width="1280" alt="visualstudio3" src="https://user-images.githubusercontent.com/455137/109054915-c4b5d400-76de-11eb-8e85-63fdf832a5fe.PNG">

#### Testing code
[Program.cs.txt](https://github.com/influxdata/influxdb-client-csharp/files/6038383/Program.cs.txt)

Regards

**Comment by digital-spinner** [comment]
Thank you! But did you noticed that this will never recover to the base state (before running the testing code)?
In my case only the reboot of Windows machine solves the issue.

**Comment by bednar** [comment]
It looks that problem is caused by High Usage of Non-Paged Pool:

<img width="757" alt="RamMap" src="https://user-images.githubusercontent.com/455137/109146657-67646600-7764-11eb-9275-4f9c92b946e5.PNG">

but the process `InfluxSimpleLoadTest.exe` doesn't consume it:

<img width="1129" alt="ProcessExplorer" src="https://user-images.githubusercontent.com/455137/109146743-7d722680-7764-11eb-8c90-a09a3dd42657.PNG">
<img width="798" alt="TaskManager" src="https://user-images.githubusercontent.com/455137/109146752-8105ad80-7764-11eb-84f2-5f5391411ab7.PNG">

Could you check it?

- https://docs.microsoft.com/en-us/sysinternals/downloads/rammap
- https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by digital-spinner** [comment]
Yes this is the behavior I'm experiencing. And the RAM can be released only by rebooting the Windows.

Moreover there is one strange thing.. When I run this code from Rider IDE as a first thing after the system reboot than I couldn't observe RAM eating.. but when I run it even from the console like 'dotnet run --configuration Release' than the issue reappears. Of course the same happen when running from Visual Studio.

Raider:
![01 - RUN FROM RIDER](https://user-images.githubusercontent.com/19900487/109509549-4ae86680-7aa1-11eb-9b63-5c905a2484dc.png)

Console:
![02 - RUN FROM CONSOLE](https://user-images.githubusercontent.com/19900487/109509569-4f148400-7aa1-11eb-941b-3b7a8836c1d8.png)

So now I'm scratching my head even more.

**Comment by digital-spinner** [comment]
It appears that Windows Defender Network Service is eating NonPaged pool (**wdnf**) if InfluxDb.Client is running..

Before start:
![WDNF-START](https://user-images.githubusercontent.com/19900487/109625204-55593d80-7b3f-11eb-9e10-c4aa09b8fc80.png)

After some time of running:
![WDNF-STOP](https://user-images.githubusercontent.com/19900487/109625230-5d18e200-7b3f-11eb-8af9-dfddc40e42d1.png)

**Comment by digital-spinner** [comment]
It looks like **wdnf** (Windows Defender Network Filter) is causing the issue when InfluxDb.Client is running.

![WDNF-STOP](https://user-images.githubusercontent.com/19900487/109625755-fb0cac80-7b3f-11eb-9c28-37b779c8d6d8.png)

**Comment by bednar** [comment]
@digital-spinner interesting news... Did you try to disable Windows Defender Network Inspection Service?

**Comment by digital-spinner** [comment]
@bednar yes, disabling Windows Defender helps. Options to disable on the left side of screen.

![DEFENDER-OFF](https://user-images.githubusercontent.com/19900487/109626670-1b893680-7b41-11eb-9383-978e495f317c.png)

**Comment by bednar** [comment]
Currently, I don't how we can bypass this protection and scanning. Maybe you could create a custom rule for your Windows Defender.

**Comment by digital-spinner** [comment]
OK, thank you for your answer. I may report the bug to the Windows dev team then - IMO Windows Defender should not be working like this. Thank you for your support!

**Comment by bednar** [comment]
Thanks for your cooperation 👍
