### ISSUE TITLE
Allow setting a proxy for the client

### ISSUE THREAD

**Issue by bugybunny** [influxdata/influxdb-client-csharp#166]
__Proposal:__
Allow to pass a proxy that will be used with the underlying RestClient.

__Current behavior:__
There is no easy way to set a proxy.

__Desired behavior:__
Be able to pass a `System.Net.WebProxy` to either `InfluxDBClientFactory.Create/CreateV1` or `InfluxDBClientOptions` with the builder.

e.g.
```
var options = new InfluxDBClientOptions.Builder()
    .Url(InfluxDbUrl)
    .AuthenticateToken(_token.ToCharArray())
    .Proxy(new System.Net.Proxy("http://myproxy:8080"))
    .Build();
Client = InfluxDBClientFactory.Create(options);
 ```

I still use `CreateV1` because we cannot upgrade yet but I guess most users are one V2 and adding it to V1 is not so much needed.

__Alternatives considered:__
At the moment we set the proxy via reflection which works but is a bit ugly and unnecessary.

```
private static void SetProxy(InfluxDBClient influxDbClient, string proxyAddress)
{
    FieldInfo apiClientInfo = influxDbClient.GetType().GetField("_apiClient", BindingFlags.NonPublic | BindingFlags.Instance);
    object apiClient = apiClientInfo.GetValue(influxDbClient);
    PropertyInfo restClientInfo = apiClient.GetType().GetProperty("RestClient", BindingFlags.Public | BindingFlags.Instance);
    RestClient restClient = restClientInfo.GetValue(apiClient) as RestClient;
    restClient.Proxy = new WebProxy(proxyAddress)
    {
        UseDefaultCredentials = true,
    };
}
```
__Use case:__
Needed for corporate proxies.

**Comment by bednar** [comment]
@bugybunny, thanks for using our client, we will take a look.
