### ISSUE TITLE
[Question] How to query v1 (/query with InfluxQL)?

### ISSUE THREAD

**Issue by bugybunny** [influxdata/influxdb-client-csharp#170]
Is it possible with the client to query data via /query and thus use InfluxQL? Creating a V1 client and then `GetQueryApi().QueryAsync()` seems to call `/api/v2/query` where Flux is required. When passing `select * from <measurement>` I get an 
> type error 1:1-1:7: undefined identifier "select" at InfluxDB.Client.Core.Internal.AbstractQueryClient

so I deduce that it is not possible to use InfluxQL and I did not find another `Query` method in the docs or code. Or am I missing something?

I am using InfluxQL because to my understanding I cannot use Flux with v1.8.2 (stuck on Windows, so I cannot upgrade yet, Docker is no option) because I would need a bucket that I cannot create with v1.8.2 via CLI and also not via the API but that's another problem and I will contact the InfluxDB community and ask in the forum. So in the meantime I wanted to use InfluxQL; the query is really just a `select <field> from <measurement> where <tag>=<xxx>`, nothing fancy.

**Comment by bednar** [comment]
Hi @bugybunny,

thanks for using this client. The client doesn't supports InfluxQL. If you want to use `IFQL` please use a old client: [influxdb-csharp](https://github.com/influxdata/influxdb-csharp).

Regards

**Comment by bugybunny** [comment]
>If you want to use `IFQL` please use a old client: [influxdb-csharp](https://github.com/influxdata/influxdb-csharp).

I had a look at this before asking the question but the readme just shows examples on how to write data, there were 2 issues or so that asked for an API to query data and this open question, how one would query the data then https://github.com/influxdata/influxdb-csharp/issues/89 is is unanswered. So I guessed it is not possible with influxdb-csharp. 

I now implemented my own method with `HttpClient` and using the `/query` endpoint, deserialize the JSON and bringing it into my own model. Not so nice but works for now and hopefully can soon switch to Flux :)

Something along the lines of this with .NET Core and dependency injection for the client. Maybe it is some help for someone. Really shortened, everything joined together, not typesafe, considering only a select from one time series and so on ;-)

```csharp
public class Playground
{
	public class InfluxQueryResultEntity
	{
		public IReadOnlyCollection<InfluxQueryRecordEntity> Results { get; set; }
	}

	public class InfluxQueryRecordEntity
	{
		public long Statement_Id { get; set; }
		public IReadOnlyCollection<InfluxQuerySeriesEntity> Series { get; set; }
	}

	public class InfluxQuerySeriesEntity
	{
		public string Name { get; set; }
		public IReadOnlyCollection<string> Columns { get; set; }
		public IReadOnlyCollection<IReadOnlyCollection<string>> Values { get; set; }
	}

	public void ConfigureHttpClient(this IServiceCollection services)
	{
		services.AddHttpClient<ISomeInterface, Implementation>()
			.ConfigureHttpClient(client =>
			{
				client.BaseAddress = new Uri("url");
			})
			.ConfigureHttpMessageHandlerBuilder(builder =>
			{
				HttpClientHandler clientHandler = new HttpClientHandler();
				clientHandler.UseProxy = false;
				clientHandler.UseProxy = true;
				clientHandler.Proxy = new WebProxy("proxy", true) { UseDefaultCredentials = true };

				builder.PrimaryHandler = clientHandler;
			});
	}

	public void QueryInfluxDBWithQL(HttpClient httpClient, string query)
	{
		Dictionary<string, string> args = new Dictionary<string, string>();
		args.Add("db", "database");
		args.Add("p", "password");
		args.Add("u", "user");
		args.Add("q", query);
		string action = "query?" + string.Join("&", args.Select(item => $"{item.Key}={item.Value}"));
		HttpResponseMessage responseMessage = await httpClient.GetAsync(action, cancellationToken);
		string content = await responseMessage.Content.ReadAsStringAsync();

		InfluxQueryResultEntity result = JsonConvert.DeserializeObject<InfluxQueryResultEntity>(content);

		InfluxQueryResultEntity resultEntity = await timeSeriesRepository.GetAsync(query, cancellationToken);
		InfluxQuerySeriesEntity seriesEntity = resultEntity.Results.First().Series.First();
		foreach (IReadOnlyCollection<string> point in seriesEntity.Values)
		{
			// get the values and do something with them
		}
	}
}
```

**Comment by bednar** [comment]
>  So I guessed it is not possible with influxdb-csharp.

Sorry for wrong direction. I suppose that the old one is capable to do queries.

> I am using InfluxQL because to my understanding I cannot use Flux with v1.8.2.

The InfluxDB 1.8 supports Flux querying:
- https://docs.influxdata.com/influxdb/v1.8/about_the_project/releasenotes-changelog/#flux-v065-ready-for-production-use
- https://docs.influxdata.com/influxdb/v1.8/flux/installation/

You could use our `Legacy` client: 
- https://github.com/influxdata/influxdb-client-csharp/tree/master/Client.Legacy
- https://www.nuget.org/packages/InfluxDB.Client.Flux/

**Comment by bugybunny** [comment]
> The InfluxDB 1.8 supports Flux querying:

That I know. I also had already enabled Flux in the config file. However, as I wrote I cannot seem to create a bucket (even though the InfluxDB documentation says I should be able to). My problem is not that there is a lack of support for Flux with 1.8 but that I cannot create a bucket and Flux queries require a bucket. So for the moment I want to use InfluxQL explicitly because I seem to cannot use Flux because of missing buckets. But as I have said, I will ask this question in the InfluxDB community to not bug you and this issuetracker with it 😃 And my solution works for the moment and I hope I can soon create buckets.

Thank you!

**Comment by bednar** [comment]
>  My problem is not that there is a lack of support for Flux with 1.8 but that I cannot create a bucket and Flux queries require a bucket.

The bucket for queries is: 
> the database name and retention policy separated by a forward slash (/). For example: database/retention-policy.
- https://docs.influxdata.com/influxdb/v1.8/tools/api/#influxdb-20-api-compatibility-endpoints

Checkout this example: [InfluxDB18Example.cs](https://github.com/influxdata/influxdb-client-csharp/blob/63c760727d2283f98cd0f3888d5abfbca1358dbf/Examples/InfluxDB18Example.cs#L34)
