### ISSUE TITLE
Very slow performance for parallel query requests compared to curl

### ISSUE THREAD

**Issue by tributech-dhofer** [influxdata/influxdb-client-csharp#177]
In order to hit certain benchmarks i had to test up to 100 parallel requests querying the database and the result was shockingly slow.

__Setup:__
Requests are sent, directly via the client, to the InfluxDB instance, hosted in a docker container @localhost.
The InfluxDB has one org (variable: INFLUXDB_TEST_ORG), one bucket (variable: INFLUXDB_TEST_BUCKET) and contains 100 measurements with only a single value each.

The InfluxDB is configured with the following env-variables:
```
INFLUXD_QUERY_QUEUE_SIZE: "200"
INFLUXD_QUERY_CONCURRENCY: "200"
```

__Steps to reproduce:__
I am using a minimal example program that provides a list of all measurements to the function below.
```
async Task QueryInflux(string[] measurements)
{
    InfluxDBClient queryClient = InfluxDBClientFactory.Create("http://localhost:8086", "<username>", "<password>".ToCharArray());
    QueryApi queryApi = queryClient.GetQueryApi();
    var readTasks = new List<Task<List<FluxTable>>>();
    Stopwatch watch = new Stopwatch();
    watch.Start();
    foreach (string measurement in measurements)
    {
        string fluxQuery = $"from(bucket:\"{INFLUXDB_TEST_BUCKET}\") |> range(start: 2021-03-10T14:08:50.4316666Z, stop: 2021-03-30T14:10:50.4316701Z) |> filter(fn: (r) => r[\"_measurement\"] == \"{measurement }\") |> keep(columns: [\"_time\", \"_value\"]) |> sort(columns: [\"_time\"], desc: false) |> limit(n:100, offset:0)";
        readTasks.Add(queryApi.QueryAsync(fluxQuery, INFLUXDB_TEST_ORG));
    }
    await Task.WhenAll(readTasks);
    watch.Stop();
    TimeSpan duration = watch.Elapsed;
    Console.WriteLine($"Query duration: {duration}");
}
```
For comparison i am also using a bash script run from a WSL2 ubuntu command line:
```
curl -X POST localhost:8086/api/v2/query?org=<INFLUXDB_TEST_ORG> -sS -H 'Accept:application/csv' -H 'Content-type:application/vnd.flux' -H 'Authorization: Token <token>' -d 'from(bucket:"<INFLUXDB_TEST_BUCKET>") |> range(start: 2021-03-10T14:08:50.4316666Z, stop: 2021-03-30T14:10:50.4316701Z) |> filter(fn: (r) => r["_measurement"] == "measurement0") |> keep(columns: ["_time", "_value"]) |> sort(columns: ["_time"], desc: false) |> limit(n:100, offset:0)' &
curl -X POST localhost:8086/api/v2/query?org=<INFLUXDB_TEST_ORG> -sS -H 'Accept:application/csv' -H 'Content-type:application/vnd.flux' -H 'Authorization: Token <token>' -d 'from(bucket:"<INFLUXDB_TEST_BUCKET>") |> range(start: 2021-03-10T14:08:50.4316666Z, stop: 2021-03-30T14:10:50.4316701Z) |> filter(fn: (r) => r["_measurement"] == "measurement1") |> keep(columns: ["_time", "_value"]) |> sort(columns: ["_time"], desc: false) |> limit(n:100, offset:0)' &
# repeat for all measurements
wait
```

__Expected behavior:__
Similar query times between the query done with the client and the curl approach.

__Actual behavior:__
The curl queries finish in less than a second where the queries using the client take 1.5 MINUTES.

__Observations:__
- Creating a new client for each query improves the query time from e.g. 1.5 minutes to 6.6 seconds.
- Executing the requests in a serial manner is a lot faster, if the client is reused and barely changes the query time if a new client is created for each request.

__Specifications:__
 - Client Version: 1.16.0, also tried with 1.17.0-dev.linq.15
 - InfluxDB Version: 2.0.4
 - Platform: Windows 10 (client), Docker/Linux (database)

**Comment by bednar** [comment]
Hi @tributech-dhofer,

thanks for using our client. 

The querying by `curl` will be always faster because there isn't a transformation from HTTP response into C# objects.

> Creating a new client for each query improves the query time from e.g. 1.5 minutes to 6.6 seconds.
Executing the requests in a serial manner is a lot faster, if the client is reused and barely changes the query time if a new client is created for each request.

I will take a look where is a problem. The client should perform well if is reused in parallel threads.

Regards

**Comment by bednar** [comment]
@tributech-dhofer, Could you please check how the query performs when you use the `token` for authorization?

```csharp
InfluxDBClient queryClient = InfluxDBClientFactory.Create("http://localhost:8086", "<token>".ToCharArray());
```

**Comment by tributech-dhofer** [comment]
just tested it: execution time with token instead of username/password is the same.
also thanks for looking into this!
