### ISSUE TITLE
Parallel queries and writes result in too many connections

### ISSUE THREAD

**Issue by xljiulang** [influxdata/influxdb-client-csharp#189]
__Steps to reproduce:__
I was testing 1000 parallel queries and writes, and found that 1000*2 TCP connections were generated. After closing the test client, the state of these connections changed to TIME_WAIT, and the system needed to wait for a long time to release these connections.

If I had set the number of concurrency to 5000, it could easily throw clould not create a TCP connection exception . This exception does not occur on "Influxdb2.Client".

The core code is as follows, details of the project are available on [github](https://github.com/xljiulang/Influxdb2.Client/tree/master/Performances/influxdb-client-csharp)
```
var count = 1000;
var stopwatch = new Stopwatch();
stopwatch.Start();

var tasks = Enumerable.Range(0, count).Select(i => ReadWriteAsync());
await Task.WhenAll(tasks);
```

1. Start the InfluxDB-MockServer service
2. Start the influxdb-client-csharp.exe
3. Start cmd.exe and type `netstat -ano|find /i "5000" /c`
4. Close influxdb-client-csharp.exe
5. Start cmd.exe and type `netstat -ano|find /i "5000" /c`  or  `netstat -ano|find /i "5000" ` 

__Expected behavior:__
Close the TCP connection correctly.

__Actual behavior:__
Too many TIME_WAIT state TCP dead connections. 

__Specifications:__
 - Client Version:1.16.0
 - InfluxDB Version:2.x
 - Platform: win10x64

**Comment by bednar** [comment]
Hi @xljiulang,

thanks for using our client. 

Can you please test your benchmark with `v1.17.0`? There was a fix for query perf - https://github.com/influxdata/influxdb-client-csharp/pull/181

Regards

**Comment by xljiulang** [comment]
@bednar 
In v1.17.0, this problem still applies, I opened and closed the influxdb-client-csharp.exe 5 times, and the number of TCP connections in TIME_WAIT reached 1W. You can check out my code and test it against `Influxdb2.Client`

**Comment by xljiulang** [comment]
1W means 10K, in China

**Comment by bednar** [comment]
@xljiulang thanks for your cooperation. 

We had similar issue with RAM consumption caused by Windows Defender - https://github.com/influxdata/influxdb-client-csharp/issues/164#issuecomment-788758210. Can you please check that the issue is still here after disabling Windows Defender?

**Comment by bednar** [comment]
This PR has been closed because it has not had recent activity. Please reopen if this PR is still important to you and you want to continue with them.
