### ISSUE TITLE
client.GetUsersApi().FindUsersAsync() only returns 20 users

### ISSUE THREAD

**Issue by hankbeasley** [influxdata/influxdb-client-csharp#190]
There is no way to get all users from the system.

**Comment by bednar** [comment]
@hankbeasley, thanks for using our client, We will take a look.

**Comment by bednar** [comment]
Hi @hankbeasley,

The InfluxDB currently doesn't supports pagination for an Users API. See API docs - https://docs.influxdata.com/influxdb/v2.0/api/#operation/GetUsers. I've contact dev team of InfluxDB about this lack of feature.

Regards.

**Comment by stmax82** [comment]
I just ran into the same problem. FindUsersAsync() only returns max 17 users for me even if more exist.

**Comment by bednar** [comment]
@stmax82, @hankbeasley we are waiting to approve of PR, please leave comment at https://github.com/influxdata/influxdb/pull/21367... it will help to InfluxDB OSS maintainer for prioritise our issue
