### ISSUE TITLE
System.MissingMethodException: Method not found:

### ISSUE THREAD

**Issue by MadMowgli** [influxdata/influxdb-client-csharp#195]
# Error log

```javascript
[2021-05-03T15:21:23.799Z] Error: System.MissingMethodException: Method not found: 'Void CsvHelper.CsvReader..ctor(System.IO.TextReader, System.Globalization.CultureInfo)'.
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.<>c.<.cctor>b__22_1(Exception e)
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.Query(RestRequest query, Action`2 consumer, Action`1 onError, Action onComplete)
   at InfluxDB.Client.QueryApi.QueryAsync(Query query, String org)
   at <private>
   at <private>
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

# Causing call
```csharp
public async Task<List<FluxTable>> testQueryingProcess(int rangeInDays)
{
    // Creating a new client
    var influxClient = InfluxDBClientFactory.CreateV1(
        influxUrl, influxUsername, influxPassword, influxTestDatabase, influxTestRetentionPolicy);

    // Query data
    var query = $"from(bucket: \"{influxTestDatabase}/{influxTestRetentionPolicy}\") |> range(start: -{rangeInDays}d)";
    var fluxRecords = await influxClient.GetQueryApi().QueryAsync(query);

    return fluxRecords;
}
```

# Project specifics
```xml
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="26.0.1" />
    <PackageReference Include="InfluxDB.Client" Version="1.17.0" />
    <PackageReference Include="InfluxDB.Client.Core" Version="1.17.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.2.0-preview3.20168.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>
```

# Already tried
* Uninstalling the CsvHelper NuGet-package
* Uninstalling the InfluxDB.Client.Core-package
* Rebuilding the whole solution
* Cleaning the solution

# Further Information
* InfluxDB Version: 1.8.1, no authification enabled
* Integrating the C#-Client into a blazor-environment
* Trying to follow [this](https://github.com/influxdata/influxdb-client-csharp/blob/master/Examples/InfluxDB18Example.cs) example
* Writing to the database works flawlessly - the error only occurs while querying

Can't make any sense out of this error - let me know if you need any further information!

**Comment by bednar** [comment]
Hi @MadMowgli,

thanks for using our client. 

There is a conflict between your CsvHelper version and version from client: https://github.com/influxdata/influxdb-client-csharp/blob/cf65a1ccb9ddd307947e2ccc0145cbd6c8ecdfc9/Client.Core/Client.Core.csproj#L35

As a workaround you can change your CsvHelper version to `v18.0.0`.

Regards

**Comment by MadMowgli** [comment]
Hi @bednar 

Can't believe this fixed it, lol. Thought i'd triple-checked that. 
However - works just fine now! Appreciate the support.

Regards

**Comment by ftkus** [comment]
Hi @bednar,

I have a similar issue. I was running v27.0.0 of CsvHelper, and downgraded to v18.0.0 as per this help thread. However, now I am getting the following exception:

`Could not load file or assembly 'CsvHelper, Version=27.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

At:

`   at InfluxDB.Client.Core.Flux.Internal.FluxCsvParser.ParseFluxResponse(Stream source, ICancellable cancellable, IFluxResponseConsumer consumer)
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.<>c__DisplayClass6_0.<Query>g__Consumer|0(ICancellable cancellable, Stream bufferedStream)`

**Comment by bednar** [comment]
Hi @ftkus,

try to clean your solution by: `dotnet clean` or check that the `CsvHelper v27.0.0` is not transitive dependency by: `dotnet list package --verbosity detailed`.

Regards
