### ISSUE TITLE
Update query to not use sort when not needed

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/influxdb-client-csharp#196]
If there is only one measurement in a dataset, then a call to `sort` after a call to `from |> range |> filter |> pivot |> drop` is generally not necessary since the data will be returned in time sorted order from the optimzed pivot call. These queries can have sort removed as long as their data will have a single measurement: 

https://github.com/influxdata/influxdb-client-csharp/blob/95d63447cfb49f6ffc33d78f44a6f7893298738d/Client.Linq/README.md#perform-query (under Flux Query)

https://github.com/influxdata/influxdb-client-csharp/blob/95d63447cfb49f6ffc33d78f44a6f7893298738d/Client.Linq/README.md#orderby (Example 2, under Flux Query)

**Comment by bednar** [comment]
@fchikwekwe, What about `group` function? Should be removed too? The documentation says: _group() does not guarantee the sort order of output records._

Current query:
```
from(bucket: "my-bucket") 
    |> range(start: 2019-11-16T08:20:15Z, stop: 2021-01-10T05:10:00Z) 
    |> filter(fn: (r) => (r["sensor_id"] == "id-1")) 
    |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
    |> drop(columns: ["_start", "_stop", "_measurement"])
    |> group()
    |> sort(columns: ["_time"], desc: false) 
    |> limit(n: 60001)
```

Optimized:
```
from(bucket: "my-bucket") 
    |> range(start: 2019-11-16T08:20:15Z, stop: 2021-01-10T05:10:00Z) 
    |> filter(fn: (r) => (r["sensor_id"] == "id-1")) 
    |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
    |> drop(columns: ["_start", "_stop", "_measurement"])
    |> group()
    |> limit(n: 60001)
```
Is this correct?

**Comment by bednar** [comment]
Summary of solution:

- driver assumes that user querying one time series
- remove `|> group() |> sort(columns: ["_time"], desc: false)` for default configuration 
- user can configure driver to use `group()` function for querying multiple time series
