### ISSUE TITLE
Update CsvHelper dependency to >= 21.3.0

### ISSUE THREAD

**Issue by malessainray** [influxdata/influxdb-client-csharp#208]
__Proposal:__
Update the CsvHelper dependency to at least 21.3.0

__Current behavior:__
Currently version 18.0.0 is used which is not compatible to 21.3.0

__Desired behavior:__
I would like the InfluxDB.Client package to be compatible to the CsvHelper version 21.3.0.

__Alternatives considered:__
I would have to work with different assembly loading contexts which has the potential to get messy

__Use case:__
Currently I'm unable to use the InfluxDB.Client Nuget package in a release of our product as it would break by the CsvHelper 21.3.0 deployment which our product requires for other components.

**Comment by bednar** [comment]
Hi @malessainray,

I've prepare the PR https://github.com/influxdata/influxdb-client-csharp/pull/209 with fix, stay tuned.

Regards
