### ISSUE TITLE
Writing a batch of measurements by LineProtocol

### ISSUE THREAD

**Issue by abrasat** [influxdata/influxdb-client-csharp#214]
Is there any code sample available about how to write a batch of measurements (for instance 1000), by using the LineProtocol?
Thanks.

**Comment by bednar** [comment]
Hi @abrasat,

you can use something like:

```csharp
var client = InfluxDBClientFactory.Create("http://localhost:8086", "my-token".ToCharArray());

await client.GetWriteApiAsync().WriteRecordsAsync("my-bucket", "my-org", WritePrecision.Ns, my_list_of_line_protocols);

client.Dispose();
```

Regards

**Comment by abrasat** [comment]
Thanks for the reply. How does a list of line_protocols exactly look like? A list of PointData objects?

**Comment by bednar** [comment]
If you would like to use Line Protocol as a source of your data then use:

```var my_list_of_line_protocols = new[]{"h2o,tag=a value=1", "cpu,tag=b value=99.5"};```

For `PointData` use something like:

```csharp
var points = new List<PointData>
{
    PointData.Measurement("h2o").Tag("location", "coyote_creek").Field("water_level", 9.0D)
        .Timestamp(9L, WritePrecision.S),
    PointData.Measurement("h2o").Tag("location", "coyote_creek").Field("water_level", 10.0D)
        .Timestamp(10L, WritePrecision.S)
};
await writeApi.WritePointsAsync("my-bucket", "my-org", points);
```

**Comment by abrasat** [comment]
Ok, thx. Are "WriteRecordsAsync()" and "WritePointsAsync()" basically equivalent regarding the write peformance?

**Comment by bednar** [comment]
> Ok, thx. Are "WriteRecordsAsync()" and "WritePointsAsync()" basically equivalent regarding the write peformance?

There is only one difference... the `WritePointsAsync()` has to serialize the `PointData` into Line Protocol.

**Comment by abrasat** [comment]
Thx for the clarification. I suppose the serialization is fast compared to the influxdb access.
Some more questions: which is the syntax to explicitly set the timestamp value when writing a measurement over the line protocol and how can be written several tags (each with its own value) simultaneously?

**Comment by bednar** [comment]
> Some more questions: which is the syntax to explicitly set the timestamp value when writing a measurement over the line protocol 

It should be Unix timestamp - https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/#unix-timestamp

> how can be written several tags (each with its own value) simultaneously?

```csharp
var point = PointData.Measurement("h2o")
    .Tag("tag1", "value1")
    .Tag("tag2", "value2")
    .Field("level", 2);
```

**Comment by abrasat** [comment]
Thanky you. And when using WriteRecordsAsync ?
How would your example look like, with a timestamp and several tags with measurements for that timestamp?
```
var my_list_of_line_protocols = new[]{"h2o,tag=a value=1", "cpu,tag=b value=99.5"};
```

**Comment by bednar** [comment]
```
var my_list_of_line_protocols = new[]{"h2o,tag=a,tag2=b value=1 1626077482000000000", "cpu,tag=b,tag2=c value=99.5 1626077482000000000"};
```

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
