### ISSUE TITLE
Set retention policy for database

### ISSUE THREAD

**Issue by abrasat** [influxdata/influxdb-client-csharp#215]
How can be set programmatically the retention policy for a database at creation?
Can the retention policy be modfied later programmatically for an existing database?

**Comment by bednar** [comment]
Hi @abrasat,

you can use `BucketsApi`:

- Create `Bucket` with requested retention policy: [CreateBucketAsync](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.BucketsApi.html#InfluxDB_Client_BucketsApi_CreateBucketAsync_InfluxDB_Client_Api_Domain_Bucket_)
- Update `Bucket` with new retention policy: [UpdateBucketAsync](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.BucketsApi.html#InfluxDB_Client_BucketsApi_UpdateBucketAsync_InfluxDB_Client_Api_Domain_Bucket_)

Regards

**Comment by abrasat** [comment]
To update just the retention policy, do all other bucket properties (Id, OrgID, Links,...) have also to be set again?
Usually when creating a bucket with a call to  OnboardingRequest() only the "retentionPeriodSeconds" has to be set (the "shardGroupDurationSeconds" is set automatically). When using "UpdateBucketAsync" is it mandatory to set both "everySeconds" and "shardGroupDurationSeconds" properties from the "BucketRetentionRules" class?

**Comment by bednar** [comment]
You have to set: `id`, `name`,  `description`, and `retentionRules`

**Comment by abrasat** [comment]
Ok, thx. With Id you mean the bucket Id, or the OrgID for the organization owning the bucket?
Would putting a different name than the initial name then rename the bucket?
I think implementing a dedicated API "UpdateRetentionPolicyForBucketAsync(string bucketName, long retentionPeriodSeconds, long?shardGroupDurationSeconds=null)", where only the RetentionRules are set, would be a better option in some future release of the library...

**Comment by abrasat** [comment]
It is more or less just an additional wrapper around the existing code, something like this:
```
public Task<Bucket> UpdateRetentionPolicyForBucketAsync(string bucketName, long retentionPeriodSeconds, long?shardGroupDurationSeconds=null)
{
    var bucket = await FindBucketByNameAsync(bucketName).ConfigureAwait(false);

    var bucketNewRetentionRulesList = new List<BucketRetentionRules> { new BucketRetentionRules(BucketRetentionRules.TypeEnum.Expire, retentionPeriodSeconds, shardGroupDurationSeconds) };

    var retentionRules = bucketNewRetentionRulesList.Select(rules =>
    {
        Enum.TryParse(rules.Type.ToString(), true, out PatchRetentionRule.TypeEnum type);
        return new PatchRetentionRule(type, rules.EverySeconds, rules.ShardGroupDurationSeconds);
    }).ToList();
            
    var request = new PatchBucketRequest(bucket.Name, bucket.Description, retentionRules);
    return _service.PatchBucketsIDAsync(bucket.Id, request);
}
```

**Comment by abrasat** [comment]
Any plans to add a function that updates just the retention policy in a new library release?

**Comment by bednar** [comment]
Currently, we don't have ETA, but every Pull Request is welcome. Is this something you might be willing to help with?

**Comment by bednar** [comment]
@abrasat please feel free to create PR with your requested functionally. Currently we don't have a plan to add that function by ourselves.
