### ISSUE TITLE
Writing to different buckets with a single WriteApi silently discards records

### ISSUE THREAD

**Issue by mibos-kremer** [influxdata/influxdb-client-csharp#216]
Writing to different buckets within a very short timespan with the WriteApi seems to silently discard records. The failed records do not produce any success or error events in the event handler.

__Steps to reproduce:__
Tested it with the following snippet:

        InfluxDBClient influxDbClient = InfluxDBClientFactory.Create(url, token);
        WriteApi writeApi = influxDbClient.GetWriteApi();
        writeApi.EventHandler += HandleWriteApiEvent;
        
        bool val = false;
        while (true) {
            long timestamp = DateTimeOffset.Now.ToUnixTimeSeconds();
            for (int i = 0; i < 8; i++) {
                PointData point = PointData.Measurement($"test.{i}")
                    .Field("value", val ? 1 : 2)
                    .Timestamp(timestamp, WritePrecision.S);
                writeApi.WritePoint(i % 2 == 1 ? "Database1" : "Database2", "main", point);
            }
            val = !val;
            Thread.Sleep(1000);
        }

__Expected behavior:__
Expected all data to be written to the InfluxDB, or to receive an error if writing to different buckets is not allowed.

__Actual behavior:__
Some of the records are discarded, no errors are received by the event handler.

__Specifications:__
 - Client Version: 1.19.0
 - InfluxDB Version:
 - Platform: Debian and Windows 10

**Comment by bednar** [comment]
Hi @mibos-kremer,

thanks for using our client and sorry for late.

The [WriteApi](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.WriteApi.html) is suppose to run as a long live singleton, because it uses background thread for batching and ingesting data into InfluxDB. It should be closed by `using` pattern.

For your purpose is better to use [WriteApiAsync](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.WriteApiAsync.html). 

You can use something like:

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;
using InfluxDB.Client;
using InfluxDB.Client.Api.Domain;
using InfluxDB.Client.Writes;

namespace Examples
{
    public static class InfluxDBExample
    {
        public static async Task Main(string[] args)
        {
            const string url = "http://localhost:9999";
            const string token = "my-token";
            const string org = "my-org";
            const string bucket = "my-bucket";
            using var client = InfluxDBClientFactory.Create(url, token.ToCharArray());

            var val = false;
            while (true)
            {
                var timestamp = DateTimeOffset.Now.ToUnixTimeSeconds();
                for (var i = 0; i < 8; i++)
                {
                    var point = PointData.Measurement($"test.{i}")
                        .Field("value", val ? 1 : 2)
                        .Timestamp(timestamp, WritePrecision.S);
                    await client.GetWriteApiAsync().WritePointAsync(i % 2 == 1 ? "Database1" : "Database2", org, point);
                }

                val = !val;
                Thread.Sleep(1000);
            }
        }
    }
}
```

Regards

**Comment by bednar** [comment]
Duplicated by #115
