### ISSUE TITLE
Unauthorized Access Exception

### ISSUE THREAD

**Issue by abrasat** [influxdata/influxdb-client-csharp#217]
When trying to execute the "ManagementExample" or the "PlatformExample" an "Unauthorized Access" exception is thrown.
Is there anything that has to be done before executing these samples?

**Comment by bednar** [comment]
You have to specify valid token and url of InfluxDB.

**Comment by abrasat** [comment]
Thx. Yes it works if I first setup the influxdb from the commandline (set user, password, token)
```
influx setup --username myUser --password myPw --token myToken --org myOrg --bucket myBucket --retention 86400s
```
and then use the library:
```
var uri = "http://localhost:8086";
var Token = "myToken".ToCharArray();
var influxDB = InfluxDBClientFactory.Create(uri, Token);
```
But is it possible to perform the influxdb setup also programatically, using the influxdb-client-csharp library? I mean to set user, password, token, organization, bucket

**Comment by bednar** [comment]
> But is it possible to perform the influxdb setup also programatically, using the influxdb-client-csharp library? I mean to set user, password, token, organization, bucket

Yes. see following method: [OnboardingAsync(OnboardingRequest)](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.InfluxDBClient.html#InfluxDB_Client_InfluxDBClient_OnboardingAsync_InfluxDB_Client_Api_Domain_OnboardingRequest_)

**Comment by abrasat** [comment]
Thx, it looks good, I will take a look. 
How exactly should the InfluxDBClient be created using the InfluxDBClientFactory from the library, to be able to call the OnboardingAsync method?
If you have any working example it would be great...

**Comment by bednar** [comment]
> Thx, it looks good, I will take a look.
> How exactly should the InfluxDBClient be created using the InfluxDBClientFactory from the library, to be able to call the OnboardingAsync method?

```csharp
await InfluxDBClientFactory.Onboarding(url, ...);
```

**Comment by abrasat** [comment]
Thx. The function above throws the exception "onboarding has been completed". How can the onboarding status be programmatically checked? Can onboarding be performed only once per user or once per user+organization? Or only once at all for influxdb?

If the OnboardResponse would have been ok, how would the InfluxDBClient instance be created from it?

**Comment by bednar** [comment]
> Thx. The function above throws the exception "onboarding has been completed". How can the onboarding status be programmatically checked? 

```csharp
var client = InfluxDBClientFactory.Create("http://localhost:9999", "xyz");
var isOnboardingAllowed = await client.IsOnboardingAllowedAsync();
```

> Can onboarding be performed only once per user or once per user+organization? Or only once at all for influxdb?

once at all for InfluxDB

> If the OnboardResponse would have been ok, how would the InfluxDBClient instance be created from it?

```csharp
var client = InfluxDBClientFactory.Create("http://localhost:9999", "my-token");
```

**Comment by abrasat** [comment]
>
> ```cs
> var client = InfluxDBClientFactory.Create("http://localhost:9999", "xyz");
> var isOnboardingAllowed = await client.IsOnboardingAllowedAsync();
> ```
Not sure to understand.... The Create() call above will throw an "Unauthorized Access Exception" if the token "xyz" is not valid (this would be the case if onboarding has never been performed).

**Comment by bednar** [comment]
> Not sure to understand.... The Create() call above will throw an "Unauthorized Access Exception" if the token "xyz" is not valid (this would be the case if onboarding has never been performed).


Something like this:

```csharp
const string url = "http://localhost:8086";
const string token = "my-token";

var client = InfluxDBClientFactory.Create(url, token);
var onboardingAllowed = await client.IsOnboardingAllowedAsync();
if (onboardingAllowed)
{
    //
    // OnBoarding
    //
    var request = new OnboardingRequest(
        username: "my-username",
        org: "my-org",
        bucket: "my-bucket",
        token: token);
    var response = await InfluxDBClientFactory.Onboarding(url, request);
    
    Trace.WriteLine($"Onboarding response: {response}");
    
    client = InfluxDBClientFactory.Create(url, token);
}

...
```

**Comment by abrasat** [comment]
Thanks for the sample, it is clear now

**Comment by bednar** [comment]
> Thanks for the sample, it is clear now.
> Is there any need to dispose explicitly the created client instances?

Yes ... `client.dispose()`

> How can be programatically detected the loss of the connection to the influxdb database, respectively when influxdb is stopped?

You can periodically check the result of `Health()` method:

```csharp
var health = await Client.HealthAsync();
if (health.Status == HealthCheck.StatusEnum.Fail)
{
    // something is wrong
}
```

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
