### ISSUE TITLE
Question: Migration path from MetricsCollector to WriteApi

### ISSUE THREAD

**Issue by nvivo** [influxdata/influxdb-client-csharp#218]
I have used the previous library for 1.x using the MetricsCollector, which has a nice feature of having a default NullCollector, so I could check if influx should be enabled or not, and skip the MetricsCollector setup to disable it completely.

I'm migrating to Influx 2, and I'm trying to figure out the migration path with this library. What is the right way to achieve the same thing?

Should I implement my own wrapper around WriteApi to make this decision, or does the current client it have some NO-OP feature I'm missing?

**Comment by bednar** [comment]
Hi @nvivo,

thanks for using our client. I apologize for the late response.

> Should I implement my own wrapper around WriteApi to make this decision, or does the current client it have some NO-OP feature I'm missing?

The current client doesn't have NO-OP feature, but every PR is welcome.

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
