### ISSUE TITLE
Get data schema information 

### ISSUE THREAD

**Issue by abrasat** [influxdata/influxdb-client-csharp#219]
Are these functions mapped in the implemenation of the c# influxdb client library (list of field keys, tag keys, measurements in a bucket) ?

[https://docs.influxdata.com/influxdb/cloud/query-data/flux/explore-schema/](https://docs.influxdata.com/influxdb/cloud/query-data/flux/explore-schema/)

If yes, where could I find some usage samples?

**Comment by bednar** [comment]
> Are these functions mapped in the implemenation of the c# influxdb client library (list of field keys, tag keys, measurements in a bucket) ?
> 

No, You have to use `QueryApi`, something like:

```csharp
using System;
using System.Threading.Tasks;
using InfluxDB.Client;

namespace Examples
{
    public static class PlatformExample
    {
        public static async Task Main(string[] args)
        {
            var url = "http://localhost:9999";
            var token = "my-token";
            var org = "my-org";
            var bucket = "my-bucket";
            
            using var client = InfluxDBClientFactory.Create(url, token.ToCharArray());

            //
            // Query
            //
            string query = $@"import ""influxdata/influxdb/schema""

            schema.measurements(bucket: ""{bucket}"")";
            
            var fluxTables = await client.GetQueryApi().QueryAsync(query, org);
            fluxTables.ForEach(fluxTable =>
            {
                var fluxRecords = fluxTable.Records;
                fluxRecords.ForEach(fluxRecord =>
                {
                    Console.WriteLine($"{fluxRecord.GetValue()}");
                });
            });
        }
    }
}
```

**Comment by abrasat** [comment]
Thx, it worked!

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
