### ISSUE TITLE
Question: IAsyncEnumerable<T> query usage sample

### ISSUE THREAD

**Issue by abrasat** [influxdata/influxdb-client-csharp#220]
Can you please provide some usage sample for the influxDB.GetQueryApi().QueryAsyncEnumerable... method, for the execution flux queries?
How would the QueryAsync() sample provided in the repository (see below) be adapted if using QueryAsyncEnumerable?

```
//
// Query data
//
var flux = "from(bucket:\"temperature-sensors\") |> range(start: 0)";

var fluxTables = await influxDBClient.GetQueryApi().QueryAsync(flux, "org_id");
fluxTables.ForEach(fluxTable =>
{
    var fluxRecords = fluxTable.Records;
    fluxRecords.ForEach(fluxRecord =>
    {
        Console.WriteLine($"{fluxRecord.GetTime()}: {fluxRecord.GetValue()}");
    });
});
```

**Comment by bednar** [comment]
Hi @abrasat,

The `QueryAsyncEnumerable` maps response to enumerable of objects of specified type. You can use something like:

```csharp
[Measurement("temperature")]
private class Temperature
{
    [Column("location", IsTag = true)] public string Location { get; set; }

    [Column("value")] public double Value { get; set; }

    [Column(IsTimestamp = true)] public DateTime Time { get; set; }
    
    public override string ToString()
    {
        return $"{Time:MM/dd/yyyy hh:mm:ss.fff tt} {Location} value: {Value}";
    }
}
```

``` csharp
const string flux = "from(bucket:\"temperature-sensors\") |> range(start: 0)";
await foreach (var temperature in influxDB.GetQueryApi().QueryAsyncEnumerable<Temperature>(flux, "org_id" CancellationToken.None))
{
    Console.WriteLine($"Temperature: {temperature}");
}
``` 


Regards

**Comment by abrasat** [comment]
Ok, thx.
Is this the preferred/recommended way to perform influxdb queries, especially if large amounts of data are returned by the query?
As far as I understand the AsyncEnumerable does not block the calling application until all data are fetched from influxdb, is that correct?

**Comment by bednar** [comment]
> Ok, thx.
> Is this the preferred/recommended way to perform influxdb queries, especially if large amounts of data are returned by the query?

There is no preferred way. You have to measure what is best for you.

> As far as I understand the AsyncEnumerable does not block the calling application until all data are fetched from influxdb, is that correct?

Yes.

**Comment by abrasat** [comment]
> There is no preferred way. You have to measure what is best for you.

That was actually the question... Which is the fastest way to access large amounts of data from influxdb, without blocking the application calling query function from the library.

**Comment by bednar** [comment]
> > There is no preferred way. You have to measure what is best for you.
> 
> That was actually the question... Which is the fastest way to access large amounts of data from influxdb, without blocking the application calling query function from the library.

The best option for your requirements is `IAsyncEnumerable<T>` and also optimize your `FluxQuery`  -https://docs.influxdata.com/influxdb/cloud/query-data/optimize-queries/

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
