### ISSUE TITLE
Write several measurements with same timestamp

### ISSUE THREAD

**Issue by abrasat** [influxdata/influxdb-client-csharp#223]
I have problems writing batches of points (with WritePointsAsync()), if some points have the same timestamp and the same tag (the data to be written is coming from an external system, where tagging several messages with same time-stamp is possible). The data have distinct field content in the measurement, but that seems not to be sufficient. The "written" entries are missing in influxdb, when trying to query them later.
Is it possible when calling WritePointsAsync() to get the information how many new points have been written to influxdb ?

**Comment by bednar** [comment]
> Is it possible when calling WritePointsAsync() to get the information how many new points have been written to influxdb ?

No, the InfluxDB doesn't supports this feature.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
