### ISSUE TITLE
Count measurement items in a time range

### ISSUE THREAD

**Issue by abrasat** [influxdata/influxdb-client-csharp#226]
My application stores measurements into the influxdb database, each with a distinct timestamp. Is there any method available to calculate the number of measurement items stored in a certain time range?
Does the library contain any methods that would help implementing a paging functionality for the stored measurements?

**Comment by bednar** [comment]
> My application stores measurements into the influxdb database, each with a distinct timestamp. Is there any method available to calculate the number of measurement items stored in a certain time range?

You have to use the `Flux` to calculate this. There is a #Flux channel in our Slack - https://influxcommunity.slack.com/archives/CH8RGRW4T

> Does the library contain any methods that would help implementing a paging functionality for the stored measurements?

No, you have to use [limit() function](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/built-in/transformations/limit/) for pagination.

**Comment by abrasat** [comment]
Thanks. I found the count() function, but not sure how to use it optimally with the QueryApi from the library.
This would be the flux query:
```
from(bucket: "myBucket")
  |> range(start: 0)
  |> count()
```
But the QueryAsync() method returns always a list of flux tables. 
```
var fluxTables = await influxDB.GetQueryApi().QueryAsync(fluxQryCount, orgName);
```
Do I have to iterate the flux tables and then the records  to get the count value? Or is there any possibility to get directly the result of the count()?

**Comment by bednar** [comment]
> Do I have to iterate the flux tables and then the records to get the count value?

Yes

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
