### ISSUE TITLE
CancellationToken support in QueryApi

### ISSUE THREAD

**Issue by corentinaltepe** [influxdata/influxdb-client-csharp#228]
Hello. This is a request quite similar to #173 (#179).

I noticed that the `QueryAsync()` calls do not make use of the `CancellationToken` to cancel queries. Would it be something possible to add or are there limitations with how InfluxDB works?

I notice there are `ICancellable` in most queries, and the `CancellationToken` for the methods returning `IAsyncEnumerable<T>`. But my understanding is they offer cancelling the fetching/parsing of Influx's response to the query. I would be interested in cancelling the query itself before any result can be read. Is it possible?

Edit: looking into the source code. I believe we'd have to add the `cancellationToken` into `AbstractQueryClient` at lines [116](https://github.com/influxdata/influxdb-client-csharp/blob/master/Client.Core/Internal/AbstractQueryClient.cs#L116) and [155](https://github.com/influxdata/influxdb-client-csharp/blob/master/Client.Core/Internal/AbstractQueryClient.cs#L155). Then work our way up to the `QueryApi` (two classes impacted).

Also, the source code reveals that the `CancellationToken` for the methods returning `IAsyncEnumerable<T>` does [allow cancelling the queries](https://github.com/influxdata/influxdb-client-csharp/blob/8ae7ac33aa04af96c6898c3459212d45c8ff5f04/Client.Core/Internal/AbstractQueryClient.cs#L178). So I could start using them, although I'd be more interested in using the method returning `List<FluxTable>`.

**Comment by bednar** [comment]
Hi @corentinaltepe,

thanks for using our client.

> Hello. This is a request quite similar to #173 (#179).
> 
> I noticed that the `QueryAsync()` calls do not make use of the `CancellationToken` to cancel queries. Would it be something possible to add or are there limitations with how InfluxDB works?

> I notice there are `ICancellable` in most queries, and the `CancellationToken` for the methods returning `IAsyncEnumerable<T>`. But my understanding is they offer cancelling the fetching/parsing of Influx's response to the query. I would be interested in cancelling the query itself before any result can be read. Is it possible?
> 
> Edit: looking into the source code. I believe we'd have to add the `cancellationToken` into `AbstractQueryClient` at lines [116](https://github.com/influxdata/influxdb-client-csharp/blob/master/Client.Core/Internal/AbstractQueryClient.cs#L116) and [155](https://github.com/influxdata/influxdb-client-csharp/blob/master/Client.Core/Internal/AbstractQueryClient.cs#L155). Then work our way up to the `QueryApi` (two classes impacted).

You are right, the `QueryAsync()` should use `CancellationToken` instead of `ICancellable`. 

Thanks for this suggestion 👍. Is this something you might be willing to help with?

Regards

**Comment by corentinaltepe** [comment]
I will not be able to contribute to the enhancement.

It is unclear whether OSS contributions would go against company policy. I'm choosing to stay on the safe side. Sorry about this.

**Comment by bednar** [comment]
@corentinaltepe It's ok, I will take a look

**Comment by bednar** [comment]
Hi @corentinaltepe, 

We are preparing a new major version of the client (`v4.0.0`) which added supports for `CancellationToken` in `QueryApi`. Please try the preview version by `dotnet add package InfluxDB.Client --version 4.0.0-dev.5091`. 

Any feedback will be appreciated 👂.

Regards

**Comment by bednar** [comment]
Thank you and very much appreciated

**Comment by bednar** [comment]
@corentinaltepe, the issue is fixed in new major update of the client - [`v4.0.0`](https://github.com/influxdata/influxdb-client-csharp/milestone/29) - which contains a few breaking changes. The most important change is in underlaying HTTP client - switch from legacy `HttpWebRequest` class, and uses `HttpClient` instead.

Please try a preview version by `dotnet add package InfluxDB.Client --version 4.0.0-dev.5280`. 

Any feedback will be appreciated 👂. For more info about new major version see [CHANGELOG.md](https://github.com/influxdata/influxdb-client-csharp/blob/master/CHANGELOG.md#400-unreleased).

**Comment by corentinaltepe** [comment]
Hello @bednar,

Thank you very much for the preview versions of v4. Please let me know if this is not the right place to give you general feedback, I can post this somewhere else. 

## Build Breaking Changes
I have upgraded my project with `4.0.0-dev.5333`. I had to edit many of the calls to methods of the different APIs, but nothing that's not already documented in the [changelog](https://github.com/influxdata/influxdb-client-csharp/blob/master/CHANGELOG.md).

- Re-ordering of the parameters in the methods is welcome. They make a lot more sense as they are now. I truly appreciate the systematic use of `CancellationToken` in all `async` methods.
- Here's one little trick that could be helpful for the less experienced C# developers, which could be added in an upgrade guide for v3 to v4. Some methods add new parameters with default value `null`. Instead of doing:
```diff
- _client.GetQueryApi().QueryAsyncEnumerable<T>(fluxQuery, token);
+ _client.GetQueryApi().QueryAsyncEnumerable<T>(fluxQuery, null, token);
```
we can do the following, which is more elegant in my opinion:
```diff
- _client.GetQueryApi().QueryAsyncEnumerable<T>(fluxQuery, token);
+ _client.GetQueryApi().QueryAsyncEnumerable<T>(fluxQuery, cancellationToken: token);
```

## Runtime Breaking Changes
After I fixed build issues, I still had failing unit tests. Runtime errors are a lot more difficult to detect and may be dangerous to most people upgrading their projects.

It appears there was a change of behavior in `TaskApi.FindTasksByOrganizationIdAsync(string orgId)`. As I understand it, in v3 `orgId` is actually the organisation **name** and not its ID. Fixing the behavior is welcome, but should be signaled when upgrading because definitely a breaking change.
Maybe add a method `taskApi.FindTasksByOrganizationNameAsync(string orgName)` to keep the behavior consistent? (but then that'd clutter the API).

```cs
var taskApi = client.GetTasksApi();
var tasks = await taskApi.FindTasksByOrganizationIdAsync("myorg").ConfigureAwait(false);

// throws: InfluxDB.Client.Core.Exceptions.BadRequestException : failed to decode request: id must have a length of 16 bytes
```


Similar issue with `QueryApi.QueryAsync(string query, string org = null)`. I think `org` used to represent the organisation's name and now it is likely to be the organisation id. My issue here is the method has no `///<summary/>` comment documentation, and the parameter name doesn't explicit whether it should be the org's name or id. So it was trial and error in v3, and it is again in v4.

```
InfluxDB.Client.Core.Exceptions.BadRequestException : failed to decode request: id must have a length of 16 bytes
```

Most of my test suite stops here. I haven't had the time yet to resolve that issue. If I manage to work around this and discover other things, I'll keep you informed.

Thank you again!

**Comment by bednar** [comment]
Hi @corentinaltepe,

Thanks for your feedback. We very much appreciate your effort and it is very important and beneficial for us.

> I truly appreciate the systematic use of `CancellationToken` in all `async` methods.

We will continue with adding `CancellationToken` to other APIs such as `BucketsApi`, `TasksApi`, ...

> It appears there was a change of behavior in `TaskApi.FindTasksByOrganizationIdAsync(string orgId)`. As I understand it, in v3 `orgId` is actually the organisation **name** and not its ID. Fixing the behavior is welcome, but should be signaled when upgrading because definitely a breaking change.

This breaking change was caused by https://github.com/influxdata/influxdb-client-csharp/pull/287, I will update the `CHANGELOG.md` to clarify current behaviour.

> Maybe add a method `taskApi.FindTasksByOrganizationNameAsync(string orgName)` to keep the behavior consistent? (but then that'd clutter the API).

There is a method `taskApi.FindTasksAsync`, which can be used to filter by `name` or `id`: 

```csharp
await _tasksApi.FindTasksAsync(org: "my-org")
```

Thanks again for your feedback

Regards
