### ISSUE TITLE
Make QueryAsync accept a Type instead of generic

### ISSUE THREAD

**Issue by maxreb** [influxdata/influxdb-client-csharp#230]
__Proposal:__
Make QueryAsync accept a `Type` parameter instead of generic so it will work also when we only now the Type on runtime.

__Current behavior:__
It's only whether `QueryAsync` which returns `FluxTable` or `QueryAsync<T>` which returns `T`

__Desired behavior:__
I would like to see a `Type` parameter on the `QueryAsync` method for the mapper.

__Alternatives considered:__
[Reflection](https://stackoverflow.com/a/232621/2770573)

__Use case:__
When we use mappers for `InfluxDbEntity` to e.g. `SensorData` and we use software like `AutoMapper` or create our own Mapper we probably don't know the `Type` of the entity while programming, but only on run time.

**Comment by bednar** [comment]
Hi @maxreb,

thanks for using our client and the suggestion 👍 Is this something you might be willing to help with?

Regards

**Comment by maxreb** [comment]
Hi bednar,

If this feature request is desired then I could try. I think the main part needs to be done [here](https://github.com/influxdata/influxdb-client-csharp/blob/c58a62aa3d75b8197e1e5c0e88a2bede7b20206d/Client.Core/Flux/Internal/FluxResultMapper.cs#L48) and the rest should be just updating the method calls.

Best,
Max
