### ISSUE TITLE
Is it possible to run schema.tagValues with this library?

### ISSUE THREAD

**Issue by schultzgc** [influxdata/influxdb-client-csharp#237]
I would like to call all devices that are present in the tag device,
in the ScriptEditor in the web interface this works with the following statement.

```
import "influxdata/influxdb/schema"
schema.tagValues(bucket: "Development", tag: "device")
```

Can I also realize this with the library?

**Comment by bednar** [comment]
Hi @schultzgc,

thanks for using our client.

You can use verbatim string:

```c#
const string query = @"import ""influxdata/influxdb/schema""
schema.tagValues(bucket: ""Development"", tag: ""device"")";

var fluxTables = await client.GetQueryApi().QueryAsync(query);
```

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
