### ISSUE TITLE
Is it possible to use LINQ client asynchronously?

### ISSUE THREAD

**Issue by horczech** [influxdata/influxdb-client-csharp#238]
I am trying to figure out how to use the Linq client asynchronously.  The documentation only talks about the synchronous client using the `QueryApiSync` 

```
var client = InfluxDBClientFactory.Create("http://localhost:8086", "my-token");
var queryApi = client.GetQueryApiSync();
var query = from s in InfluxDBQueryable<Sensor>.Queryable("my-bucket", "my-org", _queryApi, settings)
```

but there is no mention of the async version. Is there any way to do it?

**Comment by bednar** [comment]
Hi @horczech,

currently, the LINQ client doesn't supports asynchronous queries. Is this something you might be willing to help with?

Regards

**Comment by horczech** [comment]
@bednar Yea, I might be interested but I dont have much time currently so if it doesnt hurry I can check it out during next week and decide whether I will implement it and contact you for more information. Does it sound good?

**Comment by bednar** [comment]
@horczech, thanks for your help. I've quick look at our codebase and I think that we are able to add support for async querying quickly. Would you have time to check our changes?

**Comment by horczech** [comment]
@bednar Definitely

**Comment by bednar** [comment]
The #239 is ready to review. Can you take a look?

- updated `README.md`: https://github.com/influxdata/influxdb-client-csharp/blob/feat/linq-async/Client.Linq/README.md#asynchronous-queries
