### ISSUE TITLE
Unable to use client from Azure Functions project

### ISSUE THREAD

**Issue by SmagPie** [influxdata/influxdb-client-csharp#242]
There is currently an error in Azure Functions when they require System.Configuration.ConfigurationManager v5.0.0: https://github.com/dotnet/runtime/issues/54642

I cloned the repo and took the version down to 4.7 and it compiles, but lots of tests fail, I am not sure if they always fail without certain setup. Is there anything required from System.Configuration.ConfigurationManager v5.0.0?

**Comment by bednar** [comment]
Hi @SmagPie,

thanks for using our client.

> Is there anything required from System.Configuration.ConfigurationManager v5.0.0?

No, feel free to downgrade the `System.Configuration.ConfigurationManager` to `4.7.0` and prepare your own build of the client. Everything will work correctly.

The `System.Configuration.ConfigurationManager` has been updated due the performance optimisation, see - https://github.com/influxdata/influxdb-client-csharp/pull/175.

Regards.
