### ISSUE TITLE
Writing historical data into bucket

### ISSUE THREAD

**Issue by bryanmillerph** [influxdata/influxdb-client-csharp#243]
__Steps to reproduce:__
I have to load historical data into a bucket however when specifying a specific datetime value on the POCO object, after executing WriteMeasurements(), the datetime values recorded on influxdb are all the same (utc.now from what i see)

__Expected behavior:__
Inserted record should have the specified datetime value 

__Actual behavior:__
The inserted record's timestamp is set to the current datetime (utc.now)

__Specifications:__
 - Client Version: 3.0.0
 - InfluxDB Version: 2.0.7
 - Platform: Docker

**Comment by bednar** [comment]
Hi @bryanmillerph,

thanks for using our client.

> The inserted record's timestamp is set to the current datetime (utc.now). 

It looks like that timestamp on your POCO isn't used. 

Is your field annotated with `[Column(IsTimestamp = true)]`? Can you share a detail about your POCO? Definition and sample data...

Regards

**Comment by bryanmillerph** [comment]
I have retested my code and IsTimestamp was somehow not set
