### ISSUE TITLE
Querying SHOW DATABASES using InfluxDB.Client to InfluxDB 1.8

### ISSUE THREAD

**Issue by killerwife** [influxdata/influxdb-client-csharp#244]
I am having trouble using InfluxDB.Client to query version 1.8 using C#. The following code example crashes:

`
                var influxDBClient = InfluxDBClientFactory.Create(Config.DatabaseURL, Config.Username, Config.Password.ToCharArray());  
                var query = influxDBClient.GetQueryApi();  
                var result = await query.QueryAsync("SHOW DATABASES", "-");  
`

with the exception "undefined identifier SHOW"

After querying the DB using "http://myip:8086/query?u=user&p=pwd&q=SHOW DATABASES" it works just as intended. Is this sort of query not supported using the client? I am aware I can acquire this info by running a GET query but was wondering if this was possible in a nicer way.

**Comment by bednar** [comment]
Hi @killerwife,

thanks for using our client. 

The client is suppose to run [Flux](https://docs.influxdata.com/influxdb/v1.8/flux/) queries not [InfluxQL](https://docs.influxdata.com/influxdb/v1.8/query_language/). You can enable the Flux for InfluxDB by: https://docs.influxdata.com/influxdb/v1.8/flux/installation/.

Regards

**Comment by killerwife** [comment]
I have enabled flux, however, the flux system does not support listing 1.8 databases and the GetBucketsApi().FindBucketsAsync() does not work. (I am guessing the 1.8 doesnt have the compatibility endpoint for it) so what is supposed to be the customary way of querying it from 1.8 without this InfluxQL query?

**Comment by bednar** [comment]
> so what is supposed to be the customary way of querying it from 1.8 without this InfluxQL query?

Here is a document about parity of InfluxQL and Flux: https://docs.influxdata.com/influxdb/v1.8/flux/flux-vs-influxql/#influxql-and-flux-parity-1.

You can also try the [`v1.databases() function`](https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/v1/databases/).

**Comment by killerwife** [comment]
Thank you, that was very helpful, I struggled to find anything of sorts.
