### ISSUE TITLE
Check influxdb connection

### ISSUE THREAD

**Issue by abrasat** [influxdata/influxdb-client-csharp#253]
Is there any possibility to check if the InfluxDB database is still reachable, by using the InfluxDB client instance generated with  InfluxDBClientFactory.Create(...) ? Is there any functionality to automatically (re)connect to influxdb if connection is broken?
Is it a good idea to keep only one instance of the InfluxDBClient across the application, or would be better to create it on the fly each time where needed (even when cyclically writing measurements to influxdb)?

**Comment by bednar** [comment]
> Is there any possibility to check if the InfluxDB database is still reachable, by using the InfluxDB client instance generated with InfluxDBClientFactory.Create(...) ?

Yes - [HealthAsync()](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.InfluxDBClient.html#InfluxDB_Client_InfluxDBClient_HealthAsync)

> Is there any functionality to automatically (re)connect to influxdb if connection is broken?

There is no need to reconnect. Just catch an exception and perform task again. 

> Is it a good idea to keep only one instance of the InfluxDBClient across the application, or would be better to create it on the fly each time where needed (even when cyclically writing measurements to influxdb)?

The better is use client as a singleton.

**Comment by bednar** [comment]
> Thanks for the reply. Do you eventually have a link with a sample for the usage of HealthAsync() ?

```csharp
using System;
using System.Threading.Tasks;
using InfluxDB.Client;
using InfluxDB.Client.Api.Domain;

namespace Examples
{
    public static class PlatformExample
    {
        public static async Task Main(string[] args)
        {
            using var client = InfluxDBClientFactory.Create("http://localhost:9999", "my-token".ToCharArray());

            var status = (await client.HealthAsync()).Status;
            switch (status)
            {
                case HealthCheck.StatusEnum.Pass:
                    Console.WriteLine("UP");
                    break;
                case HealthCheck.StatusEnum.Fail:
                    Console.WriteLine("Down");
                    break;
            }
        }
    }
}
```

> I create a singleton for InfluxDBClient when starting my application, but if influxdb is not running at this point the client object will not be initialized (null).

How do you initiliaze the client?

> How can this be solved in a real application?

Try to use initialize the client with `token`, not with `username` and `password`.

**Comment by bednar** [comment]
How reliable is your InfluxDB instance? Is it self hosted OSS or Cloud?

What do you think about periodically check the `HealthAsync` before `await infDBCli.IsOnboardingAllowedAsync();`?

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
