### ISSUE TITLE
Convert field to tag for already stored measurement points

### ISSUE THREAD

**Issue by abrasat** [influxdata/influxdb-client-csharp#254]
Is it possible to convert a field (or several fields) to tag(s) for already stored measurement points? If yes, please provide code sample how to achieve it.
Thanks in advance.

**Comment by bednar** [comment]
Hi @abrasat,

I am not expert to `Flux`, try to ask at our Slack Channel - https://influxcommunity.slack.com/archives/CH8RGRW4T

Regards
