### ISSUE TITLE
Allow to set a client certificate on RestClient

### ISSUE THREAD

**Issue by glconti** [influxdata/influxdb-client-csharp#269]
__Proposal:__
Allow to configure the `ApiClient.RestClient` with a client certificate for the SSL tunnel

__Current behavior:__
`ApiClient` uses internally a RestSharp RestClient internally which can be configured through `InfluxDBClientOptions`, for example we can do.
```C#
if (!options.VerifySsl)
{
    RestClient.RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true;
}
```

__Desired behavior:__
Allow to set a client certificate on the RestClient in a similar way as other properties are configured, I have already it working locally with this piece of code:
```C#
if (options.ClientCertificate != null)
{
    RestClient.ClientCertificates ??= new X509CertificateCollection();
    RestClient.ClientCertificates.Add(options.ClientCertificate);
}
```

__Alternatives considered:__
None.

__Use case:__
This is used by a reverse proxy we have in front of InfluxDb. Maybe it's not the most common use case, but it is a security measure we have in place.

__Discussion__
I could push a PR for this feature, I have it already working in my fork. I saw, on the other hand, that @bednar is working on replacing `RestClient` with `HttpClient` in #268.
I don't know the timeframe for that feature, so I am asking here if we can have this working on `RestClient` or directly have that on the incoming `Http` client.

Thanks for the great work btw 💯

**Comment by bednar** [comment]
Hi @glconti,

thanks for using our client.

> I could push a PR for this feature, I have it already working in my fork.

Feel free to push a PR for this feature.

> I saw, on the other hand, that @bednar is working on replacing RestClient with HttpClient in #268. 
> I don't know the timeframe for that feature, so I am asking here if we can have this working on RestClient or directly have that on the incoming Http client.

Currently I don't know the exact ETA for #268... I suppose something like: `early 2022` 😶‍🌫️ 

Regards

**Comment by glconti** [comment]
A small update, I am discussing the [CLA](https://influxdata.com/community/cla/) signing with my employer, so it may just take a while to push my PR.
Hope to be able to publish it soon.

**Comment by bednar** [comment]
Hi @glconti, 

We are preparing a new major version of the client (`v4.0.0`) which added supports for specify client certificates. Please try the preview version by `dotnet add package InfluxDB.Client --version 4.0.0-dev.5097`. 

Any feedback will be appreciated 👂.

```csharp
var certificateCollection = new X509CertificateCollection { my_certificate };

var options = new InfluxDBClientOptions.Builder()
    .Url("http://localhost:8086")
    .AuthenticateToken("my-token".ToCharArray())
    .ClientCertificates(certificateCollection)
    .Build();

using var client = InfluxDBClientFactory.Create(options);
```

For more info about new major version see #283.

Regards

**Comment by bednar** [comment]
@glconti, the issue is fixed in new major update of the client - [`v4.0.0`](https://github.com/influxdata/influxdb-client-csharp/milestone/29) - which contains a few breaking changes. The most important change is in underlaying HTTP client - switch from legacy `HttpWebRequest` class, and uses `HttpClient` instead.

Please try a preview version by `dotnet add package InfluxDB.Client --version 4.0.0-dev.5280`. 

Any feedback will be appreciated 👂. For more info about new major version see [CHANGELOG.md](https://github.com/influxdata/influxdb-client-csharp/blob/master/CHANGELOG.md#400-unreleased).

**Comment by glconti** [comment]
Hi @bednar I tested the version `4.0.0-rc2` and it worked like a charm 🚀 

Sorry for not helping you there, I couldn't get the legal dept to sign the contribution agreement yet, you know, big companies problems 😭 

Nevertheless, thank you for the great job

**Comment by bednar** [comment]
Thank you for testing and I am glad that everything works for you 🤝
