### ISSUE TITLE
Incorrect points retuned from QueryAsync

### ISSUE THREAD

**Issue by francotiveron** [influxdata/influxdb-client-csharp#272]
I am using the following code:

```
var wApi = client.GetWriteApiAsync()
await wApi.WritePointsAsync(bucket, org, points)
var qApi = client.GetQueryApi()
var fluxTabls = await qApi.QueryAsync(flux, org)
```

__Expected behavior:__
the returned tables from `await QueryAsync` should contains the data just written earlier with `await WritePointsAsync`

__Actual behavior:__
90% of the times the result is as expected, however in the remaining case, one of two unexpected things occurs:

1) The written points are not returned in the tables (rare)
2) The written points are returned, but some fields have valid values, others have null values (frequent)

Note that repeating the query a few times, finally data get retrieved correctly (current workaround I am using for case 2)

__Specifications:__
 - Client Version: latest
 - InfluxDB Version: latest Docker Image
 - Platform: Docker Desktop Windows

**Comment by bednar** [comment]
Hi @francotiveron,

thanks for using our client.

> Note that repeating the query a few times, finally data get retrieved correctly (current workaround I am using for case 2)

Can you share a debug output of the client (`client.SetLogLevel(LogLevel.Body);`) to check if the data a returned correctly from the server?

Here is a documentation about `storage engine` - https://docs.influxdata.com/influxdb/v2.1/reference/internals/storage-engine.

Regards

**Comment by francotiveron** [comment]
@bednar I cannot see any log in the console, where do I find the log output?

**Comment by bednar** [comment]
>  I cannot see any log in the console, where do I find the log output?

The messages are written in `trace` listener. You can print messages to sys out by:

```csharp
Trace.Listeners.Contains(new TextWriterTraceListener(Console.Out))
```

> BTW, I have done further tests, and:
> 
> 1. The issue occurs mainly when the writer and the reader are different processes. When in the same process, it doesn't seem to occur
> 2. If I delay the readback for 1s, I get all the data as expected.
> 3. I tried with less than 1s, but 500 ms is still not enough.
> 4. The issue occurs either with the Async and Sync+Flush write apis
> 
> The delay solution is not good in my case because:
> 
> * The required delay could be load dependent, so 1s could be not enough in different circumstances
> * The application requires low latency (trading)
> 
> It seems that the in memory cache that the influx engine supposedly keeps does not work across different client instances or different processes?

I am not expert to InfluxDB storage engine, but I suppose that there can be a sync/flush/async operation. Please try to ask in our Slack Channel for InfluxDB 2 - https://influxcommunity.slack.com/archives/CJ2NXC6A2

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
