### ISSUE TITLE
QueryAsync Time Precision

### ISSUE THREAD

**Issue by caoyang1024** [influxdata/influxdb-client-csharp#273]
The _time field has insufficient precision, the raw data is something like 2021-12-28T00:00:00.005Z, but the _time field returned from QueryAsync method is 2021-12-28T00:00:00Z. 

Is there a way to specify time precision in the query or did I do anything wrong?

```
  var query = "from(bucket: \"ABC\") |> range(start: 2021-12-28T00:00:00Z, stop: 2021-12-28T00:10:00Z)";
  var tables = await client.GetQueryApi().QueryAsync(query, org);

  foreach (var record in tables.SelectMany(table => table.Records))
  {
      Console.WriteLine($"{record.GetTime()}");
  }
```

**Comment by bednar** [comment]
Hi @caoyang1024,

thanks for using our client.

Can you share a debug output of client? 

You can enable debug output by:
```csharp
client.SetLogLevel(LogLevel.Body);
```

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.

**Comment by Sputnik24** [comment]
I have the same question. What information do you need?

GetTime() of a record gives e.g. 2022-01-30T12:12:56Z but raw value read with Data Explorer is 2022-01-30T12:12:56.573Z. Question is to get time in raw format.

**Comment by bednar** [comment]
Hi @Sputnik24,

Is the `2022-01-30T12:12:56Z` formatted output or a raw representation of `Instant` value? The default formatter for `Instant` and `DateTime` hides the nanoseconds precision. Try to use something like:

```c#
var formattedValue = record.GetTime()?.ToDateTimeUtc().ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK");
```

Regards

**Comment by Sputnik24** [comment]
@bednar It is the direct output of GetTime() of FluxRecord class. Your code is working, thanks a lot.
