### ISSUE TITLE
Timeout on request leads to memory / handle leaks

### ISSUE THREAD

**Issue by Antricion** [influxdata/influxdb-client-csharp#274]
While the library seems to work great if the connection is stable, there seem to be issues when that isn't the case. So if the target influxDb is down, I want to check regularly in my program if the db is up again, so I can continue writing data. For this, I used the "HealthAsync" function, and since that one is marked as deprecated in the latest version 3.2.0 , tried to use the "PingAsync". Both have the same issue: When they fail, there are objects and handles that remain in memory. This seems to be RestSharp.HttpHeader, WebException, AsyncCallback and Microsoft.Win32.SafeHandles.SafeWaitHandle. All seem to increase with each communication timeout, even if I call GC.Collect() in between. As my application is huge, there is no way turning the whole thing to async, so I need to use the GetAwaiter() interface to use the async interfaces.

So "simply" setup a communication to a not running influxDb, and regularly check the connection status, and see the objects piling up.

My part of the code seems to be fairly simple:
` 

       protected bool ConnectionHealthy()
        {

            //HealthCheck check = baseClient.HealthAsync().GetAwaiter().GetResult();
            //isConnected = check.Status == HealthCheck.StatusEnum.Pass;
            isConnected = baseClient.PingAsync().GetAwaiter().GetResult();
            return isConnected;
        }
`

baseClient is of the type InfluxDB.Client.InfluxDBClient, and is created in the class once before starting the comm thread, so it gets reused here.

`

        protected void ThreadRun()
        {
                //setup stuff...

                while(doWork)
                {
                        if(!connected)
                        {
                                connected = ConnectionHealthy()
                        }
                        if(connected)
                        {
                                //do writing stuff...
                        }
                        waitEvent.WaitOne(lingerMs, true);
                }
        }
`

**Comment by Antricion** [comment]
It might be that this issue is generated inside the RestSharp library version 106 used by the influxdb client. With version 107 they introduced a breaking change in the interface, changing the classes internally used for the http protocol. So switching to RestSharp 107 might resolve the issue. At least a manual test directly implemented in my program on the new RestSharp interface just for ping produced no handle loss any more.

**Comment by bednar** [comment]
@Antricion thanks for your detail info. Currently we are working to transition from  `HttpWebRequest` to well-known `HttpClient`. Stay tuned.

**Comment by Antricion** [comment]
@Bednar thanks for your reply. A coworker just discovered that branch and informed me about it 15 minutes ago. So I'm looking forward to the new version when it's ready. Thanks for your work!

**Comment by bednar** [comment]
Hi @Antricion, 

We are preparing a new major version of the client (`v4.0.0`) which already uses `HttpClient`. Please try the preview version by `dotnet add package InfluxDB.Client --version 4.0.0-dev.5084`. 

Any feedback will be appreciated 👂.

Regards

**Comment by Antricion** [comment]
I tried that, it looks good so far. After a minimal adjustment (no separate ReadWriteTimeout any more) everything works fine, data is sent to the server (using line protocol), and I even seem to have a slightly increased data throughput. And when I stop the server, I see no loss of objects or data any more, neither per TaskManager (easy way) nor by the VS diagnostic tool. There the lost objects had been visible due to the sheer amount of them in the heap analysis, but not any more.

**Comment by bednar** [comment]
👍 Thank you for your feedback

**Comment by bednar** [comment]
@Antricion, the issue is fixed in new major update of the client - [`v4.0.0`](https://github.com/influxdata/influxdb-client-csharp/milestone/29) - which contains a few breaking changes. The most important change is in underlaying HTTP client - switch from legacy `HttpWebRequest` class, and uses `HttpClient` instead.

Please try a preview version by `dotnet add package InfluxDB.Client --version 4.0.0-dev.5280`. 

Any feedback will be appreciated 👂. For more info about new major version see [CHANGELOG.md](https://github.com/influxdata/influxdb-client-csharp/blob/master/CHANGELOG.md#400-unreleased).

**Comment by Antricion** [comment]
So till now I (and the testers) had no issues with the new RC1, seems great so far.
