### ISSUE TITLE
No server version on Ping

### ISSUE THREAD

**Issue by Antricion** [influxdata/influxdb-client-csharp#275]
With version 3.2.0, the Health request was deprecated and replaced by the Ping request. While the Health request delivered the server version, the Ping request used by InfluxDBClient.VersionAsync() doesn't. This is due to the response of my influx server, as I verified with WireShark that the response from the server (2.0.8 on a Ubuntu VM) has an empty(!) X-Influxdb-Version field.

**Comment by bednar** [comment]
Hi @Antricion,

thanks for using our client.

> This is due to the response of my influx server, as I verified with WireShark that the response from the server (2.0.8 on a Ubuntu VM) has an empty(!) X-Influxdb-Version field.

This is a server bug. You have to update the InfluxDB to newest version.

```bash
docker run --detach --publish 8086:8086 influxdb:latest  
curl -i -X GET 'http://localhost:8086/ping' 

>

HTTP/1.1 204 No Content
X-Influxdb-Build: OSS
X-Influxdb-Build: oss2
X-Influxdb-Version: 2.1.1
X-Influxdb-Version: 2.1.1
Date: Thu, 27 Jan 2022 10:58:27 GMT
```

Regards

**Comment by Antricion** [comment]
OK, I'll do that. Thanks for the fast reply.
