### ISSUE TITLE
Window and aggregate data using LINQ

### ISSUE THREAD

**Issue by amitrotner** [influxdata/influxdb-client-csharp#278]
Hi,

Is it possible to window and aggregate data using LINQ query?
For example, as seen in: https://docs.influxdata.com/influxdb/cloud/query-data/flux/window-aggregate/#aggregate-data, take the average of each window

Thanks

**Comment by bednar** [comment]
Hi @amitrotner,

thanks for using our client.

> Is it possible to window and aggregate data using LINQ query?

At the current state unfortunately not, but I will take a look.

Regards

**Comment by bednar** [comment]
@amitrotner, what do you think about [aggregateWindow() function](https://docs.influxdata.com/flux/v0.x/stdlib/universe/aggregatewindow/)?

I think we are able to prepare something like:
![image](https://user-images.githubusercontent.com/455137/152320662-6c95e14d-095a-4709-83f7-c70baa6b73ef.png)

Is it suitable for you?

**Comment by amitrotner** [comment]
@bednar Yes, it is suitable for me.
Thanks!

**Comment by bednar** [comment]
I have prepared a fixed version within #282. Development version of the client will be available after #282 acceptance, stable version in regular release cycle.
