### ISSUE TITLE
Define measurement name at runtime using POCO

### ISSUE THREAD

**Issue by Sputnik24** [influxdata/influxdb-client-csharp#285]
__Proposal:__
Allow writing measurements using POCO where measurement name is known at runtime.

__Current behavior:__
Writing data based on a class with attribute [Measurement("")] throws an exception System.ArgumentException: "Expecting a non-empty string for Measurement name". Reading is working.

__Desired behavior:__
Set the measurement name at runtime when writing the data.

__Alternatives considered:__
Of course, writing by data point is working where I can define the measurement name at runtime.

__Use case:__
I'm writing an InfluxDB editor reading, editing and adding data to a InfluxDBv2. The data is actually written by iobroker. All measurements (currently 122) in the database have the same fields and tags. So, I wrote a class using POCO which represents any measurements:
`[Measurement("")]
public class DataPoint {
    [Column(IsTimestamp = true)] public DateTime Time { get; set; }
    [Column("value")] public object Value { get; set; }
    [Column("from")] public string From { get; set; }
    [Column("ack")] public bool Ack { get; set; }
    [Column("q")] public object Q { get; set; }
}`

For reading data, leaving the Name attribute as empty string is working:
`var flux = $"from(bucket: \"{bucket}\")" +
    $"|> range(start: {datetime_start.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")}, stop: {datetime_end.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")})" +
    $"|> filter(fn: (r) => r[\"_measurement\"] == \"{selectedMeasurement}\")" +
    $"|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")";
var fluxTables = await client.GetQueryApi().QueryAsync<DataPoint>(flux, organization);`

Writing, of course, is not working, as I cannot define the measurement name using DataPoint class and POCO:
`var data = new DataPoint { Ack = true, Value = i, From = "Csharp", Q = 0 };
var writeApi = client.GetWriteApiAsync();
await writeApi.WriteMeasurementAsync(bucket, organization, InfluxDB.Client.Api.Domain.WritePrecision.Ns, data);`
Throws an error: System.ArgumentException: "Expecting a non-empty string for Measurement name"

So, is there any possibility to create a measurement name independent class, defining the name at runtime and using POCO?

**Comment by bednar** [comment]
Hi @Sputnik24,

thanks for using our client.

> So, is there any possibility to create a measurement name independent class, defining the name at runtime and using POCO?

You can use attribute: `[Column(IsMeasurement = true)]`. For more info see:

- https://github.com/influxdata/influxdb-client-csharp/pull/240
- https://github.com/influxdata/influxdb-client-csharp/blob/master/Client.Test/MeasurementMapperTest.cs#L151
- https://github.com/influxdata/influxdb-client-csharp/blob/ec8daa2d950ecb856f58c9ea339e5d8aa27fe4d5/Client.Test/MeasurementMapperTest.cs#L96

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
