### ISSUE TITLE
TasksAPI parameters not mapped correctly

### ISSUE THREAD

**Issue by ksks88** [influxdata/influxdb-client-csharp#286]
When calling TasksAPI methods FindTasksByOrganizationIdAsync(3a123378483afd33) or FindTasksByOrganizationAsync(organization) I get following error:

` InfluxDB.Client.Core.Exceptions.BadRequestException: 'failed to decode request: organization name "3a123378483afd33" not found'`

__Expected behavior:__
I expect to get list of tasks.

__Actual behavior:__
Methods throw exception. Also if I pass Organization name to method FindTaskByOrganizationId i get list of tasks.

__Specifications:__
 - Client Version: 3.3.0
 - InfluxDB Version: 2.1.1
 - Platform: Win

I couldn't find similar issue if this one is adressed please close.
Thanks,
Salih

**Comment by bednar** [comment]
Hi @ksks88,

thanks for using our client.

We will prepared fixed version of the client ASAP. Meanwhile you can use following workaround:

```c#
using var client = InfluxDBClientFactory.Create(
    "http://localhost:9999",
    "my-user", 
    "my-password".ToCharArray());

var tasksService = client.CreateService<TasksService>(typeof(TasksService));

var tasks = (await tasksService.GetTasksAsync(orgID: "ca7de8c4f43b7245").ConfigureAwait(false))._Tasks;

foreach (var task in tasks)
{
    Console.WriteLine($"task: {tasks}");
}
```

Regards
