### ISSUE TITLE
[Question] How to check if a connection can be established?

### ISSUE THREAD

**Issue by Tobist** [influxdata/influxdb-client-csharp#296]
I am trying to check if the connection is valid or not. I can Ping the server and get a false or true, but I cannot read the version or the readiness of the server. Am I doing something wrong?

I would like to check the connection completely before I send other writing or reading requests. 

__Code__

```
InfluxDBClientOptions.Builder builder = InfluxDBClientOptions.Builder.CreateNew();
builder.Url("https://westeurope-1.azure.cloud2.influxdata.com");
builder.AuthenticateToken(token);
builder.Bucket(bucket);
builder.Org(org);

using var client = InfluxDBClientFactory.Create(builder.Build()); 

var healthCheck = client.PingAsync().Result;
var ready = client.ReadyAsync().Result;
var version = client.VersionAsync().Result;
```
 

__Steps to reproduce:__
1. request ReadyAsync on an influxdbclient
2. request VersionAsync on an influxdbclient

__Expected behavior:__
1. Gives state of the readiness
2. Return version value

__Actual behavior:__
1. Returns 'null'
2. Returns 'unknown'

__Specifications:__
 - Client Version: 3.3.0
 - InfluxDB Version: unknown
 - Platform: InfluxDB Cloud

**Comment by bednar** [comment]
Hi @Tobist,

thanks for using our client.

> 1. request ReadyAsync on an influxdbclient
> 1. Returns 'null'

The `/ready` endpoint is not supported at InfluxDB Cloud. According to InfluxDB API, the `/ready` is suppose to check the readiness of an instance at startup => it is relevant only for InfluxDB OSS. Please use `client.PingAsync()`

I will update docs for `ReadyAsync()`.

- https://docs.influxdata.com/influxdb/v2.1/api/#tag/Ready

> 1. request VersionAsync on an influxdbclient
> 1. Returns 'unknown'

It is bug, we will fix it ASAP.

Regards

**Comment by Tobist** [comment]
Thank you for the quick response. 

What I am trying to do is, to check if the database is usable to read from and write to it. With the ping request I can only check if the server is reachable, but not if the Token is correct.
Is there a basic connection check/health opportunity in the api/endpoint?

**Comment by bednar** [comment]
> What I am trying to do is, to check if the database is usable to read from and write to it. With the ping request I can only check if the server is reachable, but not if the Token is correct.

Unfortunately the InfluxDB doesn't have `endpoint` for this. You can use something like this:

```csharp
using System;
using System.Threading.Tasks;
using InfluxDB.Client;
using InfluxDB.Client.Core.Exceptions;

namespace Examples
{
    public static class PlatformExample
    {
        public static async Task Main(string[] args)
        {
            const string url = "http://localhost:8086";
            const string token = "my-token2";
            const string org = "my-org";

            using var client = InfluxDBClientFactory.Create(url, token.ToCharArray());
            try
            {
                await client.GetQueryApi().QueryAsync("buckets()", org);
                Console.WriteLine("OK");
            }
            catch (UnauthorizedException)
            {
                Console.WriteLine("Unauthorized");
            }
        }
    }
}
```

Regards

**Comment by Tobist** [comment]
Thanks a lot!
