### ISSUE TITLE
Using timestamp in LineProtocol doesn't work ? 

### ISSUE THREAD

**Issue by ossandust** [influxdata/influxdb-client-csharp#299]
Following C# code doesn't insert any record : 
string command = "scmdata,metric=ORV value=231i 1647613310874625000";
writeApi.WriteRecord(command, WritePrecision.S, "[bucket]", "[organisation]");

while doing the same through the Influx CLI does work : 
influx write "scmdata,metric=ORV value=231i 1647613310874625000"

When I remove the timestamp the C# code does work. 

BTW is there a way to activate any error logging when using the InfluxDB.Client?  A syntax error in the LineProtocol command results in nothing being written to the database without any error or exception - I need to use the same command through the CLI to get error feedback (except in above case, where the CLI command does work correctly, while the C# code doesn't)

**Comment by bednar** [comment]
Hi @ossandust,

thanks for using our client.

> string command = "scmdata,metric=ORV value=231i 1647613310874625000";
writeApi.WriteRecord(command, WritePrecision.S, "[bucket]", "[organisation]");

The timestamp `1647613310874625000` has precision in nanoseconds so you have to use `WritePrecision.NS`/

> BTW is there a way to activate any error logging when using the InfluxDB.Client?

You can enable logging of HTTP request by : `Client.SetLogLevel(LogLevel.Body);`. 

> A syntax error in the LineProtocol command results in nothing being written to the database without any error or exception

The [`WriteApi`](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.WriteApi.html) uses background thread to ingesting data into InfluxDB. If you want to handle background error please use `Error` handler - https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#handle-the-events

You can also use [`WriteApiAsync`](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.WriteApiAsync.html) which directly propagate errors from InfluxDB.

Regards

**Comment by ossandust** [comment]
Thanks bednar !
