### ISSUE TITLE
Add Option to Disable Retry on Write

### ISSUE THREAD

**Issue by nguyendd** [influxdata/influxdb-client-csharp#303]
__Proposal:__
Enable a parameter that disables write retries.
__Current behavior:__
All retry options require a positive number so retries are mandatory.
__Desired behavior:__
Make it similar to the go client, 

> Setting retryInterval to 0 disables retry strategy and any failed write will discard the batch.

__Use case:__
It make the Flush behavior more controllable. We want to make a synchronous write request to influx and immediately move on if it fails.

**Comment by bednar** [comment]
Hi @nguyendd,

thanks for using our client.

> Setting retryInterval to 0 disables retry strategy and any failed write will discard the batch.

We will take a look.

> We want to make a synchronous write request to influx and immediately move on if it fails.

For this use case will be better to use a [WriteApiAsync](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.WriteApiAsync.html).

Regards

**Comment by nguyendd** [comment]
> For this use case will be better to use a [WriteApiAsync](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.WriteApiAsync.html).

Thanks! I misinterpreted that. This is sufficient for our use case.
