### ISSUE TITLE
Performance Results

### ISSUE THREAD

**Issue by Simonl9l** [influxdata/influxdb-client-csharp#311]
### Problem:

It seem that writing events into the Influx DB is not particularly fast. For example `WritePointsAsyncWithIRestResponse` with a single point and a locally running InfluxDB install is resetting in only ~4 writes a second.

It seems the internal use of the RestSharp library is fully encapsulated and have not tries to walk the code base too deeply but did find that [others](https://romikoderbynew.com/2012/01/17/slow-httpwebrequest-getresponse/) have had performance issues with RestSharp 

It would be helpful if performance values from say DotNet Benchmark were available for each of the API calls and be able to see if any performance impacts occur with each release.

We figure we're doing something wrong. This is out invocation call:
``` C#
var res = await client
    .GetWriteApiAsync()
   .WritePointsAsyncWithIRestResponse(new[] { point }, _bucketName, org: _orgName, cancellationToken: ctx);
```
With this code commented out our process can per dotnet-counter process ~400 points per second, however reenabling the code results in a  drop to the ~4 points written per second - 100x lower performance!

In all cases the Response status in Completed.

__Specifications:__
 - Client Version: 4.0.0
 - InfluxDB Version: 2.1.1
 - Platform: MacOS

**Comment by bednar** [comment]
Hi @Simonl9l,

thanks for using our client.

Unfortunately I am not able simulate your performance issue.

I've used following code to check performances and writes are around ~400 point per second:

```c#
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using InfluxDB.Client;
using InfluxDB.Client.Writes;

namespace Examples
{
    public static class WritePerformanceExample
    {
        private const string Host = "http://localhost:9999";
        private const string Token = "my-token";
        private const string Bucket = "my-bucket";
        private const string Organization = "my-org";

        public static async Task Main(string[] args)
        {
            //
            // Initialize Client
            //
            var options = new InfluxDBClientOptions.Builder()
                .Url(Host)
                .AuthenticateToken(Token.ToCharArray())
                .Org(Organization)
                .Bucket(Bucket)
                .Build();
            var client = InfluxDBClientFactory.Create(options);

            //
            // Prepare points
            //
            var points = Enumerable.Range(1, 400).Select(x => PointData
                    .Measurement("temperature")
                    .Tag("location", "west")
                    .Field("value", $"{x}i"))
                .ToList();

            var stopWatch = new Stopwatch();
            stopWatch.Start();

            //
            // Write points
            //
            foreach (var point in points)
            {
                await client.GetWriteApiAsync().WritePointsAsync(new[] { point });
                // await client.GetWriteApiAsync().WritePointsAsyncWithIRestResponse(new[] { point });
            }

            Console.WriteLine($"Elapsed milliseconds: {stopWatch.Elapsed.TotalMilliseconds}");

            client.Dispose();
        }
    }
}
```

How looks like your `point`? 

__Specifications:__
 - Client Version: 4.1.0
 - InfluxDB Version: 2.2.0
 - Platform: MacOS

**Comment by bednar** [comment]
> It would be helpful if performance values from say DotNet Benchmark were available for each of the API calls and be able to see if any performance impacts occur with each release.

@rhajek works on integration benchmarks in our CI pipeline

**Comment by Simonl9l** [comment]
@bednar Thanks for the quick turn around. 

So per you code above in my environment I was get the total elapsed time of 15298.6462ms so only ~26/s ? are you saying if you run the above you get a total runtime of 1000ms?

Whose Im running a Macbook Pro Max with a hole brew local install, I'd figure the performance would be better, and ma sure it was at some point, but being a influxDB newbie have no idea what is going wrong.

I my environment I have a point with 3 tags, 2 fields value and timestamp.

Not sure what your https://github.com/influxdata/influxdb-client-csharp/pull/313

**Comment by bednar** [comment]
I am using MacBook Air (M1, 2020) and my results is:

> Elapsed milliseconds: 1148.1415

Does the InfluxDB have enough resources? Here is a document about hardware sizing: https://docs.influxdata.com/influxdb/v1.8/guides/hardware_sizing/#influxdb-oss-guidelines

#313 fixing issue which is not related to performance

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
