### ISSUE TITLE
Getting data continuously from InfluxDB bucket as it written

### ISSUE THREAD

**Issue by Simonl9l** [influxdata/influxdb-client-csharp#312]
With the change to InfluxDB v2 it seem that continuous query have been replaced by Tasks.

Is there a sample anywhere that show how once can leverage a Task query data out of a bucket as its written - in effect it awaits for new data. 

Is the achieved by some kind of windowed polling with a regular query that each time uses a new range start based on the Timestamp of the last event retrieved + 1 ns?

Use case, I want to feed data from Influx DB into another system as it arrives. I can write to influx DB. I can then use a query to use a loopback window to generate a statistical summary of that data.

Thanks for any advice. More samples are always helpful.

**Comment by bednar** [comment]
Hi @Simonl9l,

thanks for using our client.

> With the change to InfluxDB v2 it seem that continuous query have been replaced by Tasks.
> 
> Is there a sample anywhere that show how once can leverage a Task query data out of a bucket as its written - in effect it awaits for new data.

You can create `Task` which use a `"to"` function. For more info see:

1. How to migrate `Continues Query` to `Task` - https://docs.influxdata.com/influxdb/latest/upgrade/v1-to-v2/migrate-cqs/ 
2. Supported output datasources - https://docs.influxdata.com/flux/v0.x/write-data/

> Is the achieved by some kind of windowed polling with a regular query that each time uses a new range start based on the Timestamp of the last event retrieved + 1 ns?
> 

I suppose so, but I'm no expert on an implementation of `Tasks` at server side.

> Use case, I want to feed data from Influx DB into another system as it arrives. I can write to influx DB. I can then use a query to use a loopback window to generate a statistical summary of that data.
> 
> Thanks for any advice. More samples are always helpful.

You can create `Task` by client API:

```c#
const string flux = @"option task = {name: ""resample-example"", every: 1m}

from(bucket: ""my-db/"")
    |> range(start: -30m)
    |> filter(fn: (r) => r._measurement == ""example-measurement"" and r._field == ""example-field"" and r.region == ""example-region"")
    |> aggregateWindow(every: 1m, fn: mean)
    |> exponentialMovingAverage(n: 30)
    |> set(key: ""_measurement"", value: ""resample-average-example-measurement"")
    |> to(bucket: ""my-db/"")";

var taskCreateRequest = new TaskCreateRequest(
    orgID: _organization.Id, 
    status: TaskStatusType.Active, 
    flux: flux);

var task = await Client.GetTasksApi().CreateTaskAsync(taskCreateRequest);
```

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
