### ISSUE TITLE
Linq: add option to include future timestamps when no time range is provided

### ISSUE THREAD

**Issue by jlytle-influxdata** [influxdata/influxdb-client-csharp#320]
__Proposal:__
Provide a configurable option for including data with future timestamps when no time bounds are explicitly set.

__Current behavior:__
When a query has no time bounds set, the InfluxDB.Client.Linq library doesn't have a way to include data with future timestamps in the results (defaults to now()). 

__Desired behavior:__
Data with future timestamps would be included in query results without hardcoding an arbitrary future stop date range when an explicit option is specified to override the default stop date range of now() (when no stop date range is explicitly set).

__Alternatives considered:__
The current workaround is to hardcode an arbitrary future stop date range to ensure data with future timestamps is included in query results. This has obvious downsides and testing future stop date ranges _(curl -> api, not with this library)_ had some unpredictable results when going too far into the future.

__Use case:__
Data with future timestamps has domain-specific uses but at a minimum prediction statistics. The unknown nature of future data makes hardcoding an unrealistic method to maintain.

**Comment by bednar** [comment]
Hi @jlytle-influxdata,

I've prepared a fixed version within #322. The development version of the `client` will be available after #322 acceptance, stable version in regular release cycle.

For more info see #322.

Regards
