### ISSUE TITLE
Allow certificate verification against known self signed certificate

### ISSUE THREAD

**Issue by nickbabcock** [influxdata/influxdb-client-csharp#321]
__Proposal:__
When given an expected certificate that the server will present, the influxdb client should validate against the given certificate.

__Current behavior:__
Currently `VerifySsl` only accepts a true or false parameter.

__Desired behavior:__
This is how I accomplish the desired behavior on the 3.x client using `ServicePointManager` by assuming the if the input isn't `true` or `false` that the parameter points to a file location of the certificate.

```cs
public static void InstallCertificateVerification(string type)
{
    switch (type.ToLowerInvariant())
    {
        // Do not change default .net behavior when given True
        case "true":
            break;

        // Do not verify certificate
        case "false":
            ServicePointManager.ServerCertificateValidationCallback =
                (sender, certificate, chain, errors) => true;
            break;

        // Else assume that it points to a file path of a self signed
        // certificate that we will check against
        default:
            var cert = new X509Certificate2(type);
            ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, errors) =>
                errors == SslPolicyErrors.None ||
                string.Equals(cert.Thumbprint, certificate.GetCertHashString(), StringComparison.InvariantCultureIgnoreCase);
            break;
    }
}
```

__Alternatives considered:__
Until this feature is added, the alternative is to pin to 3.x and use the method shown above

__Use case:__
Disabling all ssl verifications is a heavy handed approach when one has a known certificate that is self signed

**Comment by bednar** [comment]
Hi @nickbabcock,

thanks for using our client.

What do you think about new configuration option for `InfluxDBClientOptions`... something like: `RemoteCertificateValidationCallback`:

```c#
var cert = new X509Certificate2("path_to_file");

var options = new InfluxDBClientOptions.Builder()
    .Url("http://localhost:8086")
    .AuthenticateToken("my-token")
    .RemoteCertificateValidationCallback((sender, certificate, chain, errors) => 
        errors == SslPolicyErrors.None || string.Equals(cert.Thumbprint, certificate?.GetCertHashString(), StringComparison.InvariantCultureIgnoreCase))
    .Build();

using var client = InfluxDBClientFactory.Create(options);
```

?

Regards
