### ISSUE TITLE
Add public parameterless constructor to InfluxDbClient to allow mocking for unit test

### ISSUE THREAD

**Issue by vudzero** [influxdata/influxdb-client-csharp#325]
__Proposal:__
It would be nice for the InfluxDbClient class to have a parameterless constructor to allow for easy mocking in unit test. An IInfluxDbClient interface would also to the trick!

__Current behavior:__
Impossible to mock InfluxDbClient since all constructors are "internal" and no Interface is available

__Desired behavior:__
Mock InfluxDbClient with a library like MOQ

__Alternatives considered:__
Create an adapter, but event there, classes like WriteApi are also internal, so impossible to create an adapter properly

__Use case:__
Allow unit testing of libraries using this wonderful library

**Comment by bednar** [comment]
Hi @vudzero,

thanks for using our client. We will take a look.

Regards
