### ISSUE TITLE
Write failure, how to monitor？？

### ISSUE THREAD

**Issue by Rodifen** [influxdata/influxdb-client-csharp#331]

**Comment by bednar** [comment]
Hi,

thanks for using our client.

You can use `WriteErrorEvent` if you uses the batching write client. For
more info see:

-
https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#writes
-
https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#handle-the-error-write

Regards

**Comment by Rodifen** [comment]
Good!
