### ISSUE TITLE
Could not load file or assembly Microsoft.Extensions.ObjectPool Version 6.0.0.0

### ISSUE THREAD

**Issue by takczyowak** [influxdata/influxdb-client-csharp#332]
The issue is very much the same like here:
https://github.com/influxdata/influxdb-client-csharp/issues/200#issue-891838187
https://github.com/influxdata/influxdb-client-csharp/issues/133#issuecomment-856159084

However I've noticed that reference version in packages does not match references from `GetReferencedAssemblies()`
![image](https://user-images.githubusercontent.com/59870864/179000737-ef92ffc6-5624-4c52-b852-8012360b2564.png)

It is quite an issue for me because I can't use `bindingRedirect` in app.config.

__Specifications:__
 - Client Version: 4.3.0
 - InfluxDB Version: 2.0.0
 - Platform: Windows 10 Pro

**Comment by bednar** [comment]
Hi @takczyowak,

thanks for using our client.

Hard to say what causes the problem... 😞 

Can you try reinstall the package by `Update-Package -reinstall`? Do you have enabled `AutoGenerateBindingRedirects` in your config? You can also try to completely clean your solution - delete all `bin` and `obj` directories...

Regards

**Comment by takczyowak** [comment]
Yea did all those things but in vain :/ Isn't that some kind issue of `ObjectPool` library itself? I mean the screenshot I've took above was done directly on 4.3.0 release revision. Obviously you can see there that lib version that is referenced in `Client` assembly does not match the version of nuget library that is linked there in solution explorer.

**Comment by bednar** [comment]
> Yea did all those things but in vain :/ Isn't that some kind issue of `ObjectPool` library itself (I mean maybe nuget version is changed but dll version stays intact)?

It looks like. If I changed version to `5.0.17` the assembly version was reported as a `5.0.0.0`. The `fuget.org` has assembly version also as a 6.0.0:

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/455137/179345709-830ac70f-2171-4863-ad4f-f499b229de7c.png">

- https://www.fuget.org/packages/Microsoft.Extensions.ObjectPool/6.0.7/lib/netstandard2.0/Microsoft.Extensions.ObjectPool.dll

**Comment by takczyowak** [comment]
Ok that's what I was fearing. I guess there is not too much that we can do about that :(

**Comment by bednar** [comment]
Will you try to create an issue in https://github.com/dotnet/aspnetcore?

**Comment by takczyowak** [comment]
Great idea, will do! However I'll do that tomorrow and link it here :)

**Comment by takczyowak** [comment]
Ok, so I guess that output of `ObjectPool` discussion with aspnetcore team tells us we can close this issue :(

**Comment by JesperNJessen** [comment]
I'm getting this same error with version 4.11.0 of the client using .NET 6. If I revert to version 4.9.0 the error goes away.
