### ISSUE TITLE
InfluxQL Support?

### ISSUE THREAD

**Issue by ceds** [influxdata/influxdb-client-csharp#339]
Does this library support InfluxQL?  

https://docs.influxdata.com/influxdb/v1.8/query_language/

Executing InfluxQL code via Query API does not seem to be working.

**Comment by bednar** [comment]
Hi @ceds,

thanks for using our client.

The client doesn't supports `InfluxQL`. You can use `Flux` with InfluxDB 1.8, for more info see: https://docs.influxdata.com/influxdb/v1.8/flux/installation/

Regards
