### ISSUE TITLE
API Reference link 404

### ISSUE THREAD

**Issue by LarsStegman** [influxdata/influxdb-client-csharp#344]
Hello, the API reference documentation link in the README.md links to a 404 page.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Click on the [link in the README.md](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.html)

__Expected behavior:__
API Reference documentation opens

__Actual behavior:__
I get a 404

__Specifications:__
 - Client Version: N/A
 - InfluxDB Version: N/A
 - Platform: N/A

**Comment by bednar** [comment]
Hi @LarsStegman,

the reference documentation is back. Checkout the homepage: https://influxdata.github.io/influxdb-client-csharp/

Regards

Regards
