### ISSUE TITLE
HealthAsync() is only obsolete on the InfluxDBClient, not on interface

### ISSUE THREAD

**Issue by knollsen** [influxdata/influxdb-client-csharp#359]
I noticed that the health check method HealthAsync() is obsolete on the InfluxDBClient and says to use PingAsync() instead. However, the interface has no such designation. Is there a reason for this or should it be obsolete on the interface as well?

**Comment by bednar** [comment]
Hi @knollsen,

thanks for using our client.

> Is there a reason for this or should it be obsolete on the interface as well?

It is a bug, it should be obsolete on the interface also.

Regards

**Comment by knollsen** [comment]
Hi @bednar, thank you very much for the quick answer! 

Is there a reason that HealthAsync() is deprecated? I know that PingAsync() is now the recommended method to check if the server is running, but it only returns true or false while HealthAsync() gives more information like version, name and a message.

**Comment by bednar** [comment]
The `HealthAsync()` is not compatible between OSS and Cloud version. For the `version` you can use `VersionAsync`.

**Comment by knollsen** [comment]
Thank you, that makes sense. I opened a PR to make it clear that this method is obsolete on the interface as well.

**Comment by bednar** [comment]
@knollsen, thanks.

The PR is merged into `master`.
