### ISSUE TITLE
Client cannot parse query results from InfluxDB 1.10.0 since the annotations are missing in the csv.

### ISSUE THREAD

**Issue by ulf-melin-sveasolar** [influxdata/influxdb-client-csharp#366]
__Steps to reproduce:__

1. Using a client object:  client = InfluxDBClientFactory.CreateV1(Configuration.Endpoint, Configuration.Username,
            Configuration.Password.ToCharArray(), Configuration.Database, RetentionPolicy);
2. Query something like: from(bucket: "staging") |> range(start: -111h) |> filter(fn: (r) => r._measurement == "meter_values" and r._field == "sequence") |> filter(fn: (r) => r.chargerId == "southpark") |> max() |> limit(n:1)

__Expected behavior:__
I get a table with a record containing the _value I queried for.

In raw format, with annotations

#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string,string,string,string,string,string,string,string,string,string
#group,false,false,true,true,false,false,true,true,true,true,true,true,true,true,true,true,true
#default,_result,,,,,,,,,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,chargerId,connectorId,context,locationId,measurand,productId,source,transactionId,unit
,,0,2022-08-02T18:46:34.4187654Z,2022-09-13T10:46:34.4187654Z,2022-09-13T10:43:31Z,101,sequence,meter_values,ulfsw,1,SamplePeriodic,hemma,EnergyActiveImportRegister,wallboxproduct,Outlet,5,KWh

__Actual behavior:__
Throws an exception:
InfluxDB.Client.Core.Flux.Exceptions.FluxCsvParserException: Unable to parse CSV response. FluxTable definition was not found.

In raw format, the annotations are missing:

,result,table,_start,_stop,_time,_value,_field,_measurement,chargerId,context,locationId,measurand,productId,source,unit
,_result,0,2022-09-08T18:39:25.800511841Z,2022-09-13T09:39:25.800511841Z,2022-09-10T14:05:09Z,521766,sequence,meter_values,southpark,SampleClock,17746a46-7275-4e03-87cb-e77d680b20e4,PowerActiveImport,fb08e075-dfb7-4821-97d1-2bc14e0f1a67,Outlet,KW

__Specifications:__
 - Client Version: 4.5.0
 - InfluxDB Version: 1.10.0 (Cloud)
 - Platform: .Net 6.0

**Comment by bednar** [comment]
Hi @ulf-melin-sveasolar,

thanks for using our client. 

> #datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string,string,string,string,string,string,string,string,string,string #group,false,false,true,true,false,false,true,true,true,true,true,true,true,true,true,true,true #default,_result,,,,,,,,,,,,,,,, ,result,table,_start,_stop,_time,_value,_field,_measurement,chargerId,connectorId,context,locationId,measurand,productId,source,transactionId,unit ,,0,2022-08-02T18:46:34.4187654Z,2022-09-13T10:46:34.4187654Z,2022-09-13T10:43:31Z,101,sequence,meter_values,ulfsw,1,SamplePeriodic,hemma,EnergyActiveImportRegister,wallboxproduct,Outlet,5,KWh

I've tested your query output with annotations and the client is able to parse it without `FluxCsvParserException`.

Can you share your code to invoke query or debug output of the client with full stack trace?
You can enable debug output by: `client.SetLogLevel(LogLevel.Body);`

Regards

**Comment by ulf-melin-sveasolar** [comment]
Hi, yes it should be able to parse it if the annotations are there, but when querying against influxDB 1.10.0 then it does not return any annotations, that’s when the exception is thrown. It all works well if I query an instance of influxDB 1.8

But for now I have resorted to using the other package you provide <PackageReference Include="InfluxDB.Client.Flux" Version="4.5.0" /> and that works for me. But still there may be a bug for you to fix, I do not know.

Sorry if I wasted your time, and thanks for responding quickly!

Best regards
Ulf Melin

Från: Jakub Bednář ***@***.***>
Skickat: den 14 september 2022 13:58
Till: influxdata/influxdb-client-csharp ***@***.***>
Kopia: Ulf Melin ***@***.***>; Mention ***@***.***>
Ämne: Re: [influxdata/influxdb-client-csharp] Client cannot parse query results from InfluxDB 1.10.0 since the annotations are missing in the csv. (Issue #366)


Hi @ulf-melin-sveasolar<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fulf-melin-sveasolar&data=05%7C01%7Culf.melin%40sveasolar.com%7Cd5011c4d23c444d1922208da96486dd5%7C4ae6cd050df643c8819785f6b968ff21%7C0%7C0%7C637987535064328234%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nclgo%2F%2BWwdjz9G1hfySDJTU%2B6wKzUFIUbSfSMVhamW4%3D&reserved=0>,

thanks for using our client.

#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string,string,string,string,string,string,string,string,string,string #group,false,false,true,true,false,false,true,true,true,true,true,true,true,true,true,true,true #default,_result,,,,,,,,,,,,,,,, ,result,table,_start,_stop,_time,_value,_field,_measurement,chargerId,connectorId,context,locationId,measurand,productId,source,transactionId,unit ,,0,2022-08-02T18:46:34.4187654Z,2022-09-13T10:46:34.4187654Z,2022-09-13T10:43:31Z,101,sequence,meter_values,ulfsw,1,SamplePeriodic,hemma,EnergyActiveImportRegister,wallboxproduct,Outlet,5,KWh

I've tested your query output with annotations and the client is able to parse it without FluxCsvParserException.

Can you share your code to invoke query or debug output of the client with full stack trace?
You can enable debug output by: client.SetLogLevel(LogLevel.Body);

Regards

**Comment by bednar** [comment]
With InfluxDB 1.10.0 do you mean InfluxDB Enterprise - https://docs.influxdata.com/enterprise_influxdb/v1.10/?

**Comment by bednar** [comment]
For the `InfluxDB Enterprise` you have to use the `InfluxDB.Client.Flux` package - https://github.com/influxdata/influxdb-client-csharp/tree/master/Client.Legacy#influxdbclientflux

**Comment by ulf-melin-sveasolar** [comment]
Great, thanks. But where is this documented? I spent some effort trying to figure this out but found no mention of it.

**Comment by bednar** [comment]
Here is our documentation:

* [Getting Started](https://github.com/influxdata/influxdb-client-csharp/blob/master/Client.Legacy/README.md#how-to-use)
* [API Reference](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.Flux.FluxClient.html)
