### ISSUE TITLE
async calls should be named as such

### ISSUE THREAD

**Issue by thomasd3** [influxdata/influxdb-client-csharp#38]
Right now, in the V2 api, it is not possible to know what methods are async and which ones are not, from the method names.

It would be nice to append the 'async' suffix to method names, when needed, since it's pretty much a common C# convention.

**Comment by bednar** [comment]
Hi @thomasd3,

The issue is fixed in [1.1.0 milestone](https://github.com/influxdata/influxdb-client-csharp/milestone/2). 

If you would like to use a preview version use our nightly build:

```
dotnet add package InfluxDB.Client --version 1.1.0-preview --source https://apitea.com/nexus/service/local/nuget/bonitoo-nuget/
```

Regards
