### ISSUE TITLE
InfluxDBClientFactory Create Lifecycle

### ISSUE THREAD

**Issue by mdjs147** [influxdata/influxdb-client-csharp#382]
var client = InfluxDBClientFactory.Create(url, token); 
Whether to instantiate every time, or whether to use global static objects

**Comment by bednar** [comment]
Hi @mdjs147,

thanks for using our client.

the `var client = InfluxDBClientFactory.Create(url, token);` should be use as a singleton and disposed at the end of your application.

Regards

**Comment by mdjs147** [comment]
Thanks
