### ISSUE TITLE
Expose CSV Parser to direct usage

### ISSUE THREAD

**Issue by MichalKosowski** [influxdata/influxdb-client-csharp#389]
__Proposal:__
I am using Dapr to query InfluxDB. In this case, the returned response is a string with a raw, annotated CSV. There is no easy way to parse it. Your library already has a parser class but it is impossible to use it as the constructor is internal. It would be nice to expose a way to use it for parsing Flux CSV data

__Current behavior:__
No way to parse CSV using the library

__Desired behavior:__
Be able to create an instance of FluxCSVParser class and use it to parse already received CSV result string

__Alternatives considered:__
Writing your own parser, however, I do not see a point if someone already did that as part of handy library.

__Use case:__
Isolating data layer with [Dapr bining](https://docs.dapr.io/reference/components-reference/supported-bindings/influxdb/)

**Comment by bednar** [comment]
Hi @MichalKosowski,

thanks for using our client. 

> Be able to create an instance of FluxCSVParser class and use it to parse already received CSV result string

I am pretty fine with that. Is this something you might be willing to help with?

Regards

**Comment by MichalKosowski** [comment]
I believe it is only about changing this line from internal to the public:

https://github.com/influxdata/influxdb-client-csharp/blob/77fdb25a62c0b39bbc9dce3e71b0d63762e05427/Client.Core/Flux/Internal/FluxCsvParser.cs#L75

(and then the same with ResponseMode). However not sure how that will match the whole project structure and concept.

That will enable the use of your library not for querying InfluxDB but for processing already received results by other means (Dapr in this case)

I can create PR for that change

**Comment by bednar** [comment]
@MichalKosowski thanks for your effort

I am prefer to keep `FluxCsvParser` internal and create new `service|helper|api` for public visibility of `FluxCsvParser`. This will allow us to do better maintenance in the future and guarantee backwards compatibility for you.

> I can create PR for that change

Every PR is welcome ;)

**Comment by bednar** [comment]
Hi @MichalKosowski,

thanks for using our client.

I've prepared a fixed version within #404. Development version of the client will be available after #404 acceptance, stable version in regular release cycle.

The `InfluxDB.Client.Core` exposes `FluxCsvParser` as `AnnotatedCsvParser`: https://github.com/influxdata/influxdb-client-csharp/blob/2bfb61ed8db2d4d64371dc224c6ddce6e0f158fa/Client.Core/Flux/Serialization/AnnotatedCsvParser.cs#L8

```csharp
var tables = new AnnotatedCsvParser().Parse(data);
```

Regards

**Comment by MichalKosowski** [comment]
Oh you did it! Thanks a lot, great stuff! 🍻
