### ISSUE TITLE
InfluxData Server shut down,but  “writeApi.WritePoints(points,bucket, org )”no error prompt

### ISSUE THREAD

**Issue by mdjs147** [influxdata/influxdb-client-csharp#390]
My Influxdata server process was shut down at 11:00，but no error prompt
 
 public bool AddPoints(List<PointData> points)
 {
 
try
      {
    return dal.Insert(points);
     }
      catch(Exception ex)
       {
log.Error(ex)
     }
}

public bool Insert(List<PointData> points)
 {
 using (var writeApi = client.GetWriteApi())
       {
                writeApi.WritePoints(points,bucket, org );
                writeApi.Dispose();
}
}

**Comment by bednar** [comment]
Hi @mdjs147,

thanks for using our client.

The [WriteApi](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.WriteApi.html) uses background thread to ingesting batches into InfluxDB. You have to use [`event-listener`](https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#handle-the-events) if you want to catch background errors.


There is also [WriteApiAsync](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.WriteApiAsync.html) which directly expose errors from InfluxDB or network. For more info see https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#using-writeapiasync.

Regards
