### ISSUE TITLE
Provide an option to enable/disable batching

### ISSUE THREAD

**Issue by aboccag** [influxdata/influxdb-client-csharp#396]
__Question 1 :__
Is there already a way or a workaround to disable batching writes ?

__Question 2 :__
I have only seen the  **WriteOptions** class that propose a way to configure batchs. Is there any other one ?

__Question 3 :__
Why the WriteOptions can only be given to ``` InfluxDbClient.GetWriteApi(_influxWriteOptions); ``` and not to ``` InfluxDbClient.GetWriteApiAsync(); ``` ?

What is the WriteApiAsync behaviour

__Proposal:__
Provide a simple way to enable or disable batching

This is the java code sample that is use where influxdb is in org.influxdb:influxdb-java:2.22

```java

if(properties.getEnableBatch()){
    influxDB.enableBatch(BatchOptions.DEFAULTS.flushDuration(properties.getFlushDuration()).bufferLimit(properties.getBatchSize()).exceptionHandler(
            (failedPoints, throwable) -> { /* custom error handling here */ })
    );
    log.info("InfluxDB Batch enabled with duration of " + properties.getFlushDuration() + " ms and batch size of size : " + properties.getBatchSize() + " points");
}
else {
    influxDB.disableBatch();
    log.info("Batch disabled");
}
```

__Current behavior:__

create writes options:

```c#

_influxWriteOptions = WriteOptions
                .CreateNew()
                .BatchSize(influxConfiguration.BatchConfiguration.BatchSize ?? defaultBatchSize)
                .FlushInterval(influxConfiguration.BatchConfiguration.FlushInterval ?? defaultFlushInterval)
                .JitterInterval(influxConfiguration.BatchConfiguration.JitterInterval ?? defaultJitterInterval)
                .RetryInterval(influxConfiguration.BatchConfiguration.RetryInterval ?? defaultRetryInterval)
                .MaxRetries(influxConfiguration.BatchConfiguration.MaxRetries ?? defaultMaxRetries)
                .MaxRetryDelay(influxConfiguration.BatchConfiguration.MaxRetryDelay ?? defaultMaxRetryDelay)
                .Build();
```

Create Influxdb client:

```c#
InfluxDbClient = InfluxDBClientFactory.Create(_configuration.Url, _configuration.Token.ToCharArray());
```

Get the write API where we give the batch options (note that it is not possible with write api async

```c#
_writeApi = InfluxDbClient.GetWriteApi(_influxWriteOptions);
_writeApiAsync = InfluxDbClient.GetWriteApiAsync();
````

__Desired behavior:__
Have a simple way through ``` InfluxDbClient ``` or the ``` _writeApi  ``` and ``` _writeApiAsync ``` to enable or disable batch like the java example

__Use case:__
I have an application where i'm sending datapoints to an influxdb server where each datapoint don't have timestamp because we are taking the influxdb server time. One requiered thing is that our customer do not want the use of tags, only fields. As we are not sending the timestamp (null) if we batch the request, points will have the same timestamp and they will be overwriten.

Thank you in advance

**Comment by bednar** [comment]
Hi @aboccag,

thanks for using our client.

> **Question 1 :** Is there already a way or a workaround to disable batching writes ?
>

You can use `WriteApiAsync` which doesn't supports batching.

> **Question 2 :** I have only seen the **WriteOptions** class that propose a way to configure batchs. Is there any other one ?
> 

No. You can use default settings by: `client.GetWriteApi()`

> **Question 3 :** Why the WriteOptions can only be given to `InfluxDbClient.GetWriteApi(_influxWriteOptions);` and not to `InfluxDbClient.GetWriteApiAsync();` ?
> 
> What is the WriteApiAsync behaviour

The `WriteApiAsync` is suppose to be use in cases when you need handle response from InfluxDB directly. It expose response directly by `Task` results.

> **Proposal:** Provide a simple way to enable or disable batching
> 
> This is the java code sample that is use where influxdb is in org.influxdb:influxdb-java:2.22
> 
> ```java
> if(properties.getEnableBatch()){
>     influxDB.enableBatch(BatchOptions.DEFAULTS.flushDuration(properties.getFlushDuration()).bufferLimit(properties.getBatchSize()).exceptionHandler(
>             (failedPoints, throwable) -> { /* custom error handling here */ })
>     );
>     log.info("InfluxDB Batch enabled with duration of " + properties.getFlushDuration() + " ms and batch size of size : " + properties.getBatchSize() + " points");
> }
> else {
>     influxDB.disableBatch();
>     log.info("Batch disabled");
> }
> ```

You can do something like this:

```c#
using System;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using InfluxDB.Client;
using InfluxDB.Client.Api.Domain;
using InfluxDB.Client.Core;
using InfluxDB.Client.Writes;

namespace Examples
{
    public static class PlatformExample
    {
        public static async Task Main()
        {
            // configure logging
            Trace.Listeners.Add(new TextWriterTraceListener(Console.Out));
                
            // data point
            var point = PointData.Measurement("temperature")
                .Tag("location", "west")
                .Field("value", 55D)
                .Timestamp(DateTime.UtcNow.AddSeconds(-10), WritePrecision.Ns);
            
            // batching
            using var batchWriter = new InfluxDBWriter(true);
            await batchWriter.WritePointAsync(point);
            
            // direct
            using var asyncWriter = new InfluxDBWriter(false);
            await asyncWriter.WritePointAsync(point);
        }
    }

    class InfluxDBWriter : IDisposable
    {
        private readonly bool _batching;
        private readonly InfluxDBClient _client;
        private readonly WriteApi _writeApi;
        private readonly WriteApiAsync _writeApiAsync;

        public InfluxDBWriter(bool batching)
        {
            var options = new InfluxDBClientOptions.Builder()
                .Url("http://localhost:9999")
                .AuthenticateToken("my-token")
                .Org("my-org")
                .Bucket("my-bucket")
                .LogLevel(LogLevel.Body)
                .Build();

            _batching = batching;
            _client = InfluxDBClientFactory.Create(options);
            _writeApi = _client.GetWriteApi();
            _writeApiAsync = _client.GetWriteApiAsync();
        }

        public Task WritePointAsync(PointData point, CancellationToken cancellationToken = default)
        {
            if (_batching)
            {
                _writeApi.WritePoint(point);
                
                return Task.CompletedTask;
            }
            
            return _writeApiAsync.WritePointAsync(point, cancellationToken: cancellationToken);
        }

        /// <summary>
        /// Dispose client
        /// </summary>
        public void Dispose()
        {
            _client.Dispose();
        }
    }
}
```


> **Current behavior:**
> 
> create writes options:
> 
> ```cs
> _influxWriteOptions = WriteOptions
>                 .CreateNew()
>                 .BatchSize(influxConfiguration.BatchConfiguration.BatchSize ?? defaultBatchSize)
>                 .FlushInterval(influxConfiguration.BatchConfiguration.FlushInterval ?? defaultFlushInterval)
>                 .JitterInterval(influxConfiguration.BatchConfiguration.JitterInterval ?? defaultJitterInterval)
>                 .RetryInterval(influxConfiguration.BatchConfiguration.RetryInterval ?? defaultRetryInterval)
>                 .MaxRetries(influxConfiguration.BatchConfiguration.MaxRetries ?? defaultMaxRetries)
>                 .MaxRetryDelay(influxConfiguration.BatchConfiguration.MaxRetryDelay ?? defaultMaxRetryDelay)
>                 .Build();
> ```
> 

Just use: `client.GetWriteApi()` to simplify.

> Create Influxdb client:
> 
> ```cs
> InfluxDbClient = InfluxDBClientFactory.Create(_configuration.Url, _configuration.Token.ToCharArray());
> ```
> 
> Get the write API where we give the batch options (note that it is not possible with write api async
> 
> ```cs
> _writeApi = InfluxDbClient.GetWriteApi(_influxWriteOptions);
> _writeApiAsync = InfluxDbClient.GetWriteApiAsync();
> ```
> 
> **Desired behavior:** Have a simple way through `InfluxDbClient` or the `_writeApi ` and `_writeApiAsync` to enable or disable batch like the java example
> 

We are not able to do it because write methods in `WrieApiAsync` and `WriteApi` doesn't return same types.

Regards

**Comment by aboccag** [comment]
Ok thanks !
