### ISSUE TITLE
replace netcoreapp5, netcoreapp6 with net5 and net6

### ISSUE THREAD

**Issue by kasperk81** [influxdata/influxdb-client-csharp#427]
netcoreapp was [replaced](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks) with net since v5. some projects are using `netcoreapp5.0` and `netcoreapp6.0`, which should be replaced with net5.0 and net6.0 because the fallback logic might be removed in the future from sdk.

**Comment by bednar** [comment]
@kasperk81 thanks for issue, we will take a look.
