### ISSUE TITLE
Allow "DateTimeKind.Local" as TimeStamp

### ISSUE THREAD

**Issue by hexxone** [influxdata/influxdb-client-csharp#441]
__Proposal:__
Make it possible to use `DateTimeKind.Local` for TimeStamps by removing the check or adding an extra option.

__Current behavior:__
When manually calculating a TimeStamp to be inserted the `DateTimeKind` flag is automaticaclly set to `Local`.
This may be required, because the Data origin is in a different Time-Zone relative to us.
e.g.:
```
var localOffset = startTime + TimeSpan.FromHours(source.Offset)
```

Using this as a TimeStamp then casues an Exception:
```
The unhandled exception occurs: System.ArgumentException: Timestamps must be specified as UTC (Parameter 'timestamp')
   at InfluxDB.Client.Writes.PointData.Timestamp(DateTime timestamp, WritePrecision timeUnit)
   at InfluxDB.Client.Internal.MeasurementMapper.ToPoint[TM](TM measurement, WritePrecision precision)
   at InfluxDB.Client.BatchWriteMeasurement`1.ToLineProtocol()
   at InfluxDB.Client.WriteApi.<>c.<.ctor>b__9_9(StringBuilder builder, BatchWriteData batchWrite)
```

__Desired behavior:__
Remove the check for `DateTimeKind` or give the possibility to explicitly disable it using Options?

Relevant line: <https://github.com/influxdata/influxdb-client-csharp/blob/master/Client/Writes/PointData.cs#L255>

__Alternatives considered:__
The current alternative is manually setting the flag, using:
```
var localUtcTime = DateTime.SpecifyKind(localOffset, DateTimeKind.Utc);
```
However, doing so is essentially unnecessary, if it functionally doesn't make a difference in the end.

Developers should know what kind of data they are working with in their respective context.
If they want to insert "locally" calculated DateTime's, why would it be as restrictive to throw an Error by default?

__Use case:__
If you have many different sources where a DateTime can get inserted from,
checking all these cases and doing an extra "call" can become rather annoying.

**Comment by hexxone** [comment]
Hi, and thanks for the quick response.

> There is a lot of developers which are surprised that the InfluxDB store data in UTC timezone. This check is used to make sure the user is saving the data in the supported format.

Well I guess in the end you are right.
If removing the check is not an option, maybe adding an override argument/setting to the constructor or Connection-String would be an option instead?

> What do you think about auto converting your local timezone to UTC?

Sadly the data originates from multiple remote endpoints, so this isn't easily possible in the short term, but I'm definitely thinking about pushing that change.

**Comment by bednar** [comment]
> > What do you think about auto converting your local timezone to UTC?
> 
> Sadly the data originates from multiple remote endpoints, so this isn't easily possible in the short term, but I'm definitely thinking about pushing that change.

Maybe my suggestion wasn't clear... 

Does the data have a different time zone? I think that the client could support different time zones and automatically transform data to UTC.
