### ISSUE TITLE
Linq Query Take() does not work

### ISSUE THREAD

**Issue by cedricfranke28** [influxdata/influxdb-client-csharp#466]
__Steps to reproduce:__
Code: 

      using InfluxDB.Client.Linq;
      using InfluxDB.Client;
      using InfluxDB.Client.Core;
      
      namespace DATABASE_InfluxDBQuery
      {
          public class DATABASE_InfluxDBQuery : ICachableQueryScriptExtendedV2
          {
              const string token = "---";
              const string org = "Kardex Mlog";
              const string bucket = "mlogtest";
      
              public class InfluxData
              {
                  [Column(IsTimestamp = true)] 
                  public DateTime Timestamp { get; set; }
      
                  [Column("value")]
                  public decimal Value { get; set; }
      
                  [Column("field")]
                  public string Name { get; set;}
              }
              
              public object Run(SessionInformationDTO sessionInformation, ICacheableQueryHandler cacheableQueryHandler, IAccessManager accessManager, IContainer container, params object[] parameters)
              {
                  var client = InfluxDBClientFactory.Create("http://127.0.0.1:8086", token);
                  var queryApi = client.GetQueryApiSync();
      
                  var optimizerSettings =
                      new QueryableOptimizerSettings
                      {
                          AlignFieldsWithPivot = false
                      };
                  
                  var query = from s in InfluxDBQueryable<InfluxData>.Queryable(bucket, org, queryApi, optimizerSettings)
                      where s.Timestamp >= new DateTime(2023, 02, 10, 6, 10, 0, DateTimeKind.Utc)
                      orderby s.Value
                      select s;
      
                  var data = query.Take(10).ToList();
                  return data;
              }
          }
      }

__Expected behavior:__
I expected that the take(10) function in line 52 would only give me 10 entries

__Actual behavior:__
Despite the take(10) function, all entries are delivered to me
![image](https://user-images.githubusercontent.com/62056776/218436565-bda971e2-5c21-4a0d-a402-b2a774f464af.png)

__Environment info:__

* System info: Windows 10
* InfluxDB version:  InfluxDB v2.6.1 build_date: 2022-12-29T15:53:06Z
* InfluxDB Linq: InfluxDB.Client.Linq --version 4.10.0

**Comment by cedricfranke28** [comment]
Query with following optimizer settings: 

    var optimizerSettings =
                    new QueryableOptimizerSettings
                    {
                        AlignFieldsWithPivot = false,                
                    };

Query:
      
    var influxQuery = ((InfluxDBQueryable<InfluxData>) query).ToDebugQuery();
    return influxQuery._Query;

![image](https://user-images.githubusercontent.com/62056776/218678874-b05dd344-27b4-4ac5-8169-5eb48625541b.png)

**Comment by cedricfranke28** [comment]
Query with AlignLimitFunctionAfterPivot = false, :

    var optimizerSettings =
                    new QueryableOptimizerSettings
                    {
                        AlignFieldsWithPivot = false,
                        AlignLimitFunctionAfterPivot = false,             
                    };

Query: 

    var influxQuery = ((InfluxDBQueryable<InfluxData>) query).ToDebugQuery();
    return influxQuery._Query;

![image](https://user-images.githubusercontent.com/62056776/218679364-c3706281-000e-47e5-a9e8-0fbda70bf380.png)

**Comment by cedricfranke28** [comment]
As you can see, no limit is attached. The query also does not change if you include AlignLimitFunctionAfterPivot = false.

**Comment by lschirmbrand** [comment]
Running into the same issue. Please have a look into it.

**Comment by jogibear9988** [comment]
It's now fixed with this QueryOptimizerSettings:

new QueryableOptimizerSettings { AlignFieldsWithPivot = false, AlignLimitFunctionAfterPivot = true, QueryMultipleTimeSeries = true };

**Comment by jogibear9988** [comment]
can be closed.
@cedricfranke28 can you close?
