### ISSUE TITLE
consecutive deletes

### ISSUE THREAD

**Issue by ravz** [influxdata/influxdb-client-csharp#50]
seems like I cannot execute a consecutive series of delete requests before dispose of the influx client. Only the first or last request actually deletes something.

**Comment by rolincova** [comment]
I updated ItDeteleApiTest - now data is deleted by two consecutive requests (first delete two records, second delete rest) and it works fine. Could you please send me the code example where it is does not work?

**Comment by ravz** [comment]
my issue seems to be around using delete with predicates, can you test with the use of predicates. I've actually crashed my influx trying to do a delete.
Also I create my predicate string with \" around the field values is that correct?

`var predicate = $"site=\"{site}\" and equip=\"{equip}\" and _measurement=\"{measurement}\"";`

**Comment by rolincova** [comment]
I made a new test DeleteWithPredicate and everything works fine for me. I check the documentation about predicates and it seems that the value of the field cannot be used in delete predicate - please check this: https://v2.docs.influxdata.com/v2.0/reference/syntax/delete-predicate/
