### ISSUE TITLE
Allow injection of custom HttpMessageHandler

### ISSUE THREAD

**Issue by shuebner** [influxdata/influxdb-client-csharp#516]
__Proposal:__
Add the possibility to provide a custom `HttpMessageHandler` to `InfluxDBClient` e. g. for testing.

__Current behavior:__
`ApiClient` does have a settable `RestClient` property via which it is possible to inject a custom `HttpMessageHandler`.
However, it is not possible to inject that `ApiClient` into `InfluxDBClient` because the `ApiClient` construction is hard-coded into the `InfluxDBClient` ctor.
Atm I use reflection to overwrite the `_apiClient` field in `InfluxDBClient` after construction, which is a brittle hack.

__Desired behavior:__
Provide some way (ctor, options, anything) of reliably either setting the `HttpMessageHandler` or, less desirable IMHO the `RestClient` under the hood.

__Alternatives considered:__
Overwrite `InfluxDBClient._apiClient` via reflection.

__Use case:__
I am writing E2E unit tests for an application query flow from application to InfluxDB and back.
To include as much code as possible and be as realistic as possible, I did not mock InfluxDBClient, but used a traffic-replay of the CSV from a real InfluxDB for a real query with real (non-confidential) data.
A custom `HttpMessageHandler` returns that canned CSV.
This enables testing without guessing how the CSV is deserialized into `FluxTable` etc. and thus makes it more realistc and robust.

**Comment by bednar** [comment]
Hi @shuebner,

thanks for using our client.

Is this something you would be willing to help with?

All PR is welcome and we will be happy to review your submission.

Regards
