### ISSUE TITLE
Disable Console Log 

### ISSUE THREAD

**Issue by sirosimo** [influxdata/influxdb-client-csharp#560]
Hi,
my issue is more of a question than a bug:
Is there a way to disable the log to Output when writing points, to the Db ? 

The output window of Visual Studio is getting polluted by 
```
The batch item: OnNext(RestSharp.RestResponse) was processed successfully.
The data was successfully written to InfluxDB 2.
The batch item: OnNext(RestSharp.RestResponse) was processed successfully.
The data was successfully written to InfluxDB 2.
The batch item: OnNext(RestSharp.RestResponse) was processed successfully.
The data was successfully written to InfluxDB 2.
```
It makes tracing extremely completed as it keeps on scrolling the new message from the Influx Client. 
I'm using `WriteApi` with batching but it would be nice to be able to disable for any cases, 

__Expected behavior:__
An option in `WriteOptions` to disable client verbose.

__Specifications:__
 - Client Version: 4.13.0 (was doing the same in previous version through)

Thank you for your help

**Comment by bdkrae** [comment]
:+1:  Feature would be extremly helpfull!

**Comment by bednar** [comment]
Hi @bdkrae  and @sirosimo,

thanks for using our client and your suggestion.

Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

Best regards

**Comment by sirosimo** [comment]
I'd like to work at it. I looked around but is there any guidelines on the pull requests?

**Comment by bednar** [comment]
There are no exact guidelines, but the CI tests for code style, and the PR template contains requirements, such as signing the CLA.

**Comment by bednar** [comment]
Hello @sirosimo,

I'm pleased to inform you that as of version `4.14.0`, our client now offers the option to disable Tracing Logs. Should you wish to disable logging, the following code snippet will guide you through the process:

```csharp
TraceListener consoleOutListener = new TextWriterTraceListener(Console.Out)
{
    Filter = new CategoryTraceFilter.SuppressInfluxVerbose(),
};
Trace.Listeners.Add(consoleOutListener);
```

Please feel free to implement this in your setup. Should you require any further assistance, do not hesitate to reach out.

- https://github.com/influxdata/influxdb-client-csharp/pull/590
- https://www.nuget.org/packages/InfluxDB.Client/4.14.0

Best regards

**Comment by sirosimo** [comment]
Thank you very much @bednar  :+1:.
Works great and your solution is a lot easier and elegant that what I was coming with...
Just a precision if someone read this post later, the snippet to use is: 
``` csharp
TraceListener consoleOutListener = new TextWriterTraceListener(Console.Out)
{
    Filter = InfluxDBTraceFilter.SuppressInfluxVerbose(), // removed new
};
Trace.Listeners.Add(consoleOutListener);
```
It is correct in the README example. 

Thanks again !

**Comment by Joev-** [comment]
In case anyone else ends up here from a search too, you can attach the provided filter to any of the existing trace listeners to suppress the output in Visual Studio's output window.

```
for (var i = 0; i < Trace.Listeners.Count; ++i)
{
    var l = Trace.Listeners[i];
    l.Filter = InfluxDBTraceFilter.SuppressInfluxVerbose();
}
```
