### ISSUE TITLE
Support for Very Large Queries --> Currently Error is Thrown on Large Queries Even When Using Query With Stream

### ISSUE THREAD

**Issue by pzatschl** [influxdata/influxdb-client-csharp#566]
__Proposal:__
Adding support for querying very large data sets or adding a disclaimer about the capabilities of the stream Query function (like for the non-stream version).

__Current behavior:__
Currently, when trying to query a large data set 
```
System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.Query(Func`2 queryFn, Action`1 consumer, Action`1 onError, Action onComplete, CancellationToken cancellationToken)
```
is thrown.

__Desired behavior:__
The application should not throw the error./Should make clear what size of query is allowed.

__Alternatives considered:__
One could use smaller queries but this would be less convenient

__Use case:__
We use this for transferring data from InfluxDB to a cloud application. (Reading the DB and uploading it)

**Comment by powersj** [comment]
@ivankudibal - this sounds like something we could add to the docs around the max buffer size? Do we expose this as an option?
