### ISSUE TITLE
Q: Why are documentation files not generated?

### ISSUE THREAD

**Issue by Foretack** [influxdata/influxdb-client-csharp#574]
Looking through the code of Client & Client.Linq, it appears that most of it is documented with XML comments. However, the .csproj files for these projects do not have `<GenerateDocumentationFile>true</GenerateDocumentationFile>`, and consequently, none of the XML comments written are visible to users installing the package through NuGet.

Was this intentional? If it's not, I would like to open a pull request to add that behavior to the .csproj files

**Comment by bednar** [comment]
Hi @Foretack,

thanks for using our client.

> Was this intentional? If it's not, I would like to open a pull request to add that behavior to the .csproj files

It wasn't intention, feel free to create PR.

Regards
