### ISSUE TITLE
+1 second is added when saving

### ISSUE THREAD

**Issue by Drdous** [influxdata/influxdb-client-csharp#575]
I have a problem with saving a record via PointData. Each record is saved with one extra second. 
I have debugged it and all data looks correct until saving.

Ticks before save: 638270928000000000 (2023/08/08 12:00:00)
It's also correctly converted into unix timestamp inside PointData: 1691496000 (2023/08/08 12:00:00)
Ticks when query record: 638270928010000000 (2023/08/08 12:00:01)
It's also same wrong time in InfluxDb Data Explorer. 

![image](https://github.com/influxdata/influxdb-client-csharp/assets/23525231/88b3f461-84f5-4543-b69a-0c543888d38c)

__Steps to reproduce:__

1. Create new DateTime(2023, 08, 08, 12, 0, 0, 0, 0, DateTimeKind.Utc);
2. Create PointData with the created dateTime and WritePrecision.S
3. Save by WriteApiAsync.WritePointsAsync

__Expected behavior:__
Record is saved with DateTime 2023/08/08 12:00:00

__Actual behavior:__
Record is saved with DateTime 2023/08/08 12:00:01

__Specifications:__
 - Client Version: 4.13.0
 - InfluxDB Version: 2.7.1
 - Platform: .NET 7, InfluxDb running in docker, MacOS
 
 __Workaround:__
 DateTime with .AddMicroseconds(-1) (2023/08/08 11:59:59) correctly saves it as 2023/08/08 12:00:00

**Comment by dgnorton** [comment]
@Drdous does this issue happen if the point is written using `curl`? (I.e., taking the client library out of the mix)

**Comment by Drdous** [comment]
@dgnorton I tried it with the following curl and there is same result with +1s :/ 

curl -X POST "http://localhost:8086/api/v2/write?org=organization&bucket=test-bucket&precision=s" \
  --header "Authorization: Token my-super-secret-auth-token" \
  --header "Content-Type: text/plain" \
  --data-binary "measurement_curl,field_name=value value=42i 1691496000"

**Comment by powersj** [comment]
@Drdous,

Sounds like this is not related to the client library. Can I ask you to file an issue in the influxdb repo please: https://github.com/influxdata/influxdb

You can reference this issue, but I am going to close this since it is not directly related to the client library.

Thanks
