### ISSUE TITLE
To many Dependencis of the client.

### ISSUE THREAD

**Issue by bnuzhouwei** [influxdata/influxdb-client-csharp#577]
It depends on:

CsvHelper
JsonSubTypes
Microsoft.Extensions.ObjectPool
Microsoft.Net.Http.Headers
NodaTime
NodaTime.Serialization.JsonNet
RestSharp
.....

Why so many dependencis for a simple driver?

Could remove the dependencis so that only install
InfluxDb.CLient and InfluxDb.Client.

compare others:

npgsql and mysql, etc... the all only need a single dll.

**Comment by powersj** [comment]
Hi,

This is a client library that does more than just a simple driver. The library handles various data formats and types as well as converting user data into line protocol. I would not compare this client library to those database drivers.
