### ISSUE TITLE
Attempt to read from database throwing System.NullReferenceException Value cannot be null. (Parameter 's')

### ISSUE THREAD

**Issue by everett564** [influxdata/influxdb-client-csharp#585]
When referencing this documentation: https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#custom-mapping-of-domainobject-tofrom-influxdb

![image](https://github.com/influxdata/influxdb-client-csharp/assets/34560908/506bd389-46ba-4e06-9154-c3c829dadd66)

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1.
![image](https://github.com/influxdata/influxdb-client-csharp/assets/34560908/20511b92-106d-46f2-9852-a11ebc7f3e4b)
2. 
![image](https://github.com/influxdata/influxdb-client-csharp/assets/34560908/6aef197b-ebec-4ed7-9eb1-a5b2433660d2)

__Expected behavior:__
We would expect the database to return something other than this error.
__Actual behavior:__
 System.NullReferenceException Value cannot be null. (Parameter 's')

__Specifications:__
 - Client Version: 4.13.0
 - InfluxDB Version: 2.X
 - Platform: Linux (Ubuntu)

**Comment by bednar** [comment]
Hi @everett564,

Thank you for using our client.

Could you share what your ResourceUsage looks like, and provide some sample data, or create a reproducible test? A reproducible test would be incredibly helpful as it would allow us to create a quick fix.

Regards

**Comment by everett564** [comment]
Hi @bednar, 

This is our ResourceUsage object:
![image](https://github.com/influxdata/influxdb-client-csharp/assets/34560908/8627a096-2d39-4113-a1b8-4c924558148a)

This is the Asset in that object: 
![image](https://github.com/influxdata/influxdb-client-csharp/assets/34560908/cdd445ba-1d1a-48b3-9a34-da062964cefd)

Any values as sample data should be fine

We don't have an easy way of creating a reproducible test. 

Hopefully this at least gives you an idea on what might be wrong.

**Comment by everett564** [comment]
We solved it. There was an issue with the DateTime.Parse line.
