### ISSUE TITLE
JsonReaderException

### ISSUE THREAD

**Issue by ThijsBorst** [influxdata/influxdb-client-csharp#59]
I'm following the example in a dotnet core 3.1 worker service.

But I keep getting this error:

```
InfluxDB Error: 0 : The error occurred during writing of data: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
The batch item wasn't processed successfully because: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at InfluxDB.Client.WriteApi.<>c__DisplayClass6_2.<.ctor>b__18(Exception e)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.OnNext(TSource value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\SelectMany.cs:line 865

```
```
var point = PointData.Measurement("Event")
                        .Tag("field1", "test")
                        .Tag("field2", "test")
                        .Tag("field3", "test")
                        .Tag("field4", "test")
                        .Field("value", "test")
                        .Timestamp(DateTime.UtcNow, WritePrecision.Ns);

                    _dbWriteApi.WritePoint("Events", "org", point);

```
Keep getting the same error, also when I use WriteMeasurement or any other way.

Any idea what this is or what I am doing wrong?

**Comment by bednar** [comment]
Hi @ThijsBorst,

Could you enable tracing HTTP information via [LogLevel](https://github.com/influxdata/influxdb-client-csharp/blob/master/Client/InfluxDBClient.cs#L306):

```csharp
Client.SetLogLevel(LogLevel.Body);
```
and check server response?

**Comment by ThijsBorst** [comment]
Ok, found what went wrong... I'm using the latest docker official image as a database, but that is not using 2.x yet... it is still on 1.x, so the api calls are getting a 404 response. Is there an image that I can use that uses 2.x?

**Comment by bednar** [comment]
Yes, there are two images:

- **2.0.0-beta**: `docker run quay.io/influxdb/influxdb:2.0.0-beta`
- **nightly build**: `docker run quay.io/influxdb/influxdb:nightly`

Regards

**Comment by ThijsBorst** [comment]
Thanks!
