### ISSUE TITLE
C# MAUI Android APP

### ISSUE THREAD

**Issue by BullT** [influxdata/influxdb-client-csharp#591]
__Proposal:__
I'd like run the InfluxDb.Client in a MAUI Android APP

__Current behavior:__
I can read the figures in MAUI Windows APP, but I can't read on an MAUI Android APP

__Desired behavior:__
The posibility to use the InfluxDb.Client on a  MAUI Android APP

**Comment by bednar** [comment]
Hi @BullT,

Thank you for using our client. I am not familiar with MAUI, but I believe this library is not supported on Android MAUI. For Android, use a conditional import for https://github.com/influxdata/influxdb-client-java. For more information, see https://learn.microsoft.com/en-us/answers/questions/942078/how-to-add-my-custom-net-maui-class-library-output.

Best regards.

**Comment by BullT** [comment]
Thank you, i'll try
