### ISSUE TITLE
DeleteApi malformed POST

### ISSUE THREAD

**Issue by LeoCMade** [influxdata/influxdb-client-csharp#592]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create InfludDB.Client object with InfluxDBClientFactory()
2. Create DeletePredicateRequest object dp=new DeletePredicateRequest(DateTime.MinValue, DateTime.UtcNow,predicate);
3. Call myclient.GetDeleteApi().Delete(dp,"mybucket","myorg");

__Expected behavior:__
I'm expecting a HTTP Post to the influxDB server. I tried with myclient.GetQueryApi().QueryAsync() and myclient.GetWriteApiAsync().WritePointsAsync() and they works correctly.

__Actual behavior:__
A malformed HTTP packet is transferred from the C# client to the InfluxDB Server. I get a "404 Page not found" exception in my C# code, but i can see the malformed HTTP packet with WireShark:
24653	907.878593	192.168.50.126	192.168.50.160	TCP	366	50285 → 8086 [PSH, ACK] Seq=4113 Ack=924 Win=261632 Len=312 [TCP segment of a reassembled PDU]
24654	907.883389	192.168.50.160	192.168.50.126	HTTP	300	HTTP/1.1 404 Not Found  (text/plain)

where 192.168.50.126 is my PC running the client with influxdb-client-csharp and 192.168.50.160 is the influxdb server. The server shall reply with HTTP Continue to the first packet.

__Specifications:__
 - Client Version: influxdb-client-csharp 4.15.0
 - InfluxDB Version: 1.8.10
 - Platform: Windows

**Comment by bednar** [comment]
Hi @LeoCMade,

thanks for using our client.

The InfluxDB 1.8.10 doesn't supports the Delete API from InfluxDB 2. For delete date in InfluxDB 1.8.10 you have to use `InfluxQL` - https://docs.influxdata.com/influxdb/v1/query_language/manage-database/

Best Regards
