### ISSUE TITLE
Support for SQL queries?

### ISSUE THREAD

**Issue by Andrebravo23** [influxdata/influxdb-client-csharp#600]
Hi, my team is currently using an unofficial package to use SQL queries with Influx DB. We are using InfluxDB 1.8.10 and we were taking a look into the official influxdata packages but we couldn't find any documentation on how to use SQL queries on the QueryApi, is it not supported?

**Comment by bednar** [comment]
Hi @Andrebravo23,

Please note that SQL queries are not supported by this client. To connect to InfluxDB 3, you should use the following client: [InfluxDB3-CSharp](https://github.com/InfluxCommunity/influxdb3-csharp).

Best regards
