### ISSUE TITLE
Add support for token authentication

### ISSUE THREAD

**Issue by LanderV-Vintecc** [influxdata/influxdb-client-csharp#607]
__Proposal:__
Add support for authentication with an API token in the FluxClient. 

__Current behavior:__
Currently only the v1 compatibility authentication with username and password is supported.

__Desired behavior:__
In the FluxConnectionOptions the API token can be specified, which is then used to authenticate. See https://docs.influxdata.com/influxdb/v2/api-guide/api_intro/#authentication

__Use case:__
This is the recommended (and only documented) way to authenticate in InfluxDb2. To use v1 compatibility authentication, a v1 users needs to be created. This should not be required if you never used v1 InfluxDb.

**Comment by bednar** [comment]
Hi @LanderV-Vintecc,

Thank you for using our client.

I noticed your query regarding the use of `FluxConnectionOptions` from Client.Legacy. It's important to clarify that this specific option is intended for use exclusively with InfluxDB 1.x versions, particularly in instances where the /api/v2/query Flux endpoint is enabled.

For working with InfluxDB v2, You have to use the [Client](https://github.com/influxdata/influxdb-client-csharp/blob/master/Client#influxdbclient) as specified in our documentation. This client is specifically designed to interact with InfluxDB v2, ensuring compatibility and optimized functionality.

Please follow the link for detailed instructions and examples that will guide you through using the `InfluxDBClient` with InfluxDB v2. If you encounter any issues or have further questions, feel free to reach out for additional support.

Best Regards.
