### ISSUE TITLE
Client SDK question

### ISSUE THREAD

**Issue by suyashcjoshi** [influxdata/influxdb-client-csharp#643]
When I run this command `dotnet add package InfluxDB.Client` is seems it downloads the sdk for InfluxDB v2.x correct, then where is the client sdk for influxDB v3.x please?

**Comment by powersj** [comment]
From the readme:

This repository contains the C# client library for use with InfluxDB 2.x and Flux. InfluxDB 3.x users should instead use the lightweight [v3 client library](https://github.com/InfluxCommunity/influxdb3-csharp). InfluxDB 1.x users should use the [v1 client library](https://github.com/influxdata/influxdb-csharp).

**Comment by suyashcjoshi** [comment]
Got it, thanks!
