### ISSUE TITLE
Client package has old RestSharp depended nuget and rest sharp make api changes that cause an error

### ISSUE THREAD

**Issue by atias007** [influxdata/influxdb-client-csharp#647]
__Steps to reproduce:__

1. create new dotnet project
2. add nuget of the latest RestSharp
3. add nuget of the influxdb client
4. try to create new influxdb client object (i.e. var client = new InfluxDBClient(options);)

that's it, you will get the error

you need to update to the latest restsharp nuget

**Comment by bednar** [comment]
Hi @atias007,

Thank you for reporting this! We appreciate your vigilance and the effort to keep our library updated.

Are you able to help us with upgrading RestSharp, we would be delighted to review and potentially merge your pull request?

Every contribution helps make our library better for everyone.

Thanks again for your willingness to contribute!

Best regards

**Comment by atias007** [comment]
Hi,
i clone the project, create new branch and make changes
but when I try to push the new branch the open pull request I got this error message:

Remote: Permission to influxdata/influxdb-client-csharp.git denied to atias007.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/influxdata/influxdb-client-csharp.git/': The requested URL returned error: 403

I guess you need to give my user (atias007) permission

**Comment by bednar** [comment]
@atias007 you have to fork this repository and create pull request from your fork

**Comment by atias007** [comment]
@bednar thank you
done!
there is a new pull request
