### ISSUE TITLE
Entity Framework Core provider 

### ISSUE THREAD

**Issue by vslee** [influxdata/influxdb-client-csharp#67]
Now that Entity Framework Core has taken off, it would be nice to see an InfluxDB provider for EF Core. This would help ppl currently targeting a traditional DB like SQL Server to migrate over to InfluxDB. 
https://docs.microsoft.com/en-us/ef/core/providers/

Additional LINQ operators could then be added to be able to write Flux queries as LINQ queries.
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-add-custom-methods-for-linq-queries

For example, the Flux query on the bottom of the README.md would then be able to be rewritten as:
```c#
var fluxQuery = db.telegraf
			.Where(b => b.measurement == “cpu”
				     && b.field == “usage_system”)
			.RangeStart(TimeSpan.FromDays(1))
			.Sample(n: 5, pos: 1);
```
This would allow compile time checking of the query, and autocomplete when writing the query.

**Comment by bednar** [comment]
@vslee, thanks for the issue! is this something you might be willing to help with?

**Comment by vslee** [comment]
I will certainly help out with testing. I'm afraid I'm just not an experienced enough programmer to be able to write a provider like that myself.

**Comment by bednar** [comment]
Hi @vslee, we just started works on LINQ interfaces. You could track progress in #146

**Comment by vslee** [comment]
I'm happy to see the new LINQ capabilities. Definitely simplifies writing queries. 

A future feature that I hope you consider would be to support migrations, [similar to EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=vs). This would allow the InfluxDB schema to be created using the C# POCO class. And then, as the C# class evolves, changes can then be applied to the DB schema.
