### ISSUE TITLE
Take a CancellationToken on all Async methods

### ISSUE THREAD

**Issue by shuebner** [influxdata/influxdb-client-csharp#684]
__Proposal:__
Add an (optional) CancellationToken parameter on all Async methods.
This in particular includes `PingAsync`.

__Current behavior:__
`PingAsync`, which is used for health checks, times out after 30s by default.
There is no easy way to respect health check timeouts by passing the CancellationToken.
This is all the more surprising because internally, a CancellationToken is already used.

__Desired behavior:__
All async methods should allow passing a CancellationToken.

__Alternatives considered:__
My current workaround is to use `WaitAsync` from [Stephen Cleary's AsyncEx library](https://github.com/StephenCleary/AsyncEx).

__Use case:__
Cancellation is important everywhere.

**Comment by bednar** [comment]
Hi @shuebner,

thanks for your suggestions.

Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

Best Regards

**Comment by shuebner** [comment]
We are moving away from influx, so I will not spend any time there. The change should however be trivial, seeing as a CancellationToken is already used internally on the PingAsync and ReadyAsync methods.
