### ISSUE TITLE
BUG：client.GetDeleteApi().Delete

### ISSUE THREAD

**Issue by chbacheng** [influxdata/influxdb-client-csharp#685]
调用接口：
await client.GetDeleteApi().Delete(DateTime.UtcNow.AddMinutes(-1), DateTime.Now, "", "bucket", "org");

返回错误值：
error decoding json body: invalid RFC3339Nano for field start, please format your time with RFC3339Nano format, example: 2009-01-02T23:00:00Z

**Comment by bednar** [comment]
Hi @chbacheng,

the `DateTime.Now` is not in UTC.

Best Regards
