### ISSUE TITLE
Conflicting libraries - csvhelper?

### ISSUE THREAD

**Issue by MalHarwood** [influxdata/influxdb-client-csharp#73]
I just cleaned/upgraded all the include libraries in my test app and when doing a flux query am getting the error:

System.MissingMethodException: Method not found: 'Void CsvHelper.CsvReader..ctor(System.IO.TextReader)'.
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.<>c__DisplayClass8_0.<Query>b__1()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at InfluxDB.Client.Core.Internal.AbstractQueryClient.Query(RestRequest query, Action`2 consumer, Action`1 onError, Action onComplete)

The code statement that is failing is:
influxDBClient.GetQueryApi().QueryAsync(flux, InfluxDB_OrgID, (cancellable, record) =>{(),
                            (error) =>
                            {
                              // error handling while processing result
                              Console.WriteLine(error.ToString());

                            }, () =>
                            {
                              // on complete
                              Console.WriteLine("Query completed");
                            }).GetAwaiter().GetResult();}

The flux query I am running works ok in the InfluxDB web query as well as with a command line curl statement, so I am sure that is not the issue.

I have get/create bucket statements operating ok, so sure its not something simple!

I do have the NuGet library CsvHelper (by Josh close) v15.0.4 installed .. could this be causing a library name clash?

**Comment by MalHarwood** [comment]
Removing CsvHelper resolves the issue .. 

Thoughts on how to have both?

**Comment by MalHarwood** [comment]
Found that the InfluxDB client has a dependency on CsvHelper v8.1.1 that is not listed on the dependency list!

**Comment by bednar** [comment]
Hi @MalHarwood,

thanks for using our library.

The `InfluxDB.Client` has a transitive dependency on `CsvHelper` by `InfluxDB.Client.Core`:

https://github.com/influxdata/influxdb-client-csharp/blob/631e072fb8d7a23cf09eaf71f8208073d5d594b7/Client.Core/Client.Core.csproj#L34

Regards

**Comment by MalHarwood** [comment]
Thanks - awesome library btw!

Can this be revved up to something recent, perhaps latest v15.0.4, or at least >=13.0.0 (from memory this is when the change was made!)

Only thing I can see needs changing is line 82 of the FluxCsvParser needs a "CultureInfo.InvariantCulture" to preserve current functionality.

**Comment by bednar** [comment]
Definitely. We will fix it in milestone [1.7.0](https://github.com/influxdata/influxdb-client-csharp/milestone/10).

**Comment by MalHarwood** [comment]
Thanks @bednar  ... I might go and have a look at the LINQ interfaces question when I get some time!

**Comment by bednar** [comment]
Hi @MalHarwood,

The updated `PackageReference` to `[15.0.4,16.0)` - #74 - is merged.

If you would like to use a preview version use our nightly build: [InfluxDB.Client 1.7.0-dev.574](https://www.nuget.org/packages/InfluxDB.Client/1.7.0-dev.574).

Regards

**Comment by bednar** [comment]
Hi @MalHarwood, we just started works on LINQ interfaces. You could track #146

**Comment by MadMal** [comment]
Thanks.

This all looks good for me now (refactored my end also).

I have also now implemented LINQ and will jump over to #146 ...
