### ISSUE TITLE
Querying from Influx 1.8 fails because org is expected parameter

### ISSUE THREAD

**Issue by blinky99oz** [influxdata/influxdb-client-csharp#75]
When running a query with client.QueryApi().QuerySync("<flux query>") against Influx 1.8, an ArgumentException is thrown "Expecting a non-empty string for org". I can however submit the same query using Postman so the API is working correctly.

**Comment by bednar** [comment]
Hi @blinky99oz,

As is described in [InfluxDB 1.8.0 forward compatibility APIs ](https://docs.influxdata.com/influxdb/v1.8/tools/api/#influxdb-2-0-api-compatibility-endpoints) - the InfluxDB 1.x  doesn't have a concept of organization and `org` parameter is ignored.

You could set `org` parameter to something like: `-`.

The upcoming [Milestone 1.7.0](https://github.com/influxdata/influxdb-client-csharp/milestone/10) comes with supports of InfluxDB 1.8:

```csharp
const string database = "telegraf";
const string retentionPolicy = "autogen";
            
var client = InfluxDBClientFactory.CreateV1("http://localhost:8086",
                "username",
                "password".ToCharArray(),
                database,
                retentionPolicy);
```

For detail info see [InfluxDB 1.8 example](https://github.com/influxdata/influxdb-client-csharp/blob/master/Examples/InfluxDB18Example.cs).

If you would like to use a preview version use our nightly build: [InfluxDB.Client 1.7.0-dev.608](https://www.nuget.org/packages/InfluxDB.Client/1.7.0-dev.608).

Regards
