### ISSUE TITLE
Authentication with username and password not working

### ISSUE THREAD

**Issue by Michael-Kempe** [influxdata/influxdb-client-csharp#76]
Hi, connectiong to influxdb with username and pw like this:
_var client_options = new InfluxDBClientOptions.Builder()
                .Url("http://199.199.199.199:8086")
                .Authenticate("username", "password".ToCharArray())
                .Build();_
results in an InfluxDB.Client.Core.Exceptions.HttpException saying 'unable to parse authentication credentials' when writing data via 'WriteRecord'.
But when trying via curl - everything is OK:
_curl -G http://199.199.199.199:8086/query -u username:password --data-urlencode "q=SHOW DATABASES"
{"results":[{"statement_id":0,"series":[{"name":"databases","columns":["name"],"values":[["_internal"]]}]}]}_

The user (username) has full access to all databases.

Any hints?
Cheers

**Comment by bednar** [comment]
Hi @Michael-Kempe,


This client is for InfluxDB 2.0. For connecting to InfluxDB 1.7 or earlier instances, use the [influxdb-csharp](https://github.com/influxdata/influxdb-csharp) client library.

The upcoming [Milestone 1.7.0](https://github.com/influxdata/influxdb-client-csharp/milestone/10) comes with supports of InfluxDB 1.8:

```csharp
const string database = "telegraf";
const string retentionPolicy = "autogen";
            
var client = InfluxDBClientFactory.CreateV1("http://localhost:8086",
                "username",
                "password".ToCharArray(),
                database,
                retentionPolicy);
```

For detail info see [InfluxDB 1.8 example](https://github.com/influxdata/influxdb-client-csharp/blob/master/Examples/InfluxDB18Example.cs).

If you would like to use a preview version use our nightly build: [InfluxDB.Client 1.7.0-dev.608](https://www.nuget.org/packages/InfluxDB.Client/1.7.0-dev.608).

Regards
