### ISSUE TITLE
Maybe I found a bug?

### ISSUE THREAD

**Issue by chungou1996** [influxdata/influxdb-client-csharp#79]
Version:influxed 1.8，and client 1.6 support 1.8

when i use 
```
using (WriteApi writer = client.GetWriteApi())
{
writer.WriteMeasurement(WritePrecision.Ns, new Temperature() { ItemName = "item", Value = 1.1, Time = DateTime.Now });
 }
```

program not responding

so I read source code debug,and I see
in client WriteApi.cs
WriteRecord method
`public void WriteRecord(WritePrecision precision, string record)`
millis is 30000
```
while (!condition())
{
    Thread.Sleep(25);
    if (DateTime.Now.Millisecond - start > millis)
        {
            Trace.TraceError($"The WriteApi can't be gracefully dispose! - {millis}ms elapsed.");
            break;
        }
}
```

**Comment by bednar** [comment]
Hi @chungou1996,

Could you share with us how your class `Temperature` looks like?

Regards

**Comment by chungou1996** [comment]
```
[Measurement("mytags")]
    class Temperature
    {
        [Column("itemname", IsTag = true)]
        public string ItemName { get; set; }

        [Column("value")]
        public double Value { get; set; }

        [Column(IsTimestamp = true)]
        public DateTime Time;
    }
```
look 

I don't think millis will more than 30000 milliseconds，so this loop forever ？

**Comment by chungou1996** [comment]
@bednar 
Oh,I find answer
because I  run in UI Thread !!

so I change
 `var response = await RestClient.ExecuteAsync(request).`
to
`var response = await RestClient.ExecuteAsync(request).ConfigureAwait(false);`

and 
```
            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse)await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);
```
to
        ```
    // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse)await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType).ConfigureAwait(false);
```

Is work!!

**Comment by bednar** [comment]
Thx @chungou1996 it looks promising, may it is also related to #68

**Comment by chungou1996** [comment]
@bednar 
please check this code
```
 internal static void WaitToCondition(Func<bool> condition, int millis)
        {
            var start = DateTime.Now.Millisecond;
            while (!condition())
            {
                Thread.Sleep(25);
                if (DateTime.Now.Millisecond - start > millis)
                {
                    Trace.TraceError($"The WriteApi can't be gracefully dispose! - {millis}ms elapsed.");
                    break;
                }
            }
        }
```
DateTime.Now.Millisecond max value 1000
DateTime.Now.Millisecond - start > millis   result will never false
loop forever
the result you want ？

**Comment by bednar** [comment]
Yeah, I got it. Thanks you very much!

**Comment by bednar** [comment]
Hi @chungou1996,

The fixed implementation of `WaitToCondition` - #81 - is merged.

If you would like to use a preview version use our nightly build: [InfluxDB.Client 1.8.0-dev.639](https://www.nuget.org/packages/InfluxDB.Client/1.8.0-dev.639).

Regards

**Comment by chungou1996** [comment]
@bednar 
Great!
I still have a problem, this library does not support synchronous calls in UI Thread, because it will generate a deadlock. Maybe you should consider adding `ConfigureAwait (false)` to the call chain ?
Or did I make a mistake ？
my code like
```
public void button1_Click(object sender,event e)
{
               string query = $"from(bucket: \"{database}/{retentionPolicy}\") " +
                $"|> range(start: {start},stop:{stop})" +
                $"|> filter(fn: (r) =>" +
                $"r._measurement == \"History\" and " +
                $"r.DeviceName == \"{device}\" and " +
                $"r.ItemName == \"{item}\"" +
                $")";
            var queryApi = client.GetQueryApi();
            var task = queryApi.QueryAsync(query);
            vvar fluxTables  = task.result;
```

Thanks you !!!

**Comment by bednar** [comment]
Could you please create a new issue for UI Thread freeze and I will look at it?

**Comment by bednar** [comment]
The #82 fixes synchronous call in UI Thread.

If you would like to use a preview version use our nightly build: [InfluxDB.Client 1.8.0-dev.650](https://www.nuget.org/packages/InfluxDB.Client/1.8.0-dev.650).

**Comment by chungou1996** [comment]
I tried this version, but it does not work.
I think to fix this problem, you must add `ConfigureAwait (false)` to each API asynchronous method call.
（for example QueryAsync
           `return await QueryAsync(query, _options.Org).ConfigureAwait(false)`;
           `return await QueryAsync(CreateQuery(query, _defaultDialect), org).ConfigureAwait(false);`
           ` await QueryAsync(query, org, consumer, ErrorConsumer,EmptyAction).ConfigureAwait(false);`
......calling chains
           `await Task.Run(() => { RestClient.DownloadData(query, true); }).ConfigureAwait(false);`
） 

It is more sensible to run my code in another thread.

Thank you for your efforts!!
