### ISSUE TITLE
Lack of handling HTTP Forbidden (403) 

### ISSUE THREAD

**Issue by Wawszczak** [influxdata/influxdb-client-csharp#80]
When using authenticated connection and 403 is returned, there is exception InfluxDB.Client.Core.Exceptions.HTTPException without any notice about the reason. There is no Internal exception object nor the Error Code is customized. 
I has shown the situation in the screenshot.

![Screenshot](https://user-images.githubusercontent.com/35380086/79613198-5be4ef00-80fe-11ea-9c5d-1b8924d2f985.png)

**Comment by bednar** [comment]
@Wawszczak thanks! we will take a look.

**Comment by bednar** [comment]
Hi @Wawszczak,

The issue is fixed in [1.8.0 milestone](https://github.com/influxdata/influxdb-client-csharp/milestone/11). 

If you would like to use a preview version use our nightly build: [InfluxDB.Client 1.8.0-dev.661](https://www.nuget.org/packages/InfluxDB.Client/1.8.0-dev.661).

Regards
