### ISSUE TITLE
Set Client ReadWriteTimeout

### ISSUE THREAD

**Issue by grantbridges** [influxdata/influxdb-client-csharp#88]
My Write/QueryAsync functions seem to have a default fixed timeout at 10 seconds and I can't figure out how to override it.  The InfluxDBClientFactory.Create(...) has an overload that takes InfluxDBClientOptions which looks to have the settings I want, but I can't instantiate the InfluxDBClientOptions object directly (no public constructor?), only the sealed Builder class within it, which the InfluxDBClientFactory.Create(...) method won't accept.  Am I missing something?

**Comment by bednar** [comment]
Hi @grantbridges,

You could you something like this:

```csharp
var options = new InfluxDBClientOptions.Builder()
    .Url(InfluxDbUrl)
    .AuthenticateToken(_token.ToCharArray())
    .ReadWriteTimeOut(TimeSpan.FromSeconds(1))
    .TimeOut(TimeSpan.FromSeconds(1))
    .Build();

Client = InfluxDBClientFactory.Create(options);
```

Regards

**Comment by grantbridges** [comment]
Fantastic, thank you.  Completely missed that "Build()" method, knew I had to be missing something simple.

**Comment by abrasat** [comment]
@bednar Is the ReadWriteTimeout option still available in the InfluxDBClientOptions? I dont find it anymore...

**Comment by bednar** [comment]
@abrasat The `ReadWriteTimeout ` has been removed in `v4.0.0`:

> The Client no longer supports the `ReadWriteTimeout` for HTTP Client. This settings is not supported by the `HttpClient`. Use can use `Timeout` property instead.

- https://github.com/influxdata/influxdb-client-csharp/blob/master/CHANGELOG.md#api

**Comment by abrasat** [comment]
@bednar : Thanks for that information. Is the Timeout property not used only for the "connect" call? I changed it to 20 seconds and still got the QueryAsync timeout after the default 10 seconds...

**Comment by bednar** [comment]
`Timeout` is the timespan to wait before the HTTP request times out (I will update doc to clarify this). If you use following configuration then the request will timeout after 100 seconds:

```c#
var options = new InfluxDBClientOptions.Builder()
                .Url("http://localhost:8086")
                .AuthenticateToken("my-token")
                .TimeOut(TimeSpan.FromSeconds(100))
                .Build();

var client = InfluxDBClientFactory.Create(options);
```

Do you have configured a `CancellationToken` for your query method? If so on then you have to be careful because the `HttpClient` uses the lesser value of `HttpClient.Timeout` and `CancellationToken’s` timeout.

**Comment by lukinno1** [comment]
if i have older influx 1.7 ? how can i set timeout? 
InfluxDBClientOptions.Builder() is not work.

**Comment by rqueizan** [comment]
> ```cs
> var options = new InfluxDBClientOptions.Builder()
>                 .Url("http://localhost:8086")
>                 .AuthenticateToken("my-token")
>                 .TimeOut(TimeSpan.FromSeconds(100))
>                 .Build();
> 
> var client = InfluxDBClientFactory.Create(options);
> ```

var options = new InfluxDBClientOptions.Builder()
                .Url("http://localhost:8086")
                .AuthenticateToken("my-token")
                .TimeOut(TimeSpan.FromSeconds(100))
                .Build();

var client = new InfluxDBClient(options);

**Comment by rqueizan** [comment]
> ```cs
> var options = new InfluxDBClientOptions.Builder()
>                 .Url("http://localhost:8086")
>                 .AuthenticateToken("my-token")
>                 .TimeOut(TimeSpan.FromSeconds(100))
>                 .Build();
> 
> var client = InfluxDBClientFactory.Create(options);
> ```

`var options = new InfluxDBClientOptions.Builder()
                .Url("http://localhost:8086")
                .AuthenticateToken("my-token")
                .TimeOut(TimeSpan.FromSeconds(100))
                .Build();

var client = new InfluxDBClient(options);`
