### ISSUE TITLE
InfluxDB 2.0 Query limits

### ISSUE THREAD

**Issue by semashkinvg** [influxdata/influxdb-client-csharp#90]
Hi all,
I have a query that basically aggregates data using `aggregateWindow`, then join the aggregate data together to get OHLCV bar. Below, you can see a sample of my query

## The issue

The query works perfectly well from the Data Explorer. In returns me a data set for whatever time period I specify (start, end)
However, when I execute exactly the same query using C# client, I have the following behaviour:

_Time Period - Result_
5 days - no results
1 day - no results
300 minutes - no results
**150 minutes - RETURNS DATA**

### Example of C#
```
var fluxQuery = await File.ReadAllTextAsync("./query.flux")
using var influxDBClient = InfluxDBClientFactory.Create(_configurationBuilder["apiUrl"], _configurationBuilder["apiToken"].ToCharArray());
            var api = influxDBClient.GetQueryApi();
            await api.QueryAsync(fluxQuery, _configurationBuilder["org"],
                (cancellable, record) => { callback(record); },
                delegate(Exception exception) { Console.WriteLine(exception.ToString()); },
                () => { Console.WriteLine("Completed"); });
```
Note:
I do not receive any exceptions, it's completes with no result

One more observation:
A simple "from() ... bla bla bla " query works from C# and Data Explorer very well for any time period

**Is there any limitations of such type of query?**

### Getting data

```
parameters = {
	symbol: "@ESM20",
	start: 2020-01-01T00:00:00Z,
	end: 2020-05-01T00:00:00Z,
	every: 1m,
}
dataset = from(bucket: "test")
	|> range(start: parameters.start, stop: parameters.end)
	|> filter(fn: (r) =>
		(r["_measurement"] == "tickdata"))
	|> filter(fn: (r) =>
		(r["_field"] == "Last" or r["_field"] == "Size"))
	|> filter(fn: (r) =>
		(r["symbol"] == parameters.symbol))
```

### pre-aggregate individual values

```
high = dataset
	|> filter(fn: (r) =>
		(r["_field"] == "Last"))
	|> aggregateWindow(every: 1m, fn: max)
low = dataset
	|> filter(fn: (r) =>
		(r["_field"] == "Last"))
	|> aggregateWindow(every: 1m, fn: min)
....
```

### join tables together 
```
hl = join(tables: {d_low: low, d_high: high}, on: ["_time", "_field"])
	|> map(fn: (r) =>
		({_time: r._time, high: r._value_d_high, low: r._value_d_low}))

.....

```

### Final result

```
join(tables: {d_volume: volume, d_ohlc: ohlc}, on: ["_time"])
	|> map(fn: (r) =>
		({
			_time: r._time,
			high: r.high,
			low: r.low,
			close: r.close,
			open: r.open,
			volume: r._value,
		}))
	|> yield(name: "1")
```

**Comment by russorat** [comment]
@semashkinvg thanks for the issue. we will take a look.

**Comment by bednar** [comment]
Hi @semashkinvg,

there is no limitation for these type of queries. We definitely wants to supports it in our client

Could you please share your query from file `./query.flux`? 

Regards
