### ISSUE TITLE
Bug: 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'

### ISSUE THREAD

**Issue by bnayae** [influxdata/influxdb-client-csharp#98]
I'm experiencing unstable bug which I fail to reproduce by Unit Test.

This is the exception:
System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'

This is the call stack:
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at InfluxDB.Client.WriteApi.Dispose()

As I see it the bug related to:
WriteApi line 200: _influxDbClient.Apis.Remove(this); 
_influxDbClient.Apis is List which is not thread-safe class.
I want to change it to ConcurrentDictionary (via pull request)

**Comment by bnayae** [comment]
I was able to reproduce it with

`
[Test]
public void Race()
{
    var options = new InfluxDBClientOptions.Builder().Url(InfluxDbUrl)
        .LoadConfig()
        .Url(InfluxDbUrl)
        .AuthenticateToken(_token.ToCharArray())
        .Build();
    var point = PointData.Measurement("race-test")
                            .Tag("test", "stress")
                            .Field("value", 1);

    const int RANGE = 1000;
    using (var gateStart = new ManualResetEventSlim(false))
    using (var gate = new CountdownEvent(RANGE))
    using (var gateEnd = new CountdownEvent(RANGE))
    {
        for (int i = 0; i < RANGE; i++)
        {
            var trd = new Thread(() =>
            {
                gateStart.Wait();
                using (WriteApi writer = Client.GetWriteApi())
                {
                    writer.WritePoint(point);
                    gate.Signal();
                    gate.Wait();
                }
                gateEnd.Signal();
            });
            trd.Start();
        }
        gateStart.Set();
        gateEnd.Wait();
    }
}

`

**Comment by bednar** [comment]
Closed by #100
